### PR TITLE
use `run_shell_cmd` in custom easyblock for WIEN2k

### PR DESCRIPTION
**Pull request by boegel**
requires:
* https://github.com/easybuilders/easybuild-framework/pull/4617

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **FAIL (build issue)** _WIEN2k-23.2-intel-2021b.eb_ (partial log available at https://gist.github.com/boegel/ad337c27f8d69e89f45dc897b8bdfaba)

Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3560.doduo.os - Linux RHEL 8.8, x86_64, AMD EPYC 7552 48-Core Processor, Python 3.6.8
See https://gist.github.com/boegel/9aa888bac3dc777bf45a1729a27d0f3d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **FAIL (unhandled exception: name 'log' is not defined)Traceback (most recent call last):
  File "/arcanine/scratch/gent/vo/000/gvo00002/vsc40023/easybuild/eb5/easybuild-framework/easybuild/main.py", line 136, in build_and_install_software
    (ec_res['success'], app_log, err) = build_and_install_one(ec, init_env)
  File "/arcanine/scratch/gent/vo/000/gvo00002/vsc40023/easybuild/eb5/easybuild-framework/easybuild/framework/easyblock.py", line 4299, in build_and_install_one
    result = app.run_all_steps(run_test_cases=run_test_cases)
  File "/arcanine/scratch/gent/vo/000/gvo00002/vsc40023/easybuild/eb5/easybuild-framework/easybuild/framework/easyblock.py", line 4174, in run_all_steps
    self.run_step(step_name, step_methods)
  File "/arcanine/scratch/gent/vo/000/gvo00002/vsc40023/easybuild/eb5/easybuild-framework/easybuild/framework/easyblock.py", line 4009, in run_step
    step_method(self)()
  File "/tmp/eb-u0at5r4i/included-easyblocks-zm0msz18/easybuild/easyblocks/wien2k.py", line 97, in extract_step
    run_shell_cmd(cmd, qa_patterns=qa, qa_wait_patterns=no_qa)
  File "/arcanine/scratch/gent/vo/000/gvo00002/vsc40023/easybuild/eb5/easybuild-framework/easybuild/tools/run.py", line 174, in cache_aware_func
    res = func(cmd, *args, **kwargs)
  File "/arcanine/scratch/gent/vo/000/gvo00002/vsc40023/easybuild/eb5/easybuild-framework/easybuild/tools/run.py", line 511, in run_shell_cmd
    if _answer_question(stdout, proc, qa_patterns, qa_wait_patterns):
  File "/arcanine/scratch/gent/vo/000/gvo00002/vsc40023/easybuild/eb5/easybuild-framework/easybuild/tools/run.py", line 260, in _answer_question
    log.debug("Checking for question pattern '{question}'...")
NameError: name 'log' is not defined
** _WIEN2k-23.2-intel-2021b.eb_ 

Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3560.doduo.os - Linux RHEL 8.8, x86_64, AMD EPYC 7552 48-Core Processor, Python 3.6.8
See https://gist.github.com/boegel/9c8661872054f2f7140d1860a324303f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **FAIL (unhandled exception: name 'log' is not defined)Traceback (most recent call last):
  File "/arcanine/scratch/gent/vo/000/gvo00002/vsc40023/easybuild/eb5/easybuild-framework/easybuild/main.py", line 136, in build_and_install_software
    (ec_res['success'], app_log, err) = build_and_install_one(ec, init_env)
  File "/arcanine/scratch/gent/vo/000/gvo00002/vsc40023/easybuild/eb5/easybuild-framework/easybuild/framework/easyblock.py", line 4299, in build_and_install_one
    result = app.run_all_steps(run_test_cases=run_test_cases)
  File "/arcanine/scratch/gent/vo/000/gvo00002/vsc40023/easybuild/eb5/easybuild-framework/easybuild/framework/easyblock.py", line 4174, in run_all_steps
    self.run_step(step_name, step_methods)
  File "/arcanine/scratch/gent/vo/000/gvo00002/vsc40023/easybuild/eb5/easybuild-framework/easybuild/framework/easyblock.py", line 4009, in run_step
    step_method(self)()
  File "/tmp/eb-xuxbimro/included-easyblocks-l4pu5mzy/easybuild/easyblocks/wien2k.py", line 97, in extract_step
    run_shell_cmd(cmd, qa_patterns=qa, qa_wait_patterns=no_qa)
  File "/arcanine/scratch/gent/vo/000/gvo00002/vsc40023/easybuild/eb5/easybuild-framework/easybuild/tools/run.py", line 174, in cache_aware_func
    res = func(cmd, *args, **kwargs)
  File "/arcanine/scratch/gent/vo/000/gvo00002/vsc40023/easybuild/eb5/easybuild-framework/easybuild/tools/run.py", line 511, in run_shell_cmd
    if _answer_question(stdout, proc, qa_patterns, qa_wait_patterns):
  File "/arcanine/scratch/gent/vo/000/gvo00002/vsc40023/easybuild/eb5/easybuild-framework/easybuild/tools/run.py", line 260, in _answer_question
    log.debug("Checking for question pattern '{question}'...")
NameError: name 'log' is not defined
** _WIEN2k-23.2-intel-2021b.eb_ 

Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3560.doduo.os - Linux RHEL 8.8, x86_64, AMD EPYC 7552 48-Core Processor, Python 3.6.8
See https://gist.github.com/boegel/239917943b239b3d35331ada63d64e0a for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **FAIL (build issue)** _WIEN2k-23.2-intel-2021b.eb_ (partial log available at https://gist.github.com/boegel/69fa0716418d934a30200db0af2c6a2a)

Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3560.doduo.os - Linux RHEL 8.8, x86_64, AMD EPYC 7552 48-Core Processor, Python 3.6.8
See https://gist.github.com/boegel/db0f0de77c1248e1094e88b7d98ef7f0 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **FAIL (build issue)** _WIEN2k-23.2-intel-2021b.eb_ (partial log available at https://gist.github.com/boegel/a4c6a18bde50aacbb7d3cff984cf5799)

Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3560.doduo.os - Linux RHEL 8.8, x86_64, AMD EPYC 7552 48-Core Processor, Python 3.6.8
See https://gist.github.com/boegel/d02415ab610cf15a6f3e822aef82bc29 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **FAIL (build issue)** _WIEN2k-23.2-intel-2021b.eb_ (partial log available at https://gist.github.com/boegel/29b99218f4595f980b36c906a236accc)

Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3560.doduo.os - Linux RHEL 8.8, x86_64, AMD EPYC 7552 48-Core Processor, Python 3.6.8
See https://gist.github.com/boegel/8b0bd889b9368e6bedbff1f4a84d1c38 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **FAIL (build issue)** _WIEN2k-23.2-intel-2021b.eb_ (partial log available at https://gist.github.com/boegel/688032391d744d7c67402f7b2ac5751e)

Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3560.doduo.os - Linux RHEL 8.8, x86_64, AMD EPYC 7552 48-Core Processor, Python 3.6.8
See https://gist.github.com/boegel/40406fe7a2385d6ab08f836bf99dc206 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _WIEN2k-23.2-intel-2021b.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3504.doduo.os - Linux RHEL 8.8, x86_64, AMD EPYC 7552 48-Core Processor, Python 3.6.8
See https://gist.github.com/boegel/c12056e0b05d0a2adbddeb21d29e2770 for a full test report.

**Review by branfosj — APPROVED** [review]

**Pull request merged**
