### PR TITLE
update Clang easyblock for versions >= 16 + run tests only for final stage of bootstrap build

### PR DESCRIPTION
**Pull request by geimer**
Fix sanity check for Clang 16+ and run tests only for final stage of bootstrap build.

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _Clang-12.0.1-GCCcore-10.3.0.eb_ 
 * **SUCCESS** _Clang-12.0.1-GCCcore-11.2.0.eb_ 
 * **SUCCESS** _Clang-13.0.1-GCCcore-11.3.0.eb_ 
 * **SUCCESS** _Clang-15.0.5-GCCcore-11.3.0.eb_ 

Build succeeded for 4 out of 4 (4 easyconfigs in total)
jsczen2c1.int.jsc-zen2.easybuild-test.cluster - Linux Rocky Linux 8.5, x86_64, AMD EPYC 7742 64-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/SebastianAchilles/7fd4d39e28005f7ed345e44de7f053ec for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @SebastianAchilles
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _Clang-11.0.0-GCCcore-9.3.0.eb_ 
 * **SUCCESS** _Clang-11.0.1-GCCcore-10.2.0.eb_ 
 * **SUCCESS** _Clang-11.0.1-gcccuda-2020b.eb_ 
 * **SUCCESS** _Clang-12.0.1-GCCcore-10.3.0-CUDA-11.3.1.eb_ 
 * **SUCCESS** _Clang-12.0.1-GCCcore-10.3.0.eb_ 
 * **SUCCESS** _Clang-12.0.1-GCCcore-11.2.0.eb_ 
 * **SUCCESS** _Clang-13.0.1-GCCcore-11.2.0-CUDA-11.4.1.eb_ 
 * **SUCCESS** _Clang-13.0.1-GCCcore-11.2.0.eb_ 
 * **SUCCESS** _Clang-13.0.1-GCCcore-11.3.0.eb_ 

Build succeeded for 9 out of 9 (9 easyconfigs in total)
cnx2 - Linux Rocky Linux 8.5, x86_64, Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz (haswell), Python 3.6.8
See https://gist.github.com/SebastianAchilles/dc0ab2420d34a6c75eb29206c94491aa for a full test report.

**Comment by boegel** [comment]
@geimer Can you briefly elaborate why running the tests for the earlier stages doesn't make much sense?

**Comment by geimer** [comment]
@boegel Sorry for being unresponsive.  I took a couple of days off.

At the end of the day, the tests are supposed to ensure that the installed software is doing "the right thing".  So running them for the final stage is mandatory if tests are enabled.  Now, one could argue that executing the tests also for the stage-1 and stage-2 builds of a bootstrap build may catch compiler failures early.  However, compiling and running the tests two additional times also isn't for free.  In fact, it takes a considerable amount of time.  Thus, there is a tradeoff here.  And since the probability of failure should -- at least in theory -- be rather low, the cost/benefit ratio is to my mind pretty bad.  Those compute cycles should be used for something more productive, IMHO.

**Comment by geimer** [comment]
@boegel Does that make sense?  Any more feedback?

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
@geimer Makes total sense, thanks for elaborating.

I'll submit a test report too, for what it's worth, but this is good to in imho.

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _Clang-12.0.1-GCCcore-11.2.0.eb_ 
 * **SUCCESS** _Clang-13.0.1-GCCcore-11.2.0-CUDA-11.4.1.eb_ 
 * **SUCCESS** _Clang-13.0.1-GCCcore-11.2.0.eb_ 
 * **SUCCESS** _Clang-13.0.1-GCCcore-11.3.0.eb_ 
 * **SUCCESS** _Clang-15.0.5-GCCcore-11.3.0.eb_ 

Build succeeded for 5 out of 5 (5 easyconfigs in total)
node3115.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/56e6f0e3f7a70ea3802aa4177ef55908 for a full test report.

**Pull request merged**
