### PR TITLE
Ignore Python from virtualenvs in GROMACS configure via `-DPython3_FIND_VIRTUALENV=STANDARD`

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

As reported in [Slack](https://easybuild.slack.com/archives/C34UA1HT7/p1712147065575909) GROMACS may pick up Python from an active virtualenv (e.g. when EasyBuild is installed in a virtualenv) instead of from the Python module

This is caused by GROMACS explicitly preferring that:
```
if(NOT Python3_FIND_VIRTUALENV)
    # We advocate using Python venvs to manage package availability, so by default
    # we want to preferentially discover user-space software.
    set(Python3_FIND_VIRTUALENV FIRST)
endif()
```

This happens when `find_package(Python3)` is used which is the case for version 2021 and up. The current `self.cfg.update('configopts', "-DPYTHON_EXECUTABLE=%s" % bin_python)` only applies to usages of `find_package(PythonInterp ...)` which are still present (e.g. in the gtest submodule) but not used exclusively as they are deprecated by CMake 3.12+ in favor of `FindPython/2/3`

This change avoids it picking up the virtualenv by setting the CMake variable which avoids GROMACS changing it.

Especially together with #3282 the intended Python should be picked up.

I also did a quick Search&Replace to avoid constructing `LooseVersion(self.version)` many times in this function.

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _GROMACS-2020-foss-2019b.eb_ 
 * **SUCCESS** _GROMACS-2021.3-foss-2021a.eb_ 
 * **SUCCESS** _GROMACS-2021.5-foss-2021b.eb_ 
 * **SUCCESS** _GROMACS-2021-foss-2020b.eb_ 
 * **SUCCESS** _GROMACS-2023.1-foss-2022a.eb_ 
 * **SUCCESS** _GROMACS-2023.3-foss-2022a.eb_ 
 * **SUCCESS** _GROMACS-2023.3-foss-2023a.eb_ 
 * **SUCCESS** _GROMACS-2024.1-foss-2023b.eb_ 

Build succeeded for 8 out of 8 (8 easyconfigs in total)
n1459 - Linux RHEL 8.7 (Ootpa), x86_64, Intel(R) Xeon(R) Platinum 8470 (icelake), Python 3.8.13
See https://gist.github.com/Flamefire/d6a8736ee2f5f5cb16b22896fbb80ac2 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by bedroge** [comment]
I also just ran into this issue when trying to make/test an easyconfig for GROMACS 2024.3. Initially the configure step showed this:
```
-- Found Python3: /home/bob/venvs/eb/bin/python3.12 (found suitable version "3.12.3", minimum required is "3.7") found components: Interpreter Development Development.Module Developmen
t.Embed 
```
and it failed in some test step because gmxapi was built for this wrong Python version.

Then I used the fix from this PR, and it picked up the right Python (which also allowed the tests to run):
```
-- Found Python3: /data/apps/software/Python/3.11.5-GCCcore-13.2.0/bin/python3.11 (found suitable version "3.11.5", minimum required is "3.7") found components: Interpreter Development Development.Module Development.Embed 
```

@boegel was there any reason why you hadn't hit the merge button after having approved the changes?

**Review by ocaisa — APPROVED** [review]

**Comment by ocaisa** [comment]
Tested in https://github.com/easybuilders/easybuild-easyconfigs/pull/21430

**Pull request merged**
