### PR TITLE
Add missing arch lib path to ipp module.

### PR DESCRIPTION
**Pull request by akesandgren**
Also do sanity check on the actual (selected) arch lib path.

### CODE REVIEW

**Comment by boegel** [comment]
@akesandgren Sorry for not picking up on this... Can you clarify why you closed this?

**Comment by akesandgren** [comment]
There is another PR that does the same thing that has been merged already.
Well, except that mine used self.arch at some places instead of hardcoding intel64.

**Comment by boegel** [comment]
@akesandgren Is it worth opening a follow-up PR to fix the hardcoding?

**Comment by akesandgren** [comment]
That's my intention but there's no need to stress about it.

**Pull request closed without merging**
