### PR TITLE
Handle failure of running nvidia-smi in TensorFlow tests

### PR DESCRIPTION
**Pull request by Flamefire**
Correctly fall back to skipping GPU tests

### CODE REVIEW

**Comment by ocaisa** [comment]
@surak Can you check if this works for you?

**Comment by surak** [comment]
> @surak Can you check if this works for you?

Testing now, TF takes a while to install on juwels

**Comment by surak** [comment]
This test passes now

**Review by ocaisa — COMMENTED** [review]
Code changes are fine but it is takes a bit of digging to figure out why this was the necessary change. My digging said it was to avoid https://github.com/easybuilders/easybuild-framework/blob/develop/easybuild/tools/run.py#L574, I think this warrants a comment and I would still probably explicitly include `log_all=False` even though this is the default since that also features in the relevant line.

**Comment by ocaisa** [comment]
I guess this is a very niche case where `nvidia-smi` is available but there are no GPUs

**Comment by Flamefire** [comment]
@ocaisa Makes sense. Added.

**Review by ocaisa — APPROVED** [review]

**Pull request merged**
