### PR TITLE
ensure lib subdirectory is found in stage 2 of GCC installation + fall back to lib64

### LINKED ISSUE #2309: GCCcore/9.3.0 fails to find GMP in stage2 for ISL on OpenSUSE Leap 15.2
After fixing binutils on OpenSUSE Leap 15.2 I'm trying to build the full foss/2020a toolchain.

During the build of GCCcore/9.3.0 while configuring ISL for stage 2 with the following `run_cmd` command, it finds the header but not the static library in the stage2 prefix:
```
./configure --prefix=/tmp/eb-build/GCCcore/9.3.0/system-system/gcc-9.3.0/stage2_stuff --with-pic --disable-shared --with-gmp=system --with-gmp
-prefix=/tmp/eb-build/GCCcore/9.3.0/system-system/gcc-9.3.0/stage2_stuff  --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu
```
```
checking which gmp to use... system
checking gmp.h usability... yes
checking gmp.h presence... yes
checking for gmp.h... yes
checking for main in -lgmp... no
configure: error: gmp library not found
```
The failing `config.log` test uses this command line:
```
configure:19076: gcc -o conftest -O3 -fomit-frame-pointer -malign-double -fstrict-aliasing -ffast-math -I/tmp/eb-build/GCCcore/9.3.0/system-system/gcc-9.3.0/stage2_stuff/include  -L/tmp/eb-build/GCCcore/9.3.0/system-system/gcc-9.3.0/stage2_stuff/lib -I/tmp/eb-build/GCCcore/9.3.0/system-system/gcc-9.3.0/stage2_stuff/include  -L/tmp/eb-build/GCCcore/9.3.0/system-system/gcc-9.3.0/stage2_stuff/lib  conftest.c -lgmp  -lgmp  >&5 
```

The given `-L/tmp/eb-build/GCCcore/9.3.0/system-system/gcc-9.3.0/stage2_stuff/lib` location for GMP is incorrect as on this platform, the library is in a `lib64` directory: `/tmp/eb-build/GCCcore/9.3.0/system-system/gcc-9.3.0/stage2_stuff/lib64/libgmp.a`

@bartoldeman found a part in `gcc.py` that assumes that libraries are installed in a `lib` directory, not sure if that's a root cause or just an attempt to plaster over this GCC build behaviour on some platforms: https://github.com/easybuilders/easybuild-easyblocks/blob/6e63e1498a849f5e0bc8c57eef614e3bd4fea8ff/easybuild/easyblocks/g/gcc.py#L595-L601

### PR DESCRIPTION
**Pull request by boegel**
fixes #2309

### CODE REVIEW

**Comment by zao** [comment]
Test report by @zao
#### Overview of tested easyconfigs (in order)
 * **FAIL (build issue)** _GCCcore-9.3.0.eb_ (partial log available at https://gist.github.com/85e16b9a29daf313d0fea48cacb2d2b2)

Build succeeded for 0 out of 1 (1 easyconfigs in total)
eb-suse152 - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 3.6.12
See https://gist.github.com/fc9ec48f73f14f4b46b5ea88cc1fc230 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _GCCcore-9.3.0.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3551.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/4a6f0251291ed3de04bab98e9a3c9868 for a full test report.

**Review by akesandgren — APPROVED** [review]
LGTM

**Comment by akesandgren** [comment]
Going in, thanks @boegel!

**Pull request merged**
