### PR TITLE
ensure libQt5Core.so is compatible with older Linux kernels by disabling renameat2 and getentropy features

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

This is a fix for a weird problem that arises when installing `Qt5` on a system with a Linux kernel older than 3.17 (for example, on CentOS 7) while using a recent `glibc` version (for example in a Gentoo Prefix environment):

```
/tmp/easybuild/build/Qt5/5.14.1/GCCcore-9.3.0/qt-everywhere-src-5.14.1/qtbase/bin/qvkgen:
error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
```

Even though `libQt5Core.so.5` *is* there at a location that can be found, the Linux loader is blatantly ignoring it because it's tagged to only be compatible with Linux kernel 3.17.

see also https://bugs.gentoo.org/669994

### CODE REVIEW

**Comment by boegel** [comment]
@bartoldeman Any reference to why `-no-feature-statx` is required?

With these changes, the `Qt5` installation is working fine on a CentOS 7 host (kernel 3.10) in a Gentoo Prefix environment (glibc 2.32).

**Comment by bartoldeman** [comment]
> @bartoldeman Any reference to why `-no-feature-statx` is required?

see e.g. https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-qt/qtcore/qtcore-5.15.0.ebuild#n77

I'll have to dig a bit to see if statx is really an issue or not. I'll get back to you later.

**Comment by bartoldeman** [comment]
I suspect but haven't confirmed that since
https://code.qt.io/cgit/qt/qtbase.git/commit/?id=b7887f9b4faad222
it may only be necessary to disable getentropy as glibc should take care of the rest now.

**Comment by bartoldeman** [comment]
from the Qt changelog for 5.12.3: https://code.qt.io/cgit/qt/qtbase.git/plain/dist/changes-5.12.3?h=v5.12.3

```
 - Linux:
   * [QTBUG-74526] Changed the way we use the statx() system call to use a
     fallback mechanism provided by the GNU C library. This should allow Qt
     applications that are compiled with glibc >= 2.28 to run even on kernels
     older than 4.11.

```

so since 5.12.3 it's ok not to explicitly disable statx. However following `qtbase/src/corelib/global/minimum-linux_p.h` getentropy and renameat2 indeed need to be disabled, or qt apps simply don't run on kernels < 3.16.

**Pull request merged**
