### PR TITLE
update PETSc easyblock to take into account that ScaLAPACK installation may not have header files + fix building in parallel

### PR DESCRIPTION
**Pull request by boegel**
`ScaLAPACK/2.1.0-gompi-2020b` does not provide any header files, because the installation was done via CMake.

Apparently PETSc doesn't require the ScaLAPACK header files at all, so there's no point in requiring them.

In addition, building in parallel requires passing `MAKE_NP=...` to the `make` command as an argument, just defining the `$MAKE_NP` doesn't make any difference...

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _PETSc-3.12.4-foss-2020a-Python-3.8.2.eb_ 
 * **SUCCESS** _PETSc-3.12.4-intel-2020a-Python-3.8.2.eb_ 

Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3152.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/cec1ca24dda716a17113cea2626e10fc for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _PETSc-3.11.0-foss-2018b-downloaded-deps.eb_ 
 * **SUCCESS** _PETSc-3.12.4-foss-2019b-Python-3.7.4.eb_ 
 * **SUCCESS** _PETSc-3.12.4-foss-2020a-Python-3.8.2.eb_ 
 * **SUCCESS** _PETSc-3.12.4-intel-2019b-Python-2.7.16.eb_ 
 * **SUCCESS** _PETSc-3.12.4-intel-2019b-Python-3.7.4.eb_ 
 * **SUCCESS** _PETSc-3.12.4-intel-2020a-Python-3.8.2.eb_ 
 * **SUCCESS** _PETSc-3.9.3-foss-2018a.eb_ 

Build succeeded for 7 out of 7 (7 easyconfigs in total)
node2685.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/f64c3d0f200ee1848f99a78217a9f1a9 for a full test report.

**Review by akesandgren — APPROVED** [review]
LGTM

**Comment by akesandgren** [comment]
Going in, thanks @boegel!

**Pull request merged**
