### PR TITLE
Add support for Bazel 7+

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _Java-21.0.2.eb_ 
 * **SUCCESS** _Java-21.eb_ 
 * **FAIL (build issue)** _Bazel-7.2.0-GCCcore-12.2.0.eb_ (partial log available at https://gist.github.com/Flamefire/e497b7332c6d91a189bec3119c4d3b57)

Build succeeded for 2 out of 3 (1 easyconfigs in total)
n1610 - Linux RHEL 8.7 (Ootpa), x86_64, Intel(R) Xeon(R) Platinum 8470 (icelake), Python 3.8.13
See https://gist.github.com/Flamefire/bb9b5f91e3cfa8368cdd5b22721f4035 for a full test report.

**Comment by akesandgren** [comment]
Ha, just what I was trying to start playing with yesterday...

**Comment by Flamefire** [comment]
Test report by @Flamefire
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _Bazel-7.2.0-GCCcore-12.2.0.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
n1610 - Linux RHEL 8.7 (Ootpa), x86_64, Intel(R) Xeon(R) Platinum 8470 (icelake), Python 3.8.13
See https://gist.github.com/Flamefire/b3e19cf7eef8603f60dfa6b46f6222f2 for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _Bazel-7.2.0-GCCcore-13.2.0.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/akesandgren/69139df142e2210961016c767865d3ce for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
