### PR TITLE
fix Boost sanity check on aarch64

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _Boost-1.67.0-intel-2018b.eb_ 
 * **SUCCESS** _Boost-1.71.0-iimpi-2019b.eb_ 
 * **SUCCESS** _Boost-1.72.0-iimpi-2020a.eb_ 
 * **SUCCESS** _Boost-1.74.0-GCC-10.2.0.eb_ 
 * **SUCCESS** _Boost-1.74.0-iccifort-2020.4.304.eb_ 

Build succeeded for 5 out of 5 (5 easyconfigs in total)
node3407.kirlia.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 3.6.8
See https://gist.github.com/ad35d97529367b8c6c3f5c4fc38bc6cb for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _Boost-1.74.0-GCC-10.2.0.eb_ 
 * **SUCCESS** _Boost-1.74.0-iccifort-2020.4.304.eb_ 

Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3508.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/b543fbe5057fdc18229c30f4b60cb2ad for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _Boost-1.74.0-GCC-10.2.0.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild2.novalocal - Linux centos linux 8.3.2011, POWER, IBM pSeries (emulated by qemu) (power9le), Python 3.6.8
See https://gist.github.com/0aa5825b5681319408b144df2474016b for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @boegel!

**Pull request merged**
