### PR TITLE
Workaround for XCrySDen for Tcl 8.6

### PR DESCRIPTION
**Pull request by Micket**
XCrySDen is old, and patching all it's broken Tcl code doesn't sound fun. Workaround for now.

I also made mesa optional, so that I can use this block myself (since we filter-deps Mesa)

### CODE REVIEW

**Comment by boegel** [comment]
@Micket Can you clarify what effect using `-DUSE_INTERP_RESULT` has exactly?

**Comment by Micket** [comment]
The Tcl API have optional return strings (which XCrySDen uses all over the place, for error messages if i recall correctly), but this part of the API was deprecated in 8.6. `-DUSE_INTERP_RESULT` reactivates this feature, as it was prior to 8.6. Do you want me to comment the code?

**Comment by boegel** [comment]
@Micket Yes, please clarify this using a comment above the line adding `-DUSE_INTERP_RESULT` to `$CFLAGS`.

**Comment by smoors** [comment]
tested with https://github.com/easybuilders/easybuild-easyconfigs/pull/8477

**Pull request merged**
