### PR TITLE
fix netCDF support in Siesta easyblock

### PR DESCRIPTION
**Pull request by migueldiascosta**
(created using `eb --new-pr`)

fixes https://github.com/easybuilders/easybuild-easyblocks/issues/1965

### CODE REVIEW

**Comment by smoors** [comment]
@migueldiascosta could you generate a test report for https://github.com/easybuilders/easybuild-easyconfigs/pull/9858 with this fix applied?

**Comment by migueldiascosta** [comment]
@smoors done, https://github.com/easybuilders/easybuild-easyconfigs/pull/9858#issuecomment-589003626

**Comment by boegel** [comment]
Hmm, did this break `Siesta-4.1-b4-foss-2018b.eb`?

I'm getting this now:

```
netcdf_ncdf.f90:59:6:

   use netcdf
      1
Fatal Error: Can't open module file netcdf.mod for reading at (1): No such file or directory
compilation terminated.
```

**Comment by migueldiascosta** [comment]
bummer... will look into it

**Comment by migueldiascosta** [comment]
the include flag for netcdf is not being picked up when building siesta's ncdf module, this fixes it
```diff
--- siesta.py.orig	2020-02-21 12:58:08.255020893 +0800
+++ siesta.py	2020-02-21 14:32:21.233017759 +0800
@@ -181,6 +181,7 @@
                     (r"^(COMP_LIBS\s*=.*)$", r"\1 libncdf.a libfdict.a"),
                 ])
                 netcdf_lib_and_inc = "NETCDF_LIBS = -lnetcdff\nNETCDF_INCLUDE = -I%s/include" % netcdff_loc
+                netcdf_lib_and_inc += "\nINCFLAGS = $(NETCDF_INCLUDE)"
                 regex_newlines.append((r"^(COMP_LIBS\s*=.*)$", r"\1\n%s" % netcdf_lib_and_inc))
 
             xmlf90 = get_software_root('xmlf90')
```
but I don't know why it is only needed with foss and not with intel...

**Comment by boegel** [comment]
@migueldiascosta Could be a difference between `gfortran` & `ifort` w.r.t. which environment variables (like `$CPATH`) they pick up on...

Can you open a pull request for that fix?

**Comment by boegel** [comment]
Ah, already there in #1971, thanks :)

**Pull request merged**
