### PR TITLE
enhance TensorFlow easyblock to avoid use of `-mcpu=native` for XNNPACK component when building on aarch64

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
fixes https://github.com/easybuilders/easybuild-easyconfigs/issues/18899

### CODE REVIEW

**Comment by akesandgren** [comment]
Any test reports coming up for this?

**Comment by boegel** [comment]
@akesandgren Yes, but there's other fixes needed for recent TensorFlow versions on `aarch64`, so this needs to be paired with easyconfig PRs.

I guess we could go ahead and merge this already, since it clearly doesn't hurt on `x86_64`...

**Review by akesandgren — APPROVED** [review]
LGTM

**Comment by akesandgren** [comment]
Going in, thanks @boegel!

**Pull request merged**
