### PR TITLE
Add sanity check commands to GCC (including LTO support)

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _GCCcore-10.2.0.eb_ 
 * **SUCCESS** _GCCcore-10.1.0.eb_ 
 * **SUCCESS** _GCCcore-9.1.0.eb_ 
 * **SUCCESS** _GCCcore-8.3.0.eb_ 
 * **SUCCESS** _GCCcore-7.3.0.eb_ 
 * **SUCCESS** _GCCcore-8.1.0.eb_ 

Build succeeded for 6 out of 6 (6 easyconfigs in total)
taurusi4244.taurus.hrsk.tu-dresden.de - Linux RHEL 7.9, x86_64, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 3.6.8
See https://gist.github.com/1521f2112d6c30dfab0ebbd51ba5367c for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _GCCcore-10.2.0.eb_ 
 * **SUCCESS** _GCCcore-10.1.0.eb_ 
 * **SUCCESS** _GCCcore-9.1.0.eb_ 
 * **SUCCESS** _GCCcore-8.3.0.eb_ 
 * **SUCCESS** _GCCcore-7.3.0.eb_ 
 * **SUCCESS** _GCCcore-8.1.0.eb_ 

Build succeeded for 6 out of 6 (6 easyconfigs in total)
taurusml19 - Linux RHEL 7.6, POWER, 8335-GTX, Python 2.7.5
See https://gist.github.com/66c5cc486a1e7aa2d6de4018066e21eb for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _GCCcore-10.2.0.eb_ 
 * **SUCCESS** _GCCcore-7.3.0.eb_ 
 * **SUCCESS** _GCCcore-8.2.0.eb_ 
 * **SUCCESS** _GCCcore-8.3.0.eb_ 
 * **SUCCESS** _GCCcore-9.2.0.eb_ 
 * **SUCCESS** _GCCcore-9.3.0.eb_ 

Build succeeded for 6 out of 6 (6 easyconfigs in total)
node3551.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/a264be034eaf5f09e0ef0fbe876927e8 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _GCC-4.9.2.eb_ 
 * **SUCCESS** _GCCcore-10.1.0.eb_ 
 * **SUCCESS** _GCCcore-10.2.0.eb_ 
 * **SUCCESS** _GCCcore-4.9.2.eb_ 
 * **SUCCESS** _GCCcore-4.9.3.eb_ 
 * **SUCCESS** _GCCcore-4.9.4.eb_ 
 * **SUCCESS** _GCCcore-5.3.0.eb_ 
 * **SUCCESS** _GCCcore-5.4.0.eb_ 
 * **SUCCESS** _GCCcore-5.5.0.eb_ 
 * **SUCCESS** _GCCcore-6.1.0.eb_ 
 * **SUCCESS** _GCCcore-6.2.0.eb_ 
 * **SUCCESS** _GCCcore-6.3.0.eb_ 
 * **SUCCESS** _GCCcore-6.4.0.eb_ 
 * **SUCCESS** _GCCcore-6.5.0.eb_ 
 * **SUCCESS** _GCCcore-7.1.0.eb_ 
 * **SUCCESS** _GCCcore-7.2.0.eb_ 
 * **SUCCESS** _GCCcore-7.3.0.eb_ 
 * **SUCCESS** _GCCcore-7.4.0.eb_ 
 * **SUCCESS** _GCCcore-8.1.0.eb_ 
 * **SUCCESS** _GCCcore-8.2.0.eb_ 
 * **SUCCESS** _GCCcore-8.3.0.eb_ 
 * **SUCCESS** _GCCcore-9.1.0.eb_ 
 * **SUCCESS** _GCCcore-9.2.0.eb_ 
 * **SUCCESS** _GCCcore-9.3.0.eb_ 
 * **SUCCESS** _GCC-10.2.0.eb_ 
 * **SUCCESS** _GCC-4.9.3-2.25.eb_ 
 * **SUCCESS** _GCC-5.4.0-2.26.eb_ 
 * **SUCCESS** _GCC-6.3.0-2.27.eb_ 
 * **SUCCESS** _GCC-6.4.0-2.28.eb_ 
 * **SUCCESS** _GCC-7.2.0-2.29.eb_ 
 * **SUCCESS** _GCC-7.3.0-2.30.eb_ 
 * **SUCCESS** _GCC-8.2.0-2.31.1.eb_ 
 * **SUCCESS** _GCC-8.3.0.eb_ 
 * **SUCCESS** _GCC-9.3.0.eb_ 

Build succeeded for 34 out of 34 (34 easyconfigs in total)
node2610.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/d4ccc32a315850ac49515e332e4f9e55 for a full test report.

**Pull request merged**
