### PR TITLE
update OpenFOAM easyblock to support OpenFOAM 10 + clean up variant/version checks

### PR DESCRIPTION
**Pull request by mboisson**
I introduce `is_extend`, `is_dot_org` and `is_dot_com`, and use them to simplify the logic which was becoming rather unwieldy with version comparisons. 

The second commit is to update OpenFOAM's list of tools for version 10+

### CODE REVIEW

**Comment by kosl** [comment]
See https://github.com/easybuilders/easybuild-easyconfigs/pull/16259

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _OpenFOAM-7-foss-2019b-20200508.eb_ 
 * **SUCCESS** _OpenFOAM-8-foss-2020a.eb_ 
 * **SUCCESS** _OpenFOAM-8-foss-2020b.eb_ 
 * **SUCCESS** _OpenFOAM-9-foss-2021a.eb_ 
 * **SUCCESS** _OpenFOAM-v2006-foss-2020a.eb_ 
 * **SUCCESS** _OpenFOAM-v2012-foss-2020a.eb_ 
 * **SUCCESS** _OpenFOAM-v2106-foss-2021a.eb_ 
 * **SUCCESS** _OpenFOAM-v2112-foss-2021b.eb_ 

Build succeeded for 8 out of 8 (8 easyconfigs in total)
node3703.slaking.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 3.6.8
See https://gist.github.com/9a996abc405d89d721ad9e5c049a7706 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _OpenFOAM-Extend-4.1-20200408-foss-2019b-Python-2.7.16.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3701.slaking.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 3.6.8
See https://gist.github.com/1494b4f3c504a836c0621e45dfb03f02 for a full test report.

**Pull request merged**
