### PR TITLE
enhance BWA easyblock: pass compiler flags + use filetools functions

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
No BWA easyconfigs were hurt by these changes, test report for all existing BWA easyconfigs coming up...

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _BWA-0.7.17-GCC-8.2.0-2.31.1.eb_ 
 * **SUCCESS** _BWA-0.7.17-GCC-8.3.0.eb_ 
 * **SUCCESS** _BWA-0.7.17-GCC-9.3.0.eb_ 
 * **SUCCESS** _BWA-0.7.17-iccifort-2019.1.144-GCC-8.2.0-2.31.1.eb_ 
 * **SUCCESS** _BWA-0.7.17-iccifort-2019.5.281.eb_ 

Build succeeded for 5 out of 5 (5 easyconfigs in total)
node3507.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/aabd1cf3526cbe146a33f24025577310 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _BWA-0.7.12-foss-2016b.eb_ 
 * **SUCCESS** _BWA-0.7.13-foss-2016a.eb_ 
 * **SUCCESS** _BWA-0.7.13-intel-2016a.eb_ 
 * **SUCCESS** _BWA-0.7.15-GCCcore-5.4.0.eb_ 
 * **SUCCESS** _BWA-0.7.15-GCCcore-6.4.0.eb_ 
 * **SUCCESS** _BWA-0.7.15-foss-2016a.eb_ 
 * **SUCCESS** _BWA-0.7.15-foss-2016b.eb_ 
 * **SUCCESS** _BWA-0.7.15-intel-2016b.eb_ 
 * **SUCCESS** _BWA-0.7.15-intel-2017a.eb_ 
 * **SUCCESS** _BWA-0.7.16a-foss-2016b.eb_ 
 * **SUCCESS** _BWA-0.7.16a-intel-2017a.eb_ 
 * **SUCCESS** _BWA-0.7.17-GCC-8.2.0-2.31.1.eb_ 
 * **SUCCESS** _BWA-0.7.17-GCC-8.3.0.eb_ 
 * **SUCCESS** _BWA-0.7.17-GCC-9.3.0.eb_ 
 * **SUCCESS** _BWA-0.7.17-foss-2017b.eb_ 
 * **SUCCESS** _BWA-0.7.17-foss-2018a.eb_ 
 * **SUCCESS** _BWA-0.7.17-foss-2018b.eb_ 
 * **SUCCESS** _BWA-0.7.17-iccifort-2019.1.144-GCC-8.2.0-2.31.1.eb_ 
 * **SUCCESS** _BWA-0.7.17-iccifort-2019.5.281.eb_ 
 * **SUCCESS** _BWA-0.7.17-intel-2017b.eb_ 
 * **SUCCESS** _BWA-0.7.17-intel-2018a.eb_ 
 * **SUCCESS** _BWA-0.7.17-intel-2018b.eb_ 

Build succeeded for 22 out of 22 (22 easyconfigs in total)
node2606.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/10e41aa00ca2b78f618d2ffa77a892cd for a full test report.

**Comment by boegel** [comment]
@verdurin https://github.com/easybuilders/easybuild-easyconfigs/pull/12472 is merged already, but that requires the changes in this easyblock...

**Review by verdurin — APPROVED** [review]

**Pull request merged**
