### PR TITLE
[binutils] Include own lib dir in rpath before system lib dirs

### PR DESCRIPTION
**Pull request by Flamefire**
Avoids taking a system lib over an installed lib
Fixes https://github.com/easybuilders/easybuild-easyconfigs/issues/10056

@zao

### CODE REVIEW

**Comment by zao** [comment]
```
$ eb binutils-2.34.eb
...
== COMPLETED: Installation ended successfully (took 1 min 46 sec)
```

**Comment by zao** [comment]
This is on Ubuntu 20.04, I have yet to test anything on the Arch Linux described in https://github.com/easybuilders/easybuild-easyconfigs/issues/10056

**Comment by Flamefire** [comment]
Ah yes the issue is in the EC repo. Updated the commit and description, no other change

**Comment by zao** [comment]
Arch Linux seems a bit link-happy still but it finds the right libctf at least:
```
== 2020-04-27 12:54:45,808 run.py:540 DEBUG cmd "ldd /hp/eb/software/binutils/2.34/bin/objdump" exited with exit code 0 and output:
        linux-vdso.so.1 (0x00007ffc31093000)
        libopcodes-2.34.so => /hp/eb/software/binutils/2.34/bin/../lib/libopcodes-2.34.so (0x00007fbb984c1000)
        libctf.so.0 => /hp/eb/software/binutils/2.34/bin/../lib/libctf.so.0 (0x00007fbb98493000)
        libbfd-2.34.so => /hp/eb/software/binutils/2.34/bin/../lib/libbfd-2.34.so (0x00007fbb98350000)
        libdebuginfod.so.1 => /usr/lib/libdebuginfod.so.1 (0x00007fbb98349000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007fbb98344000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007fbb9817e000)
        libcurl.so.4 => /usr/lib/libcurl.so.4 (0x00007fbb980ee000)
        /lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fbb98684000)
        libnghttp2.so.14 => /usr/lib/libnghttp2.so.14 (0x00007fbb980c5000)
        libidn2.so.0 => /usr/lib/libidn2.so.0 (0x00007fbb980a4000)
        libssh2.so.1 => /usr/lib/libssh2.so.1 (0x00007fbb98064000)
        libpsl.so.5 => /usr/lib/libpsl.so.5 (0x00007fbb98051000)
        libssl.so.1.1 => /usr/lib/libssl.so.1.1 (0x00007fbb97fc0000)
        libcrypto.so.1.1 => /usr/lib/libcrypto.so.1.1 (0x00007fbb97ce7000)
        libgssapi_krb5.so.2 => /usr/lib/libgssapi_krb5.so.2 (0x00007fbb97c92000)
        libkrb5.so.3 => /usr/lib/libkrb5.so.3 (0x00007fbb97bad000)
        libk5crypto.so.3 => /usr/lib/libk5crypto.so.3 (0x00007fbb97b7c000)
        libcom_err.so.2 => /usr/lib/libcom_err.so.2 (0x00007fbb97b76000)
        libz.so.1 => /usr/lib/libz.so.1 (0x00007fbb97b5c000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fbb97b38000)
        libunistring.so.2 => /usr/lib/libunistring.so.2 (0x00007fbb979b6000)
        libkrb5support.so.0 => /usr/lib/libkrb5support.so.0 (0x00007fbb979a7000)
        libkeyutils.so.1 => /usr/lib/libkeyutils.so.1 (0x00007fbb979a0000)
        libresolv.so.2 => /usr/lib/libresolv.so.2 (0x00007fbb97987000)
```

**Comment by zao** [comment]
Seems like I need to cpnfigure binutils/2.34 with `--without-debuginfod` to avoid it finding a "helpful" library that pulls in `curl` and eventually `z` on my system.

Should that go into the easyblock (in this PR or another), or into the 2.34 and onward easyconfigs?

**Comment by Flamefire** [comment]
I'd go for EasyBlock with an option to include it. Do you know in which versions this was introduced?

**Comment by zao** [comment]
2.34 - https://www.phoronix.com/scan.php?page=news_item&px=GNU-Binutils-2.34-Branched

**Comment by Flamefire** [comment]
Ok, done: https://github.com/easybuilders/easybuild-easyblocks/pull/2044/commits/78ebdae0856351f570f42d11d58ba0da8f2f6dd3

Disabled by default.

**Comment by akesandgren** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
