### PR TITLE
fix ELPA preprocessor flag for QuantumESPRESSO >= 7

### PR DESCRIPTION
**Pull request by migueldiascosta**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _QuantumESPRESSO-7.0-foss-2021b.eb_ 
 * **SUCCESS** _QuantumESPRESSO-7.1-foss-2022a.eb_ 
 * **SUCCESS** _QuantumESPRESSO-7.2-foss-2022b.eb_ 
 * **FAIL (build issue)** _QuantumESPRESSO-7.2-foss-2023a.eb_ (partial log available at https://gist.github.com/migueldiascosta/a716f321e48806f8bda3ec9628d93e47)

Build succeeded for 3 out of 4 (4 easyconfigs in total)
sms - Linux CentOS Linux 7.6.1810, x86_64, AMD EPYC 7601 32-Core Processor, Python 3.6.8
See https://gist.github.com/migueldiascosta/453a22626150cae8b31861249b1fa148 for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _QuantumESPRESSO-7.2-foss-2023a.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
sms - Linux CentOS Linux 7.6.1810, x86_64, AMD EPYC 7601 32-Core Processor, Python 3.6.8
See https://gist.github.com/migueldiascosta/97c09d4e80d4a9fe58c52107c47abd11 for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
"Failed to process easyconfig /home/apps/develop/easybuild-easyconfigs/easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.6-foss-2019b.eb: Failed to process easyconfig /home/easybuild/easyconfigs/f/foss/foss-2019b.eb: Failed to process easyconfig /home/easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.4-GCC-8.3.0.eb: Failed to process easyconfig /home/easybuild/easyconfigs/h/hwloc/hwloc-1.11.12-GCCcore-8.3.0.eb: Failed to process easyconfig /home/easybuild/easyconfigs/l/libxml2/libxml2-2.9.9-GCCcore-8.3.0.eb: Failed to import EB_libxml2 easyblock: cannot import name 'subprocess_popen_text'"
Failed during parsing of the easyconfigs, so no ecs were built (8 easyconfigs in total)
sms - Linux CentOS Linux 7.6.1810, x86_64, AMD EPYC 7601 32-Core Processor, Python 3.6.8
See https://gist.github.com/migueldiascosta/5cb849216528258aba8b2ab32158d928 for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _QuantumESPRESSO-6.6-foss-2019b.eb_ 
 * **SUCCESS** _QuantumESPRESSO-6.6-foss-2020a.eb_ 
 * **SUCCESS** _QuantumESPRESSO-6.6-foss-2020b.eb_ 
 * **SUCCESS** _QuantumESPRESSO-6.7-foss-2019b.eb_ 
 * **SUCCESS** _QuantumESPRESSO-6.7-foss-2020b.eb_ 
 * **SUCCESS** _QuantumESPRESSO-6.7-foss-2021a.eb_ 
 * **SUCCESS** _QuantumESPRESSO-6.8-foss-2021a.eb_ 
 * **SUCCESS** _QuantumESPRESSO-6.8-foss-2021b.eb_ 

Build succeeded for 8 out of 8 (8 easyconfigs in total)
sms - Linux CentOS Linux 7.6.1810, x86_64, AMD EPYC 7601 32-Core Processor, Python 3.6.8
See https://gist.github.com/migueldiascosta/2b5696be3e04bc835d704338a533a246 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _QuantumESPRESSO-6.7-foss-2021a.eb_ 
 * **SUCCESS** _QuantumESPRESSO-6.7-intel-2021a.eb_ 
 * **SUCCESS** _QuantumESPRESSO-6.8-foss-2021a.eb_ 
 * **SUCCESS** _QuantumESPRESSO-6.8-foss-2021b.eb_ 
 * **SUCCESS** _QuantumESPRESSO-6.8-intel-2021a.eb_ 
 * **SUCCESS** _QuantumESPRESSO-7.0-foss-2021b.eb_ 
 * **SUCCESS** _QuantumESPRESSO-7.0-intel-2021b.eb_ 
 * **SUCCESS** _QuantumESPRESSO-7.1-foss-2022a.eb_ 
 * **SUCCESS** _QuantumESPRESSO-7.1-intel-2022a.eb_ 
 * **SUCCESS** _QuantumESPRESSO-7.2-foss-2022b.eb_ 
 * **SUCCESS** _QuantumESPRESSO-7.2-foss-2023a.eb_ 
 * **SUCCESS** _QuantumESPRESSO-7.2-intel-2022b.eb_ 

Build succeeded for 12 out of 12 (12 easyconfigs in total)
node3139.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/f01b1386f6af82458c3847f4eb5ad228 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Pull request merged**
