### PR TITLE
update Xmipp easyblock for new version (v3.20.07)

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
I tested this on an earlier easyconfig  Xmipp-3.19.04-Apollo-fosscuda-2019a-Python-2.7.15.eb, installation worked fine.

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _Xmipp-3.19.04-Apollo-fosscuda-2019a-Python-2.7.15.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3302.joltik.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/f1552945ead9a4664cae3685b0696482 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _Xmipp-3.19.04-Apollo-foss-2019a-Python-2.7.15.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2601.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/9df843c63b7943b14dc6508c3fb8fd42 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Pull request merged**
