### PR TITLE
Fix sanity-check and debug builds of TensorFlow

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by migueldiascosta** [comment]
lgtm - @Flamefire can you submit some test reports? Mine are failing, but I doubt that's related to this PR...

**Comment by Flamefire** [comment]
Started 2.5.0 with debug opt and 2.4.1 with module-only

**Comment by Flamefire** [comment]
Test report by @Flamefire
#### Overview of tested easyconfigs (in order)
 * **FAIL (build issue)** _TensorFlow-2.4.1-fosscuda-2019b-Python-3.7.4.eb_ (partial log available at https://gist.github.com/88c5d0641ccc3abd0d192de82070c50c)

Build succeeded for 0 out of 1 (1 easyconfigs in total)
taurusa4 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), Python 2.7.5
See https://gist.github.com/f0f6085573c82e6946786cf6025a6962 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _TensorFlow-2.5.0-fosscuda-2020b.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
taurusi8016 - Linux centos linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor (zen2), Python 2.7.5
See https://gist.github.com/8d110b2dbaa1cc248dcf4ce78fd11006 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _TensorFlow-2.4.1-fosscuda-2019b-Python-3.7.4.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
taurusa7 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), Python 2.7.5
See https://gist.github.com/a972e28db100c78098506a659644fe71 for a full test report.

**Comment by Flamefire** [comment]
@migueldiascosta Reran test which had a missed astor for some reason, hence the failure. --> GTG

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
