### PR TITLE
replace `run_cmd` with `run_shell_cmd` in custom easyblock for PSI/PSI4 (`psi.py`)

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

* used in `PSI4` easyconfigs
* `PSI` easyconfigs have been archived

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _CheMPS2-1.8.11-foss-2021b.eb_ 
 * **SUCCESS** _psutil-5.9.4-GCCcore-11.2.0.eb_ 
 * **SUCCESS** _pytest-7.1.3-GCCcore-11.2.0.eb_ 
 * **FAIL (build issue)** _PSI4-1.7-foss-2021b.eb_ (partial log available at https://gist.github.com/branfosj/8f5ba936df96b0101c04842128f3c3ec)

Build succeeded for 3 out of 4 (1 easyconfigs in total)
bear-pg0105u03b - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/b4a4801abcb9dcf86f839862d3d498c5 for a full test report.

**Comment by bartoldeman** [comment]
Seems to fail on an unrelated issue:
```
== 2024-02-10 10:50:34,327 build_log.py:171 ERROR EasyBuild encountered an error (at easybuild/src/easybuild-framework/easybuild/base/exceptions.py:126 in __init__): `/rds/projects/2017/branfosj-rse/easybuild/EL8-ice/software/Python/3.9.6-GCCcore-11.2.0/bin/python -m pip check` failed:
qcengine 0.26.0 requires pyyaml, which is not installed.
```

**Comment by branfosj** [comment]
Checking the current install on generoso gives the same:
```
$ pip check
qcengine 0.26.0 requires pyyaml, which is not installed.
```

So, this means that `pip check` was not enabled before and is now. This is showing up an issue with the original easyconfig. I'll sort out a fix for it.

**Comment by branfosj** [comment]
Updated easyconfig in https://github.com/easybuilders/easybuild-easyconfigs/pull/19836

**Review by bartoldeman — APPROVED** [review]
ok with the updated easyconfig now

**Pull request merged**
