### PR TITLE
add RISC-V support to Boost easyblock

### PR DESCRIPTION
**Pull request by SebastianAchilles**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by bedroge** [comment]
The same change is also included in https://github.com/easybuilders/easybuild-easyblocks/pull/3339, and I used it a few times already to install a couple of Boost versions. But I think it makes sense to have this in a separate PR, also because there are still some issue with Extrae. I'll upload some RISC-V test reports.

**Comment by SebastianAchilles** [comment]
> The same change is also included in #3339, and I used it a few times already to install a couple of Boost versions. But I think it makes sense to have this in a separate PR, also because there are still some issue with Extrae. I'll upload some RISC-V test reports.

Ah, I didn't noticed #3339 when I searched for an open PR earlier. I run into the problem of building Boost, when I tried to build SciPy.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _Boost-1.85.0-GCC-13.3.0.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
arriesgado-2 - Linux Ubuntu 22.04, RISC-V-64, UNKNOWN (u74mc), Python 3.10.12
See https://gist.github.com/SebastianAchilles/3fce59233c52c50bf6e5a5e63cf380bd for a full test report.

**Comment by bedroge** [comment]
Test report by @bedroge
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _Boost-1.85.0-GCC-13.3.0.eb_ 
 * **SUCCESS** _M4-1.4.19.eb_ 
 * **SUCCESS** _Bison-3.8.2.eb_ 
 * **SUCCESS** _flex-2.6.4.eb_ 
 * **SUCCESS** _zlib-1.2.13.eb_ 
 * **SUCCESS** _binutils-2.40.eb_ 
 * **SUCCESS** _GCCcore-13.2.0.eb_ 
 * **SUCCESS** _ICU-74.1-GCCcore-13.2.0.eb_ 
 * **SUCCESS** _gzip-1.13-GCCcore-13.2.0.eb_ 
 * **SUCCESS** _lz4-1.9.4-GCCcore-13.2.0.eb_ 
 * **SUCCESS** _zstd-1.5.5-GCCcore-13.2.0.eb_ 
 * **SUCCESS** _Boost-1.83.0-GCC-13.2.0.eb_ 

Build succeeded for 12 out of 12 (2 easyconfigs in total)
starfive - Linux Debian GNU/Linux n/a, RISC-V-64, UNKNOWN, Python 3.10.9
See https://gist.github.com/bedroge/aa8b6e3423c30f481b531cd48ea5445f for a full test report.

**Comment by bedroge** [comment]
Test report by @bedroge
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _Boost-1.85.0-GCC-13.3.0.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 22.04, x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.10.12
See https://gist.github.com/bedroge/3d44a15bd1147c30d647d445e6d7e8f2 for a full test report.

**Review by bedroge — APPROVED** [review]
Looks good to me!

**Pull request merged**
