### PR TITLE
fixed PGI easyblock sanity check for version 19

### PR DESCRIPTION
**Pull request by mboisson**
PGI 19 and more recent drops pgf77. This PR fixes the sanity checks.

### CODE REVIEW

**Comment by mboisson** [comment]
Ah, I see somebody else had removed pgf77 already. I suggest modifying it for pgf90 instead, since this is present in PGI 19.

**Comment by boegel** [comment]
@mboisson Indeed, see https://github.com/easybuilders/easybuild-easyblocks/pull/1653 .

I don't mind checking for `pgf90` instead, but you'll need to fix the conflict first here (or open a new PR starting from the `develop` branch)...

**Comment by boegel** [comment]
@mboisson `pgf90` has been there since PGI 15.1, which is the oldest version we have easyconfigs for, so no need to the version check imho...

**Comment by mboisson** [comment]
Alright, we can close this PR then, and just drop pgf77.

**Pull request closed without merging**
