### PR TITLE
update sanity check in OpenFOAM easyblock, since there's no `modifyMesh` in OpenFOAM 12

### PR DESCRIPTION
**Pull request by branfosj**

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _OpenFOAM-11-foss-2023a.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0210u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8480CL (sapphirerapids), Python 3.6.8
See https://gist.github.com/branfosj/b567c20fbe09f2889fe6917657b6d986 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _KaHIP-3.16-gompi-2023a.eb_ 
 * **SUCCESS** _OpenFOAM-v2312-foss-2023a.eb_ 

Build succeeded for 2 out of 2 (1 easyconfigs in total)
bear-pg0105u03a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/f5a765d8b255ed63a7c5cce4c0239dc4 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _OpenFOAM-11-foss-2023a.eb_ 
 * **SUCCESS** _OpenFOAM-v2306-foss-2022b.eb_ 

Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3116.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/d9e7d84023e42d65f234ebc24fcaf6ed for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Pull request merged**
