### PR TITLE
Install only SuiteSparse libraries with `make install`

### PR DESCRIPTION
**Pull request by appolloford**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
It looks like these changes are not backwards-compatible at all...

@appolloford Can you provide some more info on why these changes are required?

**Comment by appolloford** [comment]
This PR is trying to make the installation of SuiteSparse as close to normal `ConfigureMake` as possible and keep backwards-compatibility as much as possible. I have tested 3.6.0, 4.0.0, 4.5.0, 5.1.2, 5.7.1, 5.8.1, 5.13.0, and 7.1.0. Although the older versions (< v5.1.2) are not supported anymore (which needs metis-4.x), I still keep the related codes there for reference.

The current behaviour of this easyblock is (1) revise the `UConfig` or `SuiteSparse_Config` for the older versions (< 4.5.0) which does not support setting options from environment (this is almost the same as the original configuration step) (2) Set proper environment variables for newer versions (< 6.0.0) (3) Left easyconfig to handle the `CMAKE_OPTIONS` for the recent versions

A few major changes:
1. If `METIS` is not provided in the dependencies, it will compile its own metis lib. After v6.0.0, users are not allowed to use preinstalled `METIS` either. My understanding is that it does not install metis lib either but only use its object file when compiling some libs.
2. By using `make; make install`, only c libraries will be installed (ideally static libs for versions < 4.5.0 and shared libs for else). No object files or subfolders are copied to the installdir (e.g. KLU/Lib). 
3. Since its matlab tools need be compiled with `mex` and need all dependencies in relative path (e.g. KLU/Lib). The related files are not copied to the installdir anymore.
4. I think suitesparse does not need mpi and remove the code looking for `MPICC` in the original code. Suitesparse easyconfigs could move to `gfbf` instead of `foss` in the future.

Some concerns:
1. I tested `SuiteSparse-5.10.1-foss-2021a-METIS-5.1.0-CUDA-11.3.1.eb` and it passed, but there is no other versions I can test. 
2. Suitesparse starts to use CMake from v5 in GraphBLAS, but lacks of proper options to set `BLAS/LAPACK/INSTALL_PREFIX`. Since there is no such easyconfig file and they are old, I did not do more work to support them.

Details:
1. Before v4.5.0, suitesparse uses `INSTALL_LIB` and `INSTALL_INCLUDE` to control installdir and use `METIS_PATH` and `METIS` to know the path of metis lib
2. From v4.5.0 to v6.0.0, suitesparse use `INSTALL` to control installdir and GraphBLAS need its own `CMAKE_INSTALL_PREFIX`
3. From v4.5.0 to v6.0.0, metis path is set by `MY_METIS_LIB` and `MY_METIS_INC`

Please let me know if you find any mistakes. I may forget some details and write something wrong here.

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="SuiteSparse-5.7.1-foss-2020a-METIS-5.1.0.eb SuiteSparse-5.7.1-intel-2020a-METIS-5.1.0.eb SuiteSparse-5.8.1-foss-2020b-METIS-5.1.0.eb SuiteSparse-5.8.1-intel-2020b-METIS-5.1.0.eb SuiteSparse-5.10.1-foss-2021a-METIS-5.1.0.eb SuiteSparse-5.10.1-foss-2021b-METIS-5.1.0.eb SuiteSparse-5.10.1-intel-2021a-METIS-5.1.0.eb SuiteSparse-5.10.1-intel-2021b-METIS-5.1.0.eb SuiteSparse-5.13.0-foss-2022a-METIS-5.1.0.eb SuiteSparse-5.13.0-foss-2022b-METIS-5.1.0.eb --installpath /tmp/$USER/pr3004"

**Comment by appolloford** [comment]
These two tests failed for intel license.

> * **FAIL (build issue)** _SuiteSparse-5.7.1-intel-2020a-METIS-5.1.0.eb_ (partial log available at https://gist.github.com/boegelbot/6c49ebf1ee66b55f650f73f5d6a76f0d)
> * **FAIL (build issue)** _SuiteSparse-5.8.1-intel-2020b-METIS-5.1.0.eb_ (partial log available at https://gist.github.com/boegelbot/345768cdb9777e0362882613b72b558a)

```
Error: A license for Comp-CL is not available now (-15,570,115).
```

**Comment by akesandgren** [comment]
Test report by @akesandgren
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _SuiteSparse-5.7.1-intel-2020a-METIS-5.1.0.eb_ 
 * **SUCCESS** _SuiteSparse-5.8.1-intel-2020b-METIS-5.1.0.eb_ 

Build succeeded for 2 out of 2 (2 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/akesandgren/23e356e8f9553d3735859db5bb4e0321 for a full test report.

**Comment by akesandgren** [comment]
Also since SuiteSparse uses CMake from v6 we should take care of that in the easyblock.
It won't be the first time we do CMakeMake/ConfigureMake compatible easyblocks.

**Comment by appolloford** [comment]
Actually SuiteSparse does not follow the normal `cmake; make; make install` steps. It uses CMake in several subfolders (I am not sure whether all subfolders have been moved to cmake projects) but the top level is still managed by a makefile. The official guide says the whole suite should be built in this command:
```
CMAKE_OPTIONS="-DNPARTITION=1 -DNSTATIC=1 -DCMAKE_BUILD_TYPE=Debug" make
```
I think this does not match with the CMakeMake easyblock and I leave the `CMake_OPTION` to be controlled by each easyconfig file, like 

https://github.com/easybuilders/easybuild-easyconfigs/pull/18857

**Comment by akesandgren** [comment]
According to the python-linting test you should also remove these imports
shutil, stat, easybuild.tools.filetools.adjust_permissions, easybuild.tools.filetools.copy_dir

**Review by akesandgren — APPROVED** [review]
LGTM

**Comment by akesandgren** [comment]
Going in, thanks @appolloford!

**Pull request merged**
