### PR TITLE
enhance icc easyblock to inlude multipath include dir in $CPATH

### PR DESCRIPTION
**Pull request by boegel**
requires https://github.com/easybuilders/easybuild-framework/pull/2294

@akesandgren, @besserox, @vanzod, @geimer: feedback welcome, let me know if this works as expected...

### CODE REVIEW

**Comment by besserox** [comment]
@boegel The logic looks good.
A few comments/questions:
- Is the `GCCCore` dependency loaded when this is executed? (to make sure to use the right `gcc`)
- Maybe you can update the comment (to not only refer to `x86_64-linux-gnu`)

I have not tested it though.

**Comment by besserox** [comment]
@boegel What's the easiest way to install this branch to try it?

**Comment by akesandgren** [comment]
Yes, logic looks good. Will try to take it for a test spin if i get enough time tomorrow.

**Comment by boegel** [comment]
@besserox That really depends on your setup, you can just try and inject the code added to `module_generator.py` in https://github.com/easybuilders/easybuild-framework/pull/2294/files#diff-8cdd2ad54096882655bd836265e8e26b, and then download the updated `icc.py` and use `--include-easyblocks icc.py`...

**Comment by boegel** [comment]
After fixing the stupid mistake in the original PR, this seems to be working as intended; tested on in a Singularity container running Debian 9.1 using `icc-2017.2.174-GCC-6.3.0-2.27.eb`

**Comment by boegel** [comment]
This should be good to go now that https://github.com/easybuilders/easybuild-framework/pull/2294 is merged, pending confirmation from @akesandgren & @besserox...

**Comment by akesandgren** [comment]
Yeah, my from-pr of #4618 worked with the framework/easyblock changes from this morning.

**Comment by besserox** [comment]
@boegel I've got a busy week. I won't have time to try it soon.

**Comment by akesandgren** [comment]
And it worked with the new update_path based prepend/append_path framework too.

**Pull request merged**
