### PR TITLE
tweak Amber(Tools) easyblock to run tests from top-level directory

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
#### Overview of tested easyconfigs (in order)
 * **FAIL (build issue)** _AmberTools-21-foss-2021a.eb_ (partial log available at https://gist.github.com/3284da8add6500ea0321f9572efe12aa)

Build succeeded for 0 out of 1 (1 easyconfigs in total)
bear-pg0105u36b.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/61173c10f43b2f2ed566bbc0b085c300 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
#### Overview of tested easyconfigs (in order)
 * **FAIL (build issue)** _Amber-20.11-foss-2020b-AmberTools-21.3.eb_ (partial log available at https://gist.github.com/426f5534bf60a5381c71532bff68bfd2)

Build succeeded for 0 out of 1 (1 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/20154ba383b6053a5db10134504e1243 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
#### Overview of tested easyconfigs (in order)
 * **FAIL (build issue)** _Amber-20.11-foss-2020b-AmberTools-21.3.eb_ (partial log available at https://gist.github.com/fc77f23b802430cfa271af009fd80056)

Build succeeded for 0 out of 1 (1 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/9b75c31fbf3621ed635953be6aca6843 for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
#### Overview of tested easyconfigs (in order)
 * **FAIL (build issue)** _AmberTools-21.12-foss-2021b.eb_ (partial log available at https://gist.github.com/2e67fe7a8f6585e6fe915e6acca9baa7)

Build succeeded for 0 out of 1 (1 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/7ee313f09f066e7c09adf5ce71f9c27d for a full test report.

**Comment by akesandgren** [comment]
Don't merge yet. Looks like we need some patches in AT 21 and older to be able to do this.

**Comment by boegel** [comment]
@akesandgren Can you explain these changes a bit more? Why the change to `.serial`? Will this also work for older Amber(Tools) versions?

**Comment by akesandgren** [comment]
That code path is only used for AmberTools 20 (and thus Amber 20) and higher. Running the tests from the top dir is the correct way to run tests according to the developers.
Instead of just running "make test" which just runs "make test.$(INSTALLTYPE)" we now explicitly run the serial, parallel, cuda_serial and cuda_parallel test suites according to what we're acutally building.

Thus this change makes the tests not run any pmemd tests when just building AmberTools whivch was the problem before.

(There are still tests in the suites that fail, but I'm chasing the developers to get better (less exact) testing of those reesults)

One still have to check the test logs for details but at least we get a working test log.

**Comment by akesandgren** [comment]
Should be good to merge now in my opinion, updated PR's for relevant AmberTools versions submitted. Current Amber easyconfigs not affected since they aren't currently running the tests. (Except one that will need the top level Makefile patch to not include config.h)

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _AmberTools-21-foss-2021a.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3127.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/5e1a152585ed95dd817aec886b51940a for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Pull request merged**
