### PR TITLE
CP2K fix CPASSERT test faults on RHEL8

### PR DESCRIPTION
**Pull request by hajgato**

### CODE REVIEW

**Comment by migueldiascosta** [comment]
@hajgato lowering the optimisations silently for every future version of both ifort and cp2k will likely mean these will be in effect even if they are no longer necessary... probably not a big deal, but maybe at least print a message somewhere?

also, can you submit a test report with `--include-easyblocks-from-pr`? (and eb 4.3.1)

**Comment by hajgato** [comment]
@migueldiascosta We already lowering optimization silently for quite long time, but if it is needed, I will make them verbose.
As a matter of fact those optimization lowerings do not waste too much time. The first (ri_opt) consumes about a sub-second walltime, and once per calculation), the other one (cholesky) happen multiple times, but also quite quick. As a matter of fact, cholesky decomposition took in total 0.094 second out of 83.531 second of all tests jobs using cholesky decomposition (54 tests, and those numbers with the lowered optimization level)

**Comment by hajgato** [comment]
Test report by @hajgato
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _CP2K-7.1-intel-2020a.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3571.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor, Python 3.6.8
See https://gist.github.com/f069fc6c7467a1ffc8eeb74a62a748a2 for a full test report.

**Comment by hajgato** [comment]
```
--------------------------------- Summary --------------------------------
Number of FAILED  tests 0
Number of WRONG   tests 8
Number of CORRECT tests 3254
Number of NEW     tests 8
Total number of   tests 3270
--------------------------------------------------------------------------
Number of memory  leaks 0
--------------------------------------------------------------------------
```

**Comment by migueldiascosta** [comment]
regarding the optimizations, ok, not a big deal then

**Comment by hajgato** [comment]
Test report by @hajgato
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _CP2K-5.1-intel-2020a.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3571.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor, Python 3.6.8
See https://gist.github.com/a0d4e25452e00a7abd691c5c07aef6f6 for a full test report.

**Comment by hajgato** [comment]
```
--------------------------------- Summary --------------------------------
Number of FAILED  tests 5
Number of WRONG   tests 2
Number of CORRECT tests 2986
Number of NEW     tests 19
Total number of   tests 3012
--------------------------------------------------------------------------
Number of memory  leaks 0
--------------------------------------------------------------------------
```

**Comment by hajgato** [comment]
Test report by @hajgato
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _CP2K-6.1-intel-2020a.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3571.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor, Python 3.6.8
See https://gist.github.com/17cbfd0a938a39c8f0300c7053eec905 for a full test report.

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @hajgato!

**Comment by hajgato** [comment]
```
--------------------------------- Summary --------------------------------
Number of FAILED  tests 0
Number of WRONG   tests 1
Number of CORRECT tests 3047
Number of NEW     tests 19
Total number of   tests 3067
--------------------------------------------------------------------------
Number of memory  leaks 0
--------------------------------------------------------------------------
```

**Pull request merged**
