### PR TITLE
enhance MrBayes easyblock with custom sanity check command

### PR DESCRIPTION
**Pull request by jfgrimm**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by jfgrimm** [comment]
@ocaisa I can't reproduce that
If I run  `eb --include-easyblocks-from-pr=2727 MrBayes-3.2.7-gompi-2020b.eb --robot --rebuild` I see:
```
== sanity checking...
  >> file 'bin/mb' found: OK
  >> (non-empty) directory 'share' found: OK
  >> loading modules: bio/MrBayes/3.2.7-gompi-2020b...
  >> running command 'mb -help' ...
  >> result for command 'mb -help': OK
```

**Comment by ocaisa** [comment]
That's because the old ec has an explicit sanity check command included (note the missing one with `--about`)

**Comment by ocaisa** [comment]
@jfgrimm I tried this easyblock with `3.2.7` and it doesn't work. I wonder if there is much changing the easyblock now given that the latest versions of MrBayes are not supported anyway (and instead use a `ConfigureMake` easyblock)?

**Comment by jfgrimm** [comment]
I mean, there's a PR for 3.2.6 so I assume there's a requirement for that version. Since 3.2.7+ doesn't use the easyblock and instead uses `ConfigureMake`, I don't see why that matters here?

**Comment by ocaisa** [comment]
I looked at the discussion in https://github.com/easybuilders/easybuild-easyconfigs/pull/10831/files#r443527147 and I think we can merge that PR with a small change here:
```
    def __init__(self, *args, **kwargs):
        super(EB_MrBayes, self).__init__(*args, **kwargs)
        # For later MrBayes versions, no longer need to use this easyblock
        last_supported_version = '3.2.6'
        if LooseVersion(self.version) > LooseVersion(last_supported_version):
            raise EasyBuildError("Please use the ConfigureMake easyblock for %s versions > %s", self.name,
                                 last_supported_version)
```
(I tested this)

**Review by ocaisa — APPROVED** [review]

**Pull request merged**
