### PR TITLE
enhance Tarball easyblock to support using it for installing extensions

### PR DESCRIPTION
**Pull request by ItIsI-Orient**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by akesandgren** [comment]
Would be nice with an explanation of why your need this. I.e. what problem does it solve?

**Comment by ocaisa** [comment]
It sounds like a `bundle` with `components` would be useful for you. There's an example of what that looks like in https://github.com/easybuilders/easybuild-easyconfigs/pull/15018/files

**Comment by boegel** [comment]
Even though alternative approaches are possible here, I think this enhancement makes sense.

There have been other use cases where people have run into trouble when trying to use `Tarball` to install an extension, so even if we don't end up using this for `SCGid`, it still makes sense imho.

**Review by boegel — CHANGES_REQUESTED** [review]

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _Trimmomatic-0.39-Java-11.eb_ 
 * **SUCCESS** _snippy-4.6.0-GCC-10.2.0.eb_ 
 * **SUCCESS** _Spark-3.1.1-foss-2020b.eb_ 
 * **SUCCESS** _SpaceRanger-1.3.0-GCC-10.3.0.eb_ 
 * **SUCCESS** _Net-core-3.0.0.eb_ 
 * **SUCCESS** _Julia-1.7.2-linux-x86_64.eb_ 

Build succeeded for 6 out of 6 (6 easyconfigs in total)
node2607.swalot.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/6f38b66baaa444fb3667f4fd2f044375 for a full test report.

**Review by boegel — APPROVED** [review]

**Pull request merged**
