### PR TITLE
Changing numpy test command to fix the f2py errors

### PR DESCRIPTION
**Pull request by edmondac**
Ref https://github.com/easybuilders/easybuild-easyblocks/issues/605

This fixes the four fortran compile errors when we run the numpy test suite

### CODE REVIEW

**Comment by edmondac** [comment]
Thanks to @ocaisa for the help :-)

Now we just need the easyblock to notice if the tests fail/error

**Comment by edmondac** [comment]
https://github.com/easybuilders/easybuild-easyconfigs/pull/8458 is probably the better solution. If we merge that, then this PR isn't needed anymore...

**Comment by edmondac** [comment]
See also https://github.com/easybuilders/easybuild-easyblocks/pull/1744

**Comment by ocaisa** [comment]
In #1744 I've unset `LDFLAGS` during testing which also seems to work, this is similar to what has been elsewhere in the scipy/numpy easyblocks because of problems caused by having `LDFLAGS` set (and is easier than trying to figure out what should be included in the flag).

**Comment by edmondac** [comment]
Closing in favour of #1744

**Pull request closed without merging**
