### PR TITLE
switch to using CMake install procedure for Eigen 3.3.4 & newer

### PR DESCRIPTION
**Pull request by boegel**
If the CMake-based installation procedure is not using, the `eigen3.pc` file for `pkg-config` does not get generated & installed...

### CODE REVIEW

**Comment by damianam** [comment]
@boegel it lgtm, but I wonder where the version check comes from. I haven't seen anything in Eigen's changelog pointing to any change in cmake files or pkg-config in `3.3.4`.

**Comment by boegel** [comment]
@damianam I don't want to make this change for old `Eigen` versions/easyconfigs because i) the problem hasn't popped up for older versions (I suspect because not many software packages require `eigen3.pc`, and ii) mainly because the change requires using `CMake` as a build dependency for something that is installed with `dummy` toolchain (since nothing is actually being compiled).
That implies that `CMake` itself should also be built with `dummy`, which leaves us at the mercy of the OS compiler for building `CMake` 😱

**Comment by damianam** [comment]
I understand........ But I would add a comment making clear where the version restriction comes from. This is an EB issue, not an eigen requirement. Normally version checks are due to changes from one version onwards, which is not the case here. Looks to me like sort of "abusing" version checks for something they are not intended for (not exactly that, but you know what I mean)

**Comment by boegel** [comment]
@damianam I understand the potential confusion, clarifying comment added in 175326cc9

**Pull request merged**
