### PR TITLE
allow disabling of tests if using MPI in FFTW easyblock

### PR DESCRIPTION
**Pull request by willfurnass**
Addresses #1100

Q: what's the idiomatic way to add a check for the toolchain having an MPI?

### CODE REVIEW

**Comment by ocaisa** [comment]
One way would be
```
if self.toolchain.mpi_family():
```
`mpi_family()` either returns the MPI family (OpenMPI/MPICH) or None is it is not defined

**Comment by willfurnass** [comment]
Thanks @ocaisa!

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _FFTW-3.3.9-gompi-2021a.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2603.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 2.7.5
See https://gist.github.com/5bf56cb4507308586622ed8937ad06a7 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Pull request merged**
