### PR TITLE
update WPS easyblock for v3.6 & newer

### PR DESCRIPTION
**Pull request by akesandgren**
Fix openmp support and a regex problem.

### CODE REVIEW

**Comment by akesandgren** [comment]
@andreas-h Can you look at this old PR and see if it still applies after your recent updates. The target for this one is WPS v3

**Comment by akesandgren** [comment]
@andreas-h Ping??

**Comment by boegel** [comment]
@andreas-h Did you get a chance to test this?

@akesandgren Any easyconfig PRs that require this (so we have a test case)?

**Comment by akesandgren** [comment]
I double checked and this fix is still relevant.
@boegel ??

**Pull request merged**
