### PR TITLE
don't enable building of ld.gold when installing binutils on a RISC-V system + don't configure GCC to use gold as default linker on a RISC-V system

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
@SebastianAchilles I've opened this as a draft PR, because the logic in `gcc.py` w.r.t. `use_gold_linker` will need some love, I think. As it is now, it will still enable gold for GCC < 11.3 even on a RISC-V system, I think...

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _binutils-2.38.eb_ 
 * **FAIL (build issue)** _GCCcore-11.3.0.eb_ (partial log available at https://gist.github.com/85a533c2305b34c76c878d69447bb4cf)

Build succeeded for 1 out of 2 (2 easyconfigs in total)
eb-riscv - Linux Ubuntu 22.04, RISC-V-64, UNKNOWN (riscv64), Python 3.10.4
See https://gist.github.com/ca0c9b231b2f6f6aae42d78d96749d3b for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @SebastianAchilles
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _binutils-2.26.eb_ 
 * **SUCCESS** _binutils-2.28.eb_ 
 * **SUCCESS** _binutils-2.30.eb_ 
 * **SUCCESS** _binutils-2.30-GCCcore-7.3.0.eb_ 
 * **SUCCESS** _binutils-2.31.1.eb_ 
 * **SUCCESS** _binutils-2.32.eb_ 
 * **SUCCESS** _binutils-2.34.eb_ 
 * **SUCCESS** _binutils-2.35.eb_ 
 * **SUCCESS** _binutils-2.36.1.eb_ 
 * **SUCCESS** _binutils-2.36.1-GCCcore-8.4.0.eb_ 
 * **SUCCESS** _binutils-2.37.eb_ 
 * **SUCCESS** _binutils-2.38.eb_ 
 * **SUCCESS** _binutils-2.39.eb_ 
 * **SUCCESS** _GCCcore-8.1.0.eb_ 
 * **SUCCESS** _GCCcore-8.2.0.eb_ 
 * **SUCCESS** _GCCcore-8.3.0.eb_ 
 * **SUCCESS** _GCCcore-9.1.0.eb_ 
 * **SUCCESS** _GCCcore-9.2.0.eb_ 
 * **SUCCESS** _GCCcore-9.3.0.eb_ 
 * **SUCCESS** _GCCcore-9.4.0.eb_ 
 * **SUCCESS** _GCCcore-9.5.0.eb_ 
 * **SUCCESS** _GCCcore-10.1.0.eb_ 
 * **SUCCESS** _GCCcore-10.2.0.eb_ 
 * **SUCCESS** _GCCcore-10.3.0.eb_ 
 * **SUCCESS** _GCCcore-11.1.0.eb_ 
 * **SUCCESS** _GCCcore-11.2.0.eb_ 
 * **SUCCESS** _GCCcore-11.3.0.eb_ 
 * **SUCCESS** _GCCcore-12.1.0.eb_ 
 * **SUCCESS** _GCCcore-12.2.0.eb_ 
 * **SUCCESS** _binutils-2.30-GCCcore-8.1.0.eb_ 
 * **SUCCESS** _binutils-2.31.1-GCCcore-8.2.0.eb_ 
 * **SUCCESS** _binutils-2.32-GCCcore-8.3.0.eb_ 
 * **SUCCESS** _binutils-2.32-GCCcore-9.2.0.eb_ 
 * **SUCCESS** _binutils-2.34-GCCcore-10.1.0.eb_ 
 * **SUCCESS** _binutils-2.34-GCCcore-9.3.0.eb_ 
 * **SUCCESS** _binutils-2.35-GCCcore-10.2.0.eb_ 
 * **SUCCESS** _binutils-2.36.1-GCCcore-10.3.0.eb_ 
 * **SUCCESS** _binutils-2.36.1-GCCcore-11.1.0.eb_ 
 * **SUCCESS** _binutils-2.36.1-GCCcore-9.4.0.eb_ 
 * **SUCCESS** _binutils-2.37-GCCcore-11.2.0.eb_ 
 * **SUCCESS** _binutils-2.38-GCCcore-11.3.0.eb_ 
 * **SUCCESS** _binutils-2.38-GCCcore-12.1.0.eb_ 
 * **SUCCESS** _binutils-2.38-GCCcore-9.5.0.eb_ 
 * **SUCCESS** _binutils-2.39-GCCcore-12.2.0.eb_ 

Build succeeded for 44 out of 44 (44 easyconfigs in total)
cnx1 - Linux Rocky Linux 8.5, x86_64, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/6aa8f2332ee4882353ce675252718dee for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _binutils-2.28.eb_ 
 * **SUCCESS** _binutils-2.30.eb_ 
 * **SUCCESS** _binutils-2.31.1.eb_ 
 * **SUCCESS** _binutils-2.32.eb_ 
 * **SUCCESS** _binutils-2.34.eb_ 
 * **SUCCESS** _binutils-2.35.eb_ 
 * **SUCCESS** _binutils-2.36.1.eb_ 
 * **SUCCESS** _binutils-2.37.eb_ 
 * **SUCCESS** _binutils-2.38.eb_ 
 * **SUCCESS** _binutils-2.39.eb_ 
 * **SUCCESS** _GCCcore-7.3.0.eb_ 
 * **SUCCESS** _GCCcore-8.2.0.eb_ 
 * **SUCCESS** _GCCcore-8.3.0.eb_ 
 * **SUCCESS** _GCCcore-9.3.0.eb_ 
 * **SUCCESS** _GCCcore-9.4.0.eb_ 
 * **SUCCESS** _GCCcore-9.5.0.eb_ 
 * **SUCCESS** _GCCcore-10.1.0.eb_ 
 * **SUCCESS** _GCCcore-10.2.0.eb_ 
 * **SUCCESS** _GCCcore-10.3.0.eb_ 
 * **SUCCESS** _GCCcore-11.2.0.eb_ 
 * **SUCCESS** _GCCcore-11.3.0.eb_ 
 * **SUCCESS** _GCCcore-12.1.0.eb_ 
 * **SUCCESS** _GCCcore-12.2.0.eb_ 
 * **SUCCESS** _binutils-2.31.1-GCCcore-8.2.0.eb_ 
 * **SUCCESS** _binutils-2.32-GCCcore-8.3.0.eb_ 
 * **SUCCESS** _binutils-2.34-GCCcore-10.1.0.eb_ 
 * **SUCCESS** _binutils-2.34-GCCcore-9.3.0.eb_ 
 * **SUCCESS** _binutils-2.35-GCCcore-10.2.0.eb_ 
 * **SUCCESS** _binutils-2.36.1-GCCcore-10.3.0.eb_ 
 * **SUCCESS** _binutils-2.37-GCCcore-11.2.0.eb_ 
 * **SUCCESS** _binutils-2.38-GCCcore-11.3.0.eb_ 
 * **SUCCESS** _binutils-2.38-GCCcore-12.1.0.eb_ 
 * **SUCCESS** _binutils-2.38-GCCcore-9.5.0.eb_ 
 * **SUCCESS** _binutils-2.39-GCCcore-12.2.0.eb_ 

Build succeeded for 34 out of 34 (34 easyconfigs in total)
jsczen2c1.int.jsc-zen2.easybuild-test.cluster - Linux Rocky Linux 8.5, x86_64, AMD EPYC 7742 64-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/a331169c7cf5e79b015b4f797aec66e1 for a full test report.

**Comment by SebastianAchilles** [comment]
> Test report by @SebastianAchilles
> #### Overview of tested easyconfigs (in order)
> 
>     * **SUCCESS** _binutils-2.38.eb_
> 
>     * **FAIL (build issue)** _GCCcore-11.3.0.eb_ (partial log available at https://gist.github.com/85a533c2305b34c76c878d69447bb4cf)
> 
> 
> Build succeeded for 1 out of 2 (2 easyconfigs in total) eb-riscv - Linux Ubuntu 22.04, RISC-V-64, UNKNOWN (riscv64), Python 3.10.4 See https://gist.github.com/ca0c9b231b2f6f6aae42d78d96749d3b for a full test report.

Looks like I am hitting the bug described in https://gcc.gnu.org/bugzilla//show_bug.cgi?id=106271
I think this is more related to the RISC-V Ubuntu image itself rather than the EasyBlock.

**Comment by boegel** [comment]
@SebastianAchilles I agree, the problem you're hitting is clearly not due the changes being made here.

The updated logic makes sense to me, the test reports on non-RISC-V systems check out, so let's go ahead and merge this?

**Review by branfosj — APPROVED** [review]
lgtm

**Pull request merged**
