### PR TITLE
gamess_us.py: Minor update to handle option of building Michigan State University CCT3 & CCSD3A methods

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by migueldiascosta** [comment]
worth submitting an updated easyconfig?

**Comment by akesandgren** [comment]
I've have plans for generating the newest gamess_us, but getting our new storage system up and running takes precedent.
I'll get there eventually...
But I think this one is small enough not to need it.

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @akesandgren!

**Pull request merged**
