### PR TITLE
weed out duplicates when determining paths to include-fixed subdirectory

### PR DESCRIPTION
**Pull request by boegel**
Fix for problem reported via EasyBuild mailing list:

```
Exactly one 'include-fixed' directory expected, found 2:
['/opt/easybuild/software/GCCcore/10.2.0/lib/gcc/i686-pc-linux-gnu/10.2.0/include-fixed',
 '/opt/easybuild/software/GCCcore/10.2.0/lib64/gcc/i686-pc-linux-gnu/10.2.0/include-fixed']
 (at easybuild/software/EasyBuild/4.3.1/lib/python2.7/site-packages/easybuild/easyblocks/g/gcc.py:690 in post_install_step)
```

see https://lists.ugent.be/wws/arc/easybuild/2020-11/msg00007.html

### CODE REVIEW

**Comment by migueldiascosta** [comment]
lgtm - did you test it?

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _GCCcore-7.3.0.eb_ 
 * **SUCCESS** _GCCcore-9.3.0.eb_ 

Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3501.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/ac9c21220034af8d6410174bd5219495 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _GCCcore-9.3.0.eb_ 
 * **SUCCESS** _GCCcore-10.2.0.eb_ 

Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3159.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/eb39ad5ed2ae3bf3ea27bfe23273ed7a for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Review by zao — APPROVED** [review]
LGTM.

**Pull request merged**
