### PR TITLE
Add new easyblock for Theano

### PR DESCRIPTION
**Pull request by smoors**
include random string in compiledir_format and make sure theano uses BLAS libraries

### CODE REVIEW

**Comment by smoors** [comment]
adding BLAS libraries is recommended for performance: if you don't, Theano will show a warning like this:
fix warning: WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.

**Comment by boegel** [comment]
@smoors Companion PR to update `Theano` easyconfigs to leverage this is still missing?

Also, please customize `sanity_check_step` as well.

**Comment by smoors** [comment]
@boegel I was actually waiting until this easyblock is accepted :)
what do want to customize in `sanity_check_step` exactly? the updated compilation directory is created only when the user starts using the module.

**Comment by boegel** [comment]
@smoors the sanity check should be customized to check for files & directories that should be there when Theano is correctly installed (rather than relying in the generic `bin` and `lib` or `lib64` check), it's not related to the compilation directory at all (sorry for not being more specific there), basically what we already have in the easyconfigs (but then letting the easyblock handle it):

```python
sanity_check_paths = {
    'files': ['bin/theano-cache', 'bin/theano-nose'],
    'dirs': ['lib/python%(pyshortver)s/site-packages'],
}
```

Having a PR for updated Theano easyconfigs already is useful so we can easily test this easyblock (we can't merge it without testing it with all existing Theano easyconfigs).

**Comment by smoors** [comment]
@boegel see #6378

**Comment by damianam** [comment]
Given that Theano is practically abandonware, does it make sense to merge this now? It seems simple enough to implement that in the existing easyconfigs?

**Comment by smoors** [comment]
@damianam why do you say it is abandonware? they still have regular releases

**Comment by boegel** [comment]
@smoors https://groups.google.com/forum/#!topic/theano-users/7Poq8BZutbY

**Comment by smoors** [comment]
ok its clear that support will not continue much longer, will close this.

**Pull request closed without merging**
