### PR TITLE
enhance cargo easyblock for sources from git repositories

### PR DESCRIPTION
**Pull request by Flamefire**
This combines #3481 and #3482 to test that they work together for EasyConfigs that would fail without.

They can be merged individually which might be easier to review or just this one.

Closes #3481 
Closes #3482

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _uv-0.2.30-GCCcore-13.3.0.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
i7016 - Linux Rocky Linux 8.9 (Green Obsidian), x86_64, AMD EPYC 7702 64-Core Processor (zen2), Python 3.8.17
See https://gist.github.com/Flamefire/d91ecc4728b15a21cdad664178436018 for a full test report.

**Review by Micket — APPROVED** [review]
it seems you thought this through, so looks fine to me. I will run some tests.

**Comment by Micket** [comment]
Hm, i'm having trouble with the uv package you link
```
== 2024-11-07 15:59:09,477 easyblock.py:815 INFO Considering directory in which easyconfig file is located when searching for reqwest-middleware-0.3.2-21ceec9a5fd2e8d6f71c3ea2999078fecbd13cbe.tar.gz: /dev/shm/eb-04l76vze/files_pr21637/u/uv
== 2024-11-07 15:59:09,477 tools.py:282 INFO Found location to 'eb' script via $EB_SCRIPT_PATH: /apps/Common/software/EasyBuild/4.9.4/bin/eb
== 2024-11-07 15:59:09,477 tools.py:296 INFO Also considering installation prefix /apps/Common/software/EasyBuild/4.9.4 (determined via path to 'eb' script)...
== 2024-11-07 15:59:09,480 run.py:251 INFO Using /bin/bash as shell for running cmd: git clone --no-checkout https://github.com/astral-sh/reqwest-middleware.git
== 2024-11-07 15:59:09,480 run.py:260 INFO running cmd: git clone --no-checkout https://github.com/astral-sh/reqwest-middleware.git
== 2024-11-07 15:59:10,105 run.py:700 INFO cmd "git clone --no-checkout https://github.com/astral-sh/reqwest-middleware.git" exited with exit code 0 and output:
Cloning into 'reqwest-middleware'...

== 2024-11-07 15:59:10,105 run.py:251 INFO Using /bin/bash as shell for running cmd: git checkout 21ceec9a5fd2e8d6f71c3ea2999078fecbd13cbe
== 2024-11-07 15:59:10,105 run.py:260 INFO running cmd: git checkout 21ceec9a5fd2e8d6f71c3ea2999078fecbd13cbe
== 2024-11-07 15:59:10,134 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:126 in __init__): cmd "git checkout 21ceec9a5fd2e8d6f71c3ea2999078fecbd13cbe" exited with exit code 128 and output:
fatal: reference is not a tree: 21ceec9a5fd2e8d6f71c3ea2999078fecbd13cbe
```
Not sure what to make of that

**Comment by Micket** [comment]
Looks to me that maybe this is just the developers over at astral-sh/reqwest-middleware.git just forced pushed new stuff, abandoning the commit 21ceec9a5fd2e8d6f71c3ea2999078fecbd13cbe maybe?
Probing
https://github.com/astral-sh/reqwest-middleware/commit/21ceec9a5fd2e8d6f71c3ea2999078fecbd13cbe
i see the warning
> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

If so, then I don't want to let that block this PR, but I want to confirm with you @Flamefire

**Comment by Micket** [comment]
Test report by @Micket
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _tokenizers-0.15.2-GCCcore-12.3.0.eb_ 
 * **SUCCESS** _fastparquet-2023.4.0-gfbf-2022b.eb_ 
 * **SUCCESS** _Safetensors-0.4.3-gfbf-2023a.eb_ 
 * **SUCCESS** _rustworkx-0.15.1-gfbf-2023a.eb_ 
 * **SUCCESS** _maturin-1.4.0-GCCcore-12.2.0-Rust-1.75.0.eb_ 
 * **SUCCESS** _kyber-0.4.0-GCC-12.3.0.eb_ 
 * **SUCCESS** _cryptography-42.0.8-GCCcore-13.3.0.eb_ 

Build succeeded for 7 out of 7 (7 easyconfigs in total)
vera-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/ffa48aff3847feba053d5373367a2bc1 for a full test report.

**Comment by Micket** [comment]
I hadn't seen  https://github.com/easybuilders/easybuild-framework/pull/4680 

OK, so it's not this PR's fault. I'm merging it as is, as the two failures are unrelated.

**Pull request merged**
