### PR TITLE
added option use_pip_requirement to allow providing a requirements file to the pip command, as a source

### PR DESCRIPTION
**Pull request by mboisson**

### CODE REVIEW

**Comment by boegel** [comment]
@mboisson Do you have a specific example use case for this?

**Comment by mboisson** [comment]
In our case, installing our bundle modules which we install from wheels we compile independently. It is much easier to specify varying python dependencies with multi python using a requirements file than using the exts_list (plus the exts_list does not take from our wheel house).
  

  
  
  

  
  
>

**Comment by mboisson** [comment]
Consider what we had to do in the past : 
https://github.com/ComputeCanada/easybuild-easyconfigs/blob/computecanada-master/easybuild/easyconfigs/s/Scipy-Stack/SciPy-Stack-2019b-dummy.eb

to what it looks like now : 
https://github.com/ComputeCanada/easybuild-easyconfigs/blob/computecanada-master/easybuild/easyconfigs/s/Scipy-Stack/SciPy-Stack-2020a-GCCcore-9.3.0.eb
plus
https://github.com/ComputeCanada/easybuild-easyconfigs/blob/computecanada-master/easybuild/easyconfigs/s/Scipy-Stack/requirements-2020a.txt

**Comment by mboisson** [comment]
In general, the `exts_list` framework is not flexible enough to really support multi-python for python bundles, because the dependency graph can vary for different versions of python (in particular between python 2.7 and 3.x, but also sometimes within 3.x for different x).

**Comment by mboisson** [comment]
This is another example : 
https://github.com/ComputeCanada/easybuild-easyconfigs/blob/computecanada-master/easybuild/easyconfigs/i/ipykernel/ipykernel-2020a-GCCcore-9.3.0.eb
https://github.com/ComputeCanada/easybuild-easyconfigs/blob/computecanada-master/easybuild/easyconfigs/i/ipykernel/requirements-2020a.txt

**Comment by mboisson** [comment]
Any way to move this forward ?

**Comment by akesandgren** [comment]
Doesn't --requirement take an argument? If so, where does that come from ?

**Comment by mboisson** [comment]
Yes, the requirement file would be the source file in this case.

**Comment by akesandgren** [comment]
Ok, then this should perhaps be noted in the help text for use_pip_requirement. I.e. that it takes the req-file from the sources argument.

**Comment by mboisson** [comment]
> Ok, then this should perhaps be noted in the help text for use_pip_requirement. I.e. that it takes the req-file from the sources argument.

done

**Review by akesandgren — APPROVED** [review]
LGTM

**Comment by akesandgren** [comment]
Going in, thanks @mboisson!

**Pull request merged**
