### PR TITLE
Fix Boost sanity check on POWER

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _Boost-1.71.0-gompi-2019b.eb_ 
 * **SUCCESS** _Boost-1.71.0-gompic-2019b.eb_ 
 * **SUCCESS** _Boost-1.72.0-GCCcore-9.3.0-no_mpi.eb_ 
 * **SUCCESS** _Boost-1.72.0-gompi-2020a.eb_ 
 * **SUCCESS** _Boost-1.74.0-GCC-10.2.0.eb_ 
 * **SUCCESS** _numactl-2.0.12-GCCcore-8.2.0.eb_ 
 * **SUCCESS** _libxml2-2.9.8-GCCcore-8.2.0.eb_ 
 * **SUCCESS** _xorg-macros-1.19.2-GCCcore-8.2.0.eb_ 
 * **SUCCESS** _libpciaccess-0.14-GCCcore-8.2.0.eb_ 
 * **SUCCESS** _hwloc-1.11.11-GCCcore-8.2.0.eb_ 
 * **SUCCESS** _OpenMPI-3.1.3-GCC-8.2.0-2.31.1.eb_ 
 * **SUCCESS** _gompi-2019a.eb_ 
 * **SUCCESS** _Boost-1.70.0-gompi-2019a.eb_ 

Build succeeded for 13 out of 13 (6 easyconfigs in total)
bear-pg0306u11a.bear.cluster - Linux RHEL 8.2, POWER, 8335-GTX (power9le), Python 3.6.8
See https://gist.github.com/df234e9c4654e8b9ddb8fbb2e2a257c8 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _Boost-1.70.0-gompi-2019a.eb_ 
 * **SUCCESS** _Boost-1.70.0-iimpi-2019a.eb_ 
 * **SUCCESS** _Boost-1.71.0-gompi-2019b.eb_ 
 * **SUCCESS** _Boost-1.71.0-iimpi-2019b.eb_ 
 * **SUCCESS** _Boost-1.72.0-GCCcore-9.3.0-no_mpi.eb_ 
 * **SUCCESS** _Boost-1.72.0-gompi-2020a.eb_ 
 * **SUCCESS** _Boost-1.72.0-iimpi-2020a.eb_ 
 * **SUCCESS** _Boost-1.74.0-GCC-10.2.0.eb_ 
 * **SUCCESS** _Boost-1.74.0-iccifort-2020.4.304.eb_ 

Build succeeded for 9 out of 9 (9 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/9ca5407fcff476945749cab8afcb4129 for a full test report.

**Review by Flamefire — APPROVED** [review]

**Review by ocaisa — APPROVED** [review]
LGTM

**Comment by ocaisa** [comment]
Going in, thanks @branfosj

**Pull request merged**
