### PR TITLE
add EPYC to KOKKOS_CPU_ARCH_LIST and MAPPING in LAMMPS easyblock

### PR DESCRIPTION
**Pull request by migueldiascosta**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by migueldiascosta** [comment]
for the current version of LAMMPS in https://github.com/easybuilders/easybuild-easyconfigs/pull/9883 and https://github.com/easybuilders/easybuild-easyconfigs/pull/9884, this also requires an easyconfig patch with
```diff
* EPYC is supported in kokkos, but is missing from this arch list
--- lammps-stable_7Aug2019/lib/kokkos/cmake/kokkos_options.cmake.orig	2020-02-26 10:22:02.335120843 +0800
+++ lammps-stable_7Aug2019/lib/kokkos/cmake/kokkos_options.cmake	2020-02-26 10:22:53.470621040 +0800
@@ -78,6 +78,7 @@
 list(APPEND KOKKOS_ARCH_LIST
      None            # No architecture optimization
      AMDAVX          # (HOST) AMD chip
+     EPYC	      # (HOST) AMD EPYC Zen-Core CPU
      ARMv80          # (HOST) ARMv8.0 Compatible CPU
      ARMv81          # (HOST) ARMv8.1 Compatible CPU
      ARMv8-ThunderX  # (HOST) ARMv8 Cavium ThunderX CPU
```

**Comment by boegel** [comment]
@migueldiascosta Is it worth the trouble to open a pull request to https://github.com/lammps/lammps to add `EPYC` to `KOKKOS_ARCH_LIST`?

**Comment by migueldiascosta** [comment]
verified that the LAMMPS version in https://github.com/easybuilders/easybuild-easyconfigs/pull/10191 no longer requires the patch above in order to build on EPYC, only this PR

**Comment by akesandgren** [comment]
Going in, thanks @migueldiascosta!

**Pull request merged**
