### PR TITLE
don't run scipy test suite in parallel for scipy >= 1.11

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _SciPy-bundle-2023.07-gfbf-2023a.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
bwd-rockylinux-92 - Linux Rocky Linux 9.2 (Blue Onyx), x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), 2 x NVIDIA NVIDIA GeForce GTX 1060 6GB, 535.54.03, Python 3.9.16
See https://gist.github.com/SebastianAchilles/4d0cfb50c665039155245bd484cd2e96 for a full test report.

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _SciPy-bundle-2023.07-gfbf-2023a.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3115.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/cc46204f0df14a8d9b2bfa34af093d57 for a full test report.

**Comment by boegel** [comment]
FWIW: I've reported this upstream, see https://github.com/scipy/scipy/issues/19028

**Pull request merged**
