### PR TITLE
Remove redundant CPATH entry of tbb modules

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by migueldiascosta — DISMISSED** [review]
lgtm

**Comment by migueldiascosta** [comment]
hm, `--module-only` fails because `self.libpath` is `UNKNOWN` (only set in `install_step`)... 

@Flamefire, would you care to also fix that?

**Comment by Flamefire** [comment]
> @Flamefire, would you care to also fix that?

Done a first approach. Testing a few ECs now because something is really fishy here. IMO we should always have `lib/tbb*.so` and `include/tbb/*` and maybe some bin. The comments don't match what is done (which is why I dislike such comments) and there are major differences between the SYSTEM version and the source version. Trying to get them closer together.

Checked e.g. `endree` and that searches `/lib` not `/tbb/lib`, and we even set `TBB_ROOT=/tbb` if that exists else to `/` only (always with the install-prefix ofc)
So from how it looks to me the tbb subdir is bogus

**Comment by Flamefire** [comment]
Test report by @Flamefire
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _tbb-2018.4.222.eb_ 
 * **SUCCESS** _tbb-2019_U4-GCCcore-8.2.0.eb_ 
 * **SUCCESS** _tbb-2020.3-GCCcore-10.2.0.eb_ 

Build succeeded for 3 out of 3 (3 easyconfigs in total)
taurusa5 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), Python 2.7.5
See https://gist.github.com/d05030739a864e3dfc6eb6b8c282b91c for a full test report.

**Comment by Flamefire** [comment]
@migueldiascosta Ok done. Wasn't exactly easy to do it correctly but it should now be as it was supposed to be

**Comment by ocaisa** [comment]
Test report by @ocaisa
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _tbb-2019_U4-GCCcore-8.2.0.eb_ 
 * **SUCCESS** _tbb-2020.3-GCCcore-10.2.0.eb_ 

Build succeeded for 2 out of 2 (2 easyconfigs in total)
generoso - Linux centos linux 8.2.2004, x86_64, Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz, Python 3.6.8
See https://gist.github.com/c7637ff02a541481322e068d72a01bc4 for a full test report.

**Comment by ocaisa** [comment]
Test report by @ocaisa
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _tbb-2019_U4-GCCcore-8.2.0.eb_ 
 * **SUCCESS** _tbb-2020.3-GCCcore-10.2.0.eb_ 

Build succeeded for 2 out of 2 (2 easyconfigs in total)
generoso - Linux centos linux 8.2.2004, x86_64, Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz, Python 3.6.8
See https://gist.github.com/bcc5c9077c2f19b717b092d5adde6110 for a full test report.

**Review by ocaisa — APPROVED** [review]
LGTM

**Pull request merged**
