### PR TITLE
improve handling of `optarch` in `Cargo` easyblock

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by casparvl** [comment]
Trying to test [here](https://github.com/easybuilders/easybuild-easyconfigs/pull/18032#issuecomment-1577527592)

**Comment by Micket** [comment]
I see what where i messed up, one sec

**Comment by branfosj** [comment]
Test report by @branfosj
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _bamtofastq-1.4.0-GCCcore-10.3.0.eb_ 
 * **SUCCESS** _Evcxr-REPL-0.14.2-GCCcore-12.2.0-Rust-1.65.0.eb_ 
 * **SUCCESS** _Longshot-0.4.5-GCCcore-11.3.0.eb_ 
 * **SUCCESS** _ripunzip-0.4.0.eb_ 
 * **SUCCESS** _rustworkx-0.12.1-foss-2022a.eb_ 
 * **SUCCESS** _subset-bam-1.1.0-GCCcore-10.3.0.eb_ 

Build succeeded for 6 out of 6 (6 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/deb440eba33dd3f777617f274823596d for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _bamtofastq-1.4.0-GCCcore-10.3.0.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/d6c6f4373882a122fcbd444ec676c8b7 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _bamtofastq-1.4.0-GCCcore-10.3.0.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/52c6c2c0729ed71febe7fe3e5f10f9cd for a full test report.

**Review by branfosj — CHANGES_REQUESTED** [review]
I've suggested a small change and a small addition to the logging information. Other that that I am happy with this. We should add information about this to https://docs.easybuild.io/controlling-compiler-optimization-flags/.

**Review by branfosj — APPROVED** [review]

**Pull request merged**
