### PR TITLE
make IntelBase generic easyblock aware of (pre)installopts

### PR DESCRIPTION
**Pull request by ocaisa**
Addresses #1501

### CODE REVIEW

**Comment by ocaisa** [comment]
Verified with an extended dry run using https://github.com/easybuilders/easybuild-easyconfigs/pull/6841
```
  running command "INTEL_NO_CONNECTION_CHECK=1  ./install.sh  -s /home/alanc/.local/easybuild/build/icc/2018.3.222/dummy-dummy-GCC-7.3.0-2.30/icc-2018.3.222/silent.cfg"
```

**Comment by boegel** [comment]
@ocaisa Doesn't it make sense to also pick up `installopts` while we're at it?

**Comment by ocaisa** [comment]
Verified again with an extended dry run and  easybuilders/easybuild-easyconfigs#6841
```
running command "INTEL_NO_CONNECTION_CHECK=1 ./install.sh  -s /home/alanc/.local/easybuild/build/icc/2018.3.222/dummy-dummy-GCC-7.3.0-2.30/icc-2018.3.222/silent.cfg"
```

**Comment by boegel** [comment]
Thanks @ocaisa!

**Pull request merged**
