### PR TITLE
Using dict-type checksums for CUDA, with custom source filename

### PR DESCRIPTION
**Pull request by edmondac**
CUDA needs a different source file per architecture

### CODE REVIEW

**Comment by edmondac** [comment]
See also https://github.com/easybuilders/easybuild-framework/pull/2940 and https://github.com/easybuilders/easybuild-easyconfigs/pull/8136

**Comment by boegel** [comment]
@edmondac So we can't use `%(arch)s` after all?

**Comment by boegel** [comment]
@edmondac Due to the mixup in #1765, this appears merged, but the changes were actually reverted in #1765 too.

So, you'll need to open a new PR to follow-up on this...

**Comment by edmondac** [comment]
I've replaced this with #1766

**Pull request merged**
