### PR TITLE
update Kokkos CPU mapping for LAMMPS >= 2Aug2023 to use `icx` on Intel Icelake systems

### PR DESCRIPTION
**Pull request by steenlysgaard**
I noticed this when installing LAMMPS on our icelake servers and felt it was a typo.

### CODE REVIEW

**Comment by ocaisa** [comment]
Whether this is supported or not is dependent on the LAMMPS version. The correct place to make the update is within
 
https://github.com/easybuilders/easybuild-easyblocks/blob/develop/easybuild/easyblocks/l/lammps.py#L228

**Comment by boegel** [comment]
@steenlysgaard Are you planning to follow up on this?

**Comment by steenlysgaard** [comment]
@boegel I have done the change as @ocaisa suggested.

**Comment by steenlysgaard** [comment]
I found the relevant LAMMPS version by looking at this file https://github.com/lammps/lammps/blob/stable_2Aug2023/lib/kokkos/generate_makefile.bash#L182 for different LAMMPS releases

**Comment by boegel** [comment]
@casparvl Can you submit a test report for this using `LAMMPS-29Aug2024-foss-2023b-kokkos.eb` on your Icelake system?

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3
EB_ARGS="LAMMPS-29Aug2024-foss-2023b-kokkos.eb"

**Comment by laraPPr** [comment]
Succesfull build on IceLake See https://github.com/easybuilders/easybuild-easyconfigs/pull/21436#issuecomment-2420302152
And used the correct Kokkos package:
```
== Determined cpu arch: ICX
== Using Kokkos package with arch: CPU - ICX, GPU - None
```

**Review by laraPPr — APPROVED** [review]
lgtm

**Pull request merged**
