### PR TITLE
fix assumption in Bazel easyblock that include-fixed subdirectory is always there in GCC installation

### PR DESCRIPTION
**Pull request by boegel**
(partial fix for #2092)

### CODE REVIEW

**Comment by boegel** [comment]
confirmed fix for broken Bazel installation:

```
$ eb Bazel-2.0.0-GCCcore-8.3.0.eb
...
== FAILED: Installation ended unsuccessfully (build directory: /tmp/Bazel/2.0.0/GCCcore-8.3.0):
build failed (first 300 chars): Derived directory /software/GCCcore/8.3.0/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include-fixed does not exist (took 9 sec)
```

**Comment by lexming** [comment]
Positive test with `Bazel-2.0.0-GCCcore-8.3.0.eb`
https://gist.github.com/lexming/48dcbd9fbd4c724de87851693228ba42

**Comment by lexming** [comment]
Positive test with `Bazel-1.1.0-GCCcore-8.3.0.eb`
https://gist.github.com/lexming/ae1812bab3efb0b05bb53e680695e0be

**Comment by lexming** [comment]
Positive test with `Bazel-0.29.1-GCCcore-8.3.0.eb`
https://gist.github.com/lexming/08cd9f8e29f10bba33ef1ae4691f740c

**Comment by lexming** [comment]
Going in, thanks @boegel !

**Pull request merged**
