### PR TITLE
add custom easyblock for reticulate R package

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

see also https://github.com/easybuilders/easybuild-easyblocks/pull/2665#pullrequestreview-866974709

### CODE REVIEW

**Comment by smoors** [comment]
Test report by @smoors
#### Overview of tested easyconfigs (in order)

Build succeeded for 0 out of 0 (1 easyconfigs in total)
node310.hydra.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/52a23e029fbb3200b631177e84684d82 for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _R-4.1.0-foss-2021a.ebtest_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
node310.hydra.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/e40c0e69c45038cd69038b1c6dbb1704 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _R-4.1.2-foss-2021b.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3517.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/652139cd7a5751a295097b43a1dcde21 for a full test report.

**Comment by boegel** [comment]
Works like a charm (as long as `--parallel-extensions-install` isn't used, see https://github.com/easybuilders/easybuild-framework/issues/3959):

```
 $ ml show R/4.1.2-foss-2021b | grep RETI
setenv("RETICULATE_PYTHON","/software/Python/3.9.6-GCCcore-11.2.0/bin/python")
```

Thanks @smoors!

**Pull request merged**
