### PR TITLE
Simplify Boost easyblock

### PR DESCRIPTION
**Pull request by Flamefire**
Followup to #2456
This now saves some work by building Boost.MPI with the main build and
installing directly into the final folder without an intermediate copy step
Also a bit of cleanup, fixing comments, ...

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _Boost-1.72.0-GCCcore-9.3.0-no_mpi.eb_ 
 * **SUCCESS** _Boost-1.71.0-gompic-2019b.eb_ 
 * **SUCCESS** _Boost-1.70.0-gompic-2019a.eb_ 
 * **SUCCESS** _Boost-1.68.0-foss-2018b-Python-3.6.6.eb_ 
 * **SUCCESS** _Boost-1.54.0-foss-2016b-Python-2.7.12.eb_ 
 * **SUCCESS** _Boost.Python-1.64.0-gompi-2019a.eb_ 
 * **SUCCESS** _Boost.Python-1.67.0-foss-2018b-Python-3.6.6.eb_ 
 * **SUCCESS** _Boost.Python-1.74.0-GCC-10.2.0.eb_ 

Build succeeded for 8 out of 8 (8 easyconfigs in total)
taurusi6605.taurus.hrsk.tu-dresden.de - Linux RHEL 7.9, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/0339ff0adee6acf39822e985d96db197 for a full test report.

**Comment by Flamefire** [comment]
@branfosj @akesandgren Any comments?

**Review by akesandgren — APPROVED** [review]
LGTM

**Comment by akesandgren** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
