### PR TITLE
Add ambertools, derived from amber

### PR DESCRIPTION
**Pull request by verdurin**
Simple conversion of the existing `amber` for use with `ambertools`, which doesn't require a license.

In testing I found that the updating functionality was semi-broken in that it truncated the `patchlevels` value to a single digit, with the result that when set to 20, the current patch level, it instead only updated to patch 2. As a result, I've applied a workaround to use the original value from the easyconfig.

### CODE REVIEW

**Comment by boegel** [comment]
Hmm, with this approach there's quite a bit of copy-pasting between the easyblocks for `Amber` and `AmberTools`, is there not @verdurin?

Should we look into a more integrated solution, where both easyblocks leverage common functionality (which is hosted in either `amber*.py` Python module)?

**Comment by verdurin** [comment]
@boegel that would certainly be much more elegant, and preferred.

With a parameter to distinguish between the two, the need for the duplication would be obviated.

**Comment by boegel** [comment]
@verdurin My PR (https://github.com/akesandgren/easybuild-easyblocks/pull/7) to @akesandgren branch for https://github.com/easybuilders/easybuild-easyblocks/pull/1305 make `EB_Amber` compatible with `AmberTools`, so this can be closed probably?

Easyconfig PR for `AmberTools` is coming soon

**Comment by verdurin** [comment]
Okay, closing. Thanks @boegel

**Pull request closed without merging**
