### PR TITLE
Lammps

### PR DESCRIPTION
**Pull request by mboisson**
Compute Canada's LAMMPS EasyBlock

### CODE REVIEW

**Comment by boegel** [comment]
@mboisson This got integrated in #594, so this PR can be closed?

**Comment by mboisson** [comment]
It seems so, but #594 still is incompatible with multi-python support as we do in CC.

**Comment by damianam** [comment]
@mboisson maybe you can issue a PR against @boegel's branch? I think that's better than having 2 separate PR's tackling partly the same issues.

**Comment by mboisson** [comment]
The two PRs are incompatible I believe because of explicit checks for python in the other PR

**Comment by ocaisa** [comment]
@mboisson Are you very familiar with LAMMPS? I've gotten a working build using the new LAMMPS cmake procedure (see https://github.com/easybuilders/easybuild-easyconfigs/pull/6917) and I've been increasingly adding capabilities. I'm willing to work on a cmake-based easyblock but I need a collaborator that knows LAMMPS to know if the end result actually makes sense.

**Comment by mboisson** [comment]
No. Our resident expert on LAMMPS would be @aliker

**Comment by mboisson** [comment]
No. Our resident expert on LAMMPS would be @alikerr

**Comment by boegel** [comment]
@ocaisa I think @vanzod is quite familiar with LAMMPS (although maybe not the recent CMake-based build procedure).

**Comment by boegel** [comment]
closing this, superseded by https://github.com/easybuilders/easybuild-easyblocks/pull/1964

**Pull request closed without merging**
