### PR TITLE
look for Python version directories with suffixes in ROOT easyblock

### PR DESCRIPTION
**Pull request by kelseymh**
Implementation adapted from blender.py.  Addresses issue #2009 .

### CODE REVIEW

**Comment by lexming** [comment]
Going in, thanks @kelseymh !

**Comment by mboisson** [comment]
Instead of copying `find_glob_pattern`, this function should have been implemented in `filetools.py` and imported in both easyblocks.

**Comment by kelseymh** [comment]
@mboisson You are quite right, of course.  Since this PR is already merged, I will open a new one with that improvement.

**Comment by mboisson** [comment]
I created a PR for it here already 
https://github.com/easybuilders/easybuild-framework/pull/3297

**Comment by kelseymh** [comment]
I'll do that.  Something I don't know how to deal with, though, is handling the cross-repository dependence.  Should I just wait until your [PR #3297](https://github.com/easybuilders/easybuild-framework/pull/3297) gets merged, and then submit mine?  Or is there a way to specify the dependence as part of the PR process?  Sorry for my GitHub ignorance :-/

**Comment by mboisson** [comment]
I don't know that there is an official mechanism. I usually just comment and comment on the PR that this PR requires that PR.

**Comment by boegel** [comment]
> Instead of copying `find_glob_pattern`, this function should have been implemented in `filetools.py` and imported in both easyblocks.

You're very right, and I thought of that, but I had to admit I was being lazy at the time (we were close to the EasyBuild v4.2.0 release, and I wanted this fix included in it).
I figured that if it came up again, or if somebody cared enough, we could still support it in framework later.

Thanks for bringing this up, and helping out!

**Pull request merged**
