### PR TITLE
Evaluate numpy test results

### LINKED ISSUE #605: also run numpy.test rather than only a simply numpy.dot performance test in EB_numpy.test_step
Note: this will result in a failed test with numpy built with Intel compilers, which is actually a broken test, see https://github.com/numpy/numpy/issues/3844#issuecomment-97910358

problem reported by @olavks

### LINKED ISSUE #2237: Numpy (and likely scipy) test failures ignored
The numpy EasyBlock runs the unittests as `"cd .. && %(python)s -c 'import numpy; numpy.test(verbose=2)'"`

However the `numpy.test` function returns True/False depending on success. As that is never checked the exit code is always 0 (unless a segfault or similar occurred). See https://github.com/numpy/numpy/blob/360ba0572483457837992d711a0a00580741fc88/numpy/_pytesttester.py#L213

This means we basically run the tests but ignore any failures other than hard crashes. And with 2019b numpy I see errors in the test suite (caused by having LDFLAGS set)
I don't think this is intentional and hence should be changed.

I assume scipy has the same problem as it is similar.

### PR DESCRIPTION
**Pull request by Flamefire**
This checks for any errors during the numpy test suite.
Supersedes #1744

Fixes #2237
Fixes #605

### CODE REVIEW

**Comment by ocaisa** [comment]
@Flamefire Can you update the scipy easyblock as well for this change?

**Comment by Flamefire** [comment]
Done. And with SciPy-bundle-2019.03-foss-2019a.eb I get a failure due to a precision issue -.- Same with

Those are very small failures, e.g. `-0.00077271310043404 !=          -0.000772713100434114  (rdiff          9.569216326469691e-14)` or `"Arrays are not almost equal to 5 decimals" ... Max absolute difference: 1.5497208e-05`

Numpy seems to be fine. Not sure what to do. I'd suggest I'll remove the scipy change so we have at least numpy tested

**Comment by ocaisa** [comment]
Let's put it in a separate PR so we can still try to address it

**Comment by ocaisa** [comment]
Was that test on POWER? Looks like this is not uncommon:
https://github.com/scipy/scipy/pull/11181

**Comment by Flamefire** [comment]
No, this was on Intel and AMD x86 CPUs. Split out the SciPy stuff into #2241

**Comment by Flamefire** [comment]
Test report by @Flamefire
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _SciPy-bundle-2019.03-foss-2019a.eb_ 
 * **SUCCESS** _SciPy-bundle-2019.10-foss-2019b-Python-2.7.16.eb_ 
 * **SUCCESS** _SciPy-bundle-2019.10-foss-2019b-Python-3.7.4.eb_ 
 * **SUCCESS** _Python-3.6.6-foss-2018b.eb_ 
 * **SUCCESS** _Python-3.6.4-foss-2018a.eb_ 

Build succeeded for 5 out of 5 (5 easyconfigs in total)
taurusi6257.taurus.hrsk.tu-dresden.de - Linux RHEL 7.8, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/0a047b845b27d654b8e0bbe381e00874 for a full test report.

**Comment by migueldiascosta** [comment]
lgtm

I' wondering if there should be a log message about inverting the return value, so if a future version of numpy changes the behaviour (again) and the test_steps fails although all tests pass, at least it would be immediately clear why (?)

**Comment by Flamefire** [comment]
I expect the shown error message to be clear enough for that case. I would not clutter the log in anticipation of stuff that may or may not change and may or may not be obvious what changed. I mean: The test command is pretty clear: Run a test function and exit with the inverse of the result. As long as you remember that exit takes an error value and not a success value of course.

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
