### PR TITLE
change extra `$PATH` entry for OCaml to use `opam/default` rather than `opam/system`

### PR DESCRIPTION
**Pull request by branfosj**
For `OCaml/5.1.1-GCC-13.2.0` on generoso and for `OCaml/4.14.0-GCC-11.3.0` on my system there is no `opam/system` but there is `opam/default` and this contains `ocamlfind`

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _OCaml-4.14.0-GCC-11.3.0.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0105u03a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/9feae9561a08c50ad07a052e3d42079b for a full test report.

**Review by bartoldeman — DISMISSED** [review]
LGTM

**Review by boegel — CHANGES_REQUESTED** [review]
@branfosj Let's add "`ocamlfind list`" as sanity check command to catch this bug?

Maybe that should only be done conditionally though, when `ocamlfind` is being installed as extension?

**Comment by branfosj** [comment]
> @branfosj Let's add "`ocamlfind list`" as sanity check command to catch this bug?
> 
> Maybe that should only be done conditionally though, when `ocamlfind` is being installed as extension?

Done in bc7fa88.

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3
EB_ARGS="OCaml-4.14.0-GCC-11.3.0.eb   OCaml-5.1.1-GCC-13.2.0.eb"

**Review by boegel — APPROVED** [review]
lgtm

**Pull request merged**
