### PR TITLE
replace `run_cmd` with `run_shell_cmd` in custom easyblock for tensorflow_compression (`tensorflow_compression.py`)

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

* no use of `EB_tensorflow_minus_compression` in easyconfigs or blocks

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _tensorflow-compression-2.11.0-foss-2022a-CUDA-11.7.0.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0208u15a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), 1 x NVIDIA NVIDIA A100-SXM4-40GB, 520.61.05, Python 3.6.8
See https://gist.github.com/branfosj/da6c13fd86c979c785be3a8bc234be63 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **FAIL (build issue)** _tensorflow-compression-2.11.0-foss-2022a-CUDA-11.7.0.eb_ (partial log available at https://gist.github.com/boegel/9a2f71badf2d97e7a1ad91169c7c2117)

Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3301.joltik.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz, 1 x NVIDIA Tesla V100-SXM2-32GB, 535.154.05, Python 3.6.8
See https://gist.github.com/boegel/e361f65a8e2e305c5fcb4aee1ab4ea33 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _tensorflow-compression-2.11.0-foss-2022a-CUDA-11.7.0.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3301.joltik.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz, 1 x NVIDIA Tesla V100-SXM2-32GB, 535.154.05, Python 3.6.8
See https://gist.github.com/boegel/8ecc1b87cc2227f6a9b17f154d861250 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Pull request merged**
