### PR TITLE
Honor pretestopts & testopts in PerlModule

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by ocaisa — APPROVED** [review]

**Comment by ocaisa** [comment]
I'm a bit confused as we actually have an easyconfig that uses `pretestopts` with `PerlModule` and it works just fine there: https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/s/swissknife/swissknife-1.80-GCCcore-8.3.0.eb

**Comment by Flamefire** [comment]
It is only honored if a `Makefile.PL` exists in which case `ConfigureMake.test_step(self)` is called which honors pretestopts

If that file does not exist but a `Build.PL` exists then another command is used. For the test this would be `perl Build test`

**Review by ocaisa — DISMISSED** [review]
I see it now, there are two possible code paths in the easyblock, one respected `pretestopts` and the other didn't

**Comment by Flamefire** [comment]
> I see it now, there are two possible code paths in the easyblock, one respected `pretestopts` and the other didn't

Correct. Actually we should also honor "testopts" which are ignored in that code path too. Updated

**Review by ocaisa — APPROVED** [review]

**Comment by Flamefire** [comment]
> I don't have an easyconfig to test this against, but it doesn't break what we have and looks fine. Can you confirm @Flamefire that you've used it successfully?

I actually made this for #19971 as I needed  `pretestopts` and wasn't sure which of the code paths was taken. There it was not required. 

I tested this with a modified EC:
```
--- /tmp/orig/Perl-bundle-CPAN-5.36.1-GCCcore-12.3.0.eb	2024-02-27 09:11:17.712794906 +0100
+++ /tmp/Perl-bundle-CPAN-5.36.1-GCCcore-12.3.0.eb	2024-02-27 09:11:17.712794906 +0100
@@ -64,6 +64,8 @@
     ('Module::Build::Tiny', '0.045', {
         'source_tmpl': 'Module-Build-Tiny-%(version)s.tar.gz',
         'source_urls': ['https://cpan.metacpan.org/authors/id/L/LE/LEONT'],
+        'pretestopts': 'LC_ALL=C.UTF-8',
+        'testopts': '&& false',
         'checksums': ['d20692eee246d0b329b7f7659f36286b14ae0696fe91078a64b7078f8876d300'],
     }),
     ('aliased', '0.34', {
```

And it failed as expected: `build failed (first 300 chars): cmd "LC_ALL=C.UTF-8 perl Build test && false" exited with exit code 1 and output:`

Hence I'd say this PR works as it should.

**Pull request merged**
