### PR TITLE
replace `run_cmd` with `run_shell_cmd` in custom easyblock for Hadoop (`hadoop.py`)

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

* no use of `EB_Hadoop` in easyconfigs or blocks

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _protobuf-2.5.0-GCCcore-10.2.0.eb_ 
 * **SUCCESS** _libtirpc-1.3.1-GCCcore-10.2.0.eb_ 
 * **SUCCESS** _Hadoop-2.10.0-GCCcore-10.2.0-native-Java-1.8.eb_ 

Build succeeded for 3 out of 3 (1 easyconfigs in total)
bear-pg0105u03a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/83d5125f9d4becd59af27923ef46e417 for a full test report.

**Review by jfgrimm — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _Hadoop-2.10.0-GCCcore-10.2.0-native-Java-1.8.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3557.doduo.os - Linux RHEL 8.8, x86_64, AMD EPYC 7552 48-Core Processor, Python 3.6.8
See https://gist.github.com/boegel/54ce81baf4a74eb473f8d6705f781cfd for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Pull request merged**
