### PR TITLE
added multi_deps support into qscintilla easyblock

### PR DESCRIPTION
**Pull request by mboisson**
installing qscintilla with multiple python support fails currently. This PR fixes that.

### CODE REVIEW

**Comment by mboisson** [comment]
This PR included changes that were submitted in PR https://github.com/easybuilders/easybuild-easyblocks/pull/2040

it therefore supersedes #2040.

**Comment by boegel** [comment]
close/re-open to wake up Travis

**Comment by lexming** [comment]
Positive test with a modified `QScintilla-2.11.2-GCCcore-9.3.0.eb` from ComputeCanada using `multi_deps`

Easyconfigs:
* `Qt5-5.12.8-GCCcore-9.3.0.eb`: https://gist.github.com/lexming/815dfa33eecb62f4bab5781fe29d31ac
* `QScintilla-2.11.2-GCCcore-9.3.0.eb`: https://gist.github.com/lexming/d4387b0667dd7fef2aee352a82fc0af4

Logs:
* `Qt5-5.12.8-GCCcore-9.3.0.eb`:
    * 1/4) https://gist.github.com/lexming/cae66e3a33a5249e62c3f0e10aa1865e
    * 2/4) https://gist.github.com/lexming/fdb91e589f3cddbcd70e132a935ecbd6
    * 3/4) https://gist.github.com/lexming/c843c3431f3fc061e7795c846e475546
    * 4/4) https://gist.github.com/lexming/93bf5f6222e3fafdea24b3b895d3e56a
* `QScintilla-2.11.2-GCCcore-9.3.0.eb`: https://gist.github.com/lexming/d37612207153719f9f0bee569509bdd1

**Comment by lexming** [comment]
Positive test with regular `QScintilla-2.11.2-GCCcore-8.2.0-Python-3.7.2.eb` from EB
https://gist.github.com/lexming/7306095b3a1d3f019d5d41315fc6618a

**Comment by lexming** [comment]
Positive test with regular `QScintilla-2.9.4-foss-2016b-Python-2.7.12.eb` from EB
https://gist.github.com/lexming/c2fdd2d80bc6453d72324783ab4bb188

**Comment by lexming** [comment]
Going in, thanks @mboisson !

**Pull request merged**
