### PR TITLE
fix malformed `$CPATH` for intel-compilers on Debian/Ubuntu

### LINKED ISSUE #3345: intel-compiler fails sanity check on Debian/Ubuntu
With the recent changes to gcc easyblock #3254 and the older change to intel_compiler easyblock #1237 and its followups, intel-compiler now fails sanity check due to an incorrect module file being generated.

```
multiarch_inc_dir, ec = run_cmd("gcc -E -Wp,-v -xc /dev/null 2>&1 | grep %s$" % multiarch_out)
```
returns
```
easybuild@b-cn1615:~$ gcc -E -Wp,-v -xc /dev/null 2>&1 | grep  x86_64-linux-gnu'$'
 /cvmfs/ebsw.hpc2n.umu.se/amd64_ubuntu2204_icelake/software/GCCcore/13.2.0/bin/../lib/gcc/x86_64-pc-linux-gnu/13.2.0/include-fixed/x86_64-linux-gnu
 /usr/include/x86_64-linux-gnu
```

resulting in an malformed CPATH being added to the module file:
```
append_path("CPATH", "/cvmfs/ebsw.hpc2n.umu.se/amd64_ubuntu2204_icelake/software/GCCcore/13.2.0/bin/../lib/gcc/x86_64-pc-linux-gnu/13.2.0/include-fixed/x86_64-linux-gnu
 /usr/include/x86_64-linux-gnu")
```

Simple fix is to do ```grep -v GCCcore``` at the and of the command.

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

fixes #3345

### CODE REVIEW

**Comment by akesandgren** [comment]
@boegel Please suggest better solution :-)

**Comment by akesandgren** [comment]
Changed to use grep -v /include-fixed/ instead of GCCcore.

**Comment by boegel** [comment]
Test report by @boegel
"Can't find path /kyukon/home/gent/400/vsc40023/intel-compilers/2022.2.1.eb"
Failed during parsing of the easyconfigs, so no ecs were built (2 easyconfigs in total)
node3120.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/f37305bef1c8736144173cf18cce69f0 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _intel-compilers-2023.2.1.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
node4014.donphan.os - Linux Ubuntu 22.04.4 LTS (Jammy Jellyfish), x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 3.10.12
See https://gist.github.com/boegel/82de55e83ebc7a686287c421e9eabb91 for a full test report.

**Comment by boegel** [comment]
Problem reproduced in Ubuntu 22.04 container, manifests as:

```
== FAILED: Installation ended unsuccessfully (build directory: /tmp/vsc40023/easybuild_build/intelcompilers/2023.2.1/system-system): build failed (first 300 chars): Sanity check failed: loading fake module failed: 'Module command \'/usr/lmod/lmod/libexec/lmod python load intel-compilers/2023.2.1\' failed with exit code 1; stderr: Lmod has detected the following error: Unable to load module because of error when evaluating modulefile:\n     /tmp/eb-xsiw4xjr/tmpc (took 3 mins 17 secs)
```

Test report above confirms the fix

**Review by boegel — APPROVED** [review]

**Pull request merged**
