### PR TITLE
enhance psmpi easyblock to activate CUDA support when it is a dependency + make check for static libs in MPICH easyblock optional

### PR DESCRIPTION
**Pull request by damianam**
and to make the check for static libs in mpich optional, as they aren't always there

### CODE REVIEW

**Review by ocaisa — APPROVED** [review]
LGTM Any chance we can get a test report?

**Comment by damianam** [comment]
This kind of stalled, but in principle there is no reason to don't merge I guess. Ping @SebastianAchilles @ocaisa @boegel

**Review by SebastianAchilles — APPROVED** [review]
Thank you for your contribution, and I'm sorry that this PR got stalled.

I’ve reviewed the changes:

- The modifications appear reasonable.
- We received a successful test report.
- The modified EasyBlocks have been used at JSC for some time.

LGTM!

**Comment by SebastianAchilles** [comment]
Going in, thanks @damianam!

**Pull request merged**
