### PR TITLE
do not use -g77 option when installing NVHPC 22.9+

### PR DESCRIPTION
**Pull request by SebastianAchilles**
(created using `eb --new-pr`)

While installing `NVHPC/22.9` I got this error:
```
== FAILED: Installation ended unsuccessfully (build directory: /dev/shm/swmanage/jurecadc/NVHPC/22.9/system-system): build failed (first 300 chars): cmd "/p/software/jurecadc/stages/2023/software/NVHPC/22.9/Linux_x86_64/22.9/compilers/bin/makelocalrc -x /p/software/jurecadc/stages/2023/software/NVHPC/22.9/Linux_x86_64/22.9/compilers -g77 /" exited with exit code 1 and output:
ERROR: gfortran not found
```
Currently `-g77` is set to `/`. It looks like this was copied from the PGI easyblock which the NVHPC easyblock was based on: https://github.com/easybuilders/easybuild-easyblocks/blob/develop/easybuild/easyblocks/p/pgi.py#L147 But I think it should be set to a command name:
```
$ $EBROOTNVHPC/Linux_x86_64/22.9/compilers/bin/makelocalrc -h | grep g77
-g77 g77     g77 command name; default is g77
```

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
> to be specific, g77 and gfortran have different ways of returning some function values and they are not compatible. But on the other hand, noone should be using g77 today :-)

Would you suggest to remove `-g77 /` instead of changing it to `-g77 gfortran`?

**Comment by akesandgren** [comment]
That would be more correct yes.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _NVHPC-21.7.eb_ 
 * **SUCCESS** _NVHPC-21.9.eb_ 
 * **SUCCESS** _NVHPC-22.7-CUDA-11.7.0.eb_ 

Build succeeded for 3 out of 3 (3 easyconfigs in total)
jsczen2g1.int.jsc-zen2.easybuild-test.cluster - Linux Rocky Linux 8.5, x86_64, AMD EPYC 7742 64-Core Processor (zen2), 1 x NVIDIA GRID V100-4C, 460.73.01, Python 3.6.8
See https://gist.github.com/b549b31d981705c2308e2c1bd532f3fe for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _NVHPC-22.9.eb_ 
 * **SUCCESS** _NVHPC-22.11.eb_ 

Build succeeded for 2 out of 2 (2 easyconfigs in total)
bwd-rockylinux-91 - Linux Rocky Linux 9.1 (Blue Onyx), x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), 2 x NVIDIA NVIDIA GeForce GTX 1060 6GB, 515.86.01, Python 3.9.14
See https://gist.github.com/1728fd797bd0d1242991fff8c945abac for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @SebastianAchilles
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _NVHPC-20.7.eb_ 
 * **SUCCESS** _NVHPC-20.9.eb_ 
 * **SUCCESS** _NVHPC-20.11.eb_ 
 * **SUCCESS** _NVHPC-21.2.eb_ 
 * **SUCCESS** _NVHPC-21.3.eb_ 
 * **SUCCESS** _NVHPC-21.5.eb_ 
 * **SUCCESS** _NVHPC-21.9.eb_ 
 * **SUCCESS** _NVHPC-21.11.eb_ 
 * **SUCCESS** _NVHPC-22.1-CUDA-11.4.1.eb_ 
 * **SUCCESS** _NVHPC-22.7-CUDA-11.7.0.eb_ 

Build succeeded for 10 out of 10 (10 easyconfigs in total)
cnx1 - Linux Rocky Linux 8.5, x86_64, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/418f02609e87c0e25340f33d1fccac0d for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Pull request merged**
