### PR TITLE
Added an Autoconf easyblock for ppc64le support

### PR DESCRIPTION
**Pull request by edmondac**

### CODE REVIEW

**Comment by boegel** [comment]
@edmondac This should no longer be needed anymore since the recent changes to the `ConfigureMake` easyblock (see #1506, included in EasyBuild v3.7.0), where the output of a recent `config.guess` script is used to automatically set the `--build` option for `./configure`?

cc @ocaisa

**Comment by edmondac** [comment]
Doh. That's the mistake I always make. We're not up to date with the develop branch yet. We're planning to go to EasyBuild 3.7.0 in the next couple of weeks... Sorry!

**Comment by boegel** [comment]
@edmondac No problem, just wanted to make sure you were aware of those recent changes. There are a couple of related bug fixes coming up in EasyBuild v3.7.1 (to be released this week or early next week), so delaying updates for a while isn't necessarily a bad thing... ;-)

Do test first with EasyBuild v3.7.0 on POWER, and let us know if it works as expected for `Autoconf`.

**Comment by edmondac** [comment]
@boegel - ok we'll test 3.7.0 on POWER soon

**Comment by damianam** [comment]
@edmondac Since this is (or should be) fixed in 3.7.0, I'll close this PR to try to make things tidier here. Feel free to reopen the PR if things don't work as expected.

**Comment by edmondac** [comment]
Yes - it works fine on POWER9 with 3.7.0. There are other problems, but I'll come to them later!

**Pull request closed without merging**
