### PR TITLE
fix creation of symlink for libraries in TBB easyblock

### PR DESCRIPTION
**Pull request by Flamefire**
PR #2539 introduced a suspicious `os.path.join(libpath)` which was likely intended to be `os.path.join(self.installdir, libpath)` but works due to a possible(!) `chdir` when TBB is installed via the system toolchain.
Fix this by making `libpath` always absolute and simplify the code a bit.

@mboisson Please take a look at this instead of https://github.com/ComputeCanada/easybuild-easyblocks/commit/f34b32b91c6ffb5e4edc92eab0c2b824d11600b3

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _tbb-2018_U5-GCCcore-7.3.0.eb_ 
 * **SUCCESS** _tbb-2019_U4-GCCcore-8.2.0.eb_ 
 * **SUCCESS** _tbb-2020.3-GCCcore-10.2.0.eb_ 
 * **SUCCESS** _tbb-2021.5.0-GCCcore-11.3.0.eb_ 

Build succeeded for 4 out of 4 (4 easyconfigs in total)
taurusi6605.taurus.hrsk.tu-dresden.de - Linux RHEL 7.9, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/Flamefire/eb53b8daf570cb59930233cf2f0bcd18 for a full test report.

**Review by akesandgren — COMMENTED** [review]
This does fix incorrect symlinks being generated for newer (20xx) versions, but the code for "if self.toolchain.is_system_toolchain():" both was and still is broken due to multiple layers of relative synlinking.

**Comment by Flamefire** [comment]
> This does fix incorrect symlinks being generated for newer (20xx) versions, but the code for "if self.toolchain.is_system_toolchain():" both was and still is broken due to multiple layers of relative synlinking.

I see, we have

```
        # applications go looking into tbb/lib so we move what's in there to tbb/libs
        shutil.move(install_tbb_lib_path, os.path.join(self.installdir, 'tbb', 'libs'))
        # And add a symlink of the library folder to tbb/lib
        symlink(libpath, install_tbb_lib_path)

        root_lib_path = os.path.join(self.installdir, 'lib')
        move_file(libpath, root_lib_path)
        # Create a relative symlink at the original location as-if we didn't move it.
        # Note that the path must be relative from the folder where the symlink will be!
        symlink(os.path.relpath(root_lib_path, os.path.dirname(libpath)), libpath, use_abspath_source=False)
```

`libpath` is an actual folder, `install_tbb_lib_path` an absolute symlink to it. We move `libpath` and create a relative symlink to it

Now `install_tbb_lib_path` points to the relative symlink but is itself absolute, so shouldn't this work? Where do the multiple layers of relative symlinks come from?

**Comment by akesandgren** [comment]
From installdir of tbb/4.4.x (based under /home/a/ake/easybuild-amd64_ubuntu2004_bdw/software):
```
tbb -> compilers_and_libraries/linux/tbb/
compilers_and_libraries -> compilers_and_libraries_2016/
compilers_and_libraries_2016/linux/tbb -> ../../compilers_and_libraries_2016.3.210/linux/tbb/
compilers_and_libraries_2016.3.210/linux/tbb/lib -> /home/a/ake/easybuild-amd64_ubuntu2004_bdw/software/tbb/4.4.4.210/tbb/libs/intel64/gcc4.4
tbb/libs/intel64 -> ./intel64_lin/
tbb/libs/intel64_lin/gcc4.4 -> ../../../lib
```
But since that last one is really
compilers_and_libraries_2016.3.210/linux/tbb/libs/intel64_lin
the ../../../lib ends up as really being
compilers_and_libraries_2016.3.210/linux/lib
which doesn't exist.

**Comment by Flamefire** [comment]
@akesandgren I updated the easyblock to create the symlink with the resolved path.

I expect that to change `tbb/libs/intel64_lin/gcc4.4 -> ../../../lib` to `tbb/libs/intel64_lin/gcc4.4 -> ../../../../../lib` which should then work.

I can't test/debug this though as I can't find the 4.4 archive.

**Comment by akesandgren** [comment]
Test report by @akesandgren
#### Overview of tested easyconfigs (in order)

Build succeeded for 0 out of 0 (1 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/akesandgren/85cfbfeed8368ac335f6fc5ecf67e6e3 for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _tbb-4.4.4.210.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/akesandgren/fb6554572898944e2b388990f54475a0 for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _tbb-2017.2.132.eb_ 
 * **SUCCESS** _tbb-2019_U9-GCCcore-8.3.0.eb_ 
 * **SUCCESS** _tbb-2020.3-GCCcore-10.3.0.eb_ 
 * **SUCCESS** _tbb-2021.5.0-GCCcore-11.3.0.eb_ 

Build succeeded for 4 out of 4 (4 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/akesandgren/101f823a9b91de63d6517601a9e490f8 for a full test report.

**Review by akesandgren — APPROVED** [review]
LGTM

**Comment by akesandgren** [comment]
Going in, thanks @Flamefire!

**Comment by akesandgren** [comment]
Going in, thanks @Flamefire!

**Comment by akesandgren** [comment]
Going in, thanks @Flamefire!

**Comment by Flamefire** [comment]
> Test report by @akesandgren
> #### Overview of tested easyconfigs (in order)
> 
>     * **SUCCESS** _tbb-4.4.4.210.eb_

So I assume the symlinks are good there now?

**Pull request merged**
