### PR TITLE
use `run_shell_cmd` in custom easyblock for DualSPHysics

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _DualSPHysics-5.0.175-GCC-11.2.0.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0105u03a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/32b5edc825badcb7d0ec0b158dbe7857 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
"Can't find path /user/gent/400/vsc40023/data/DualSPHysics-5.0.175-GCC-11.2.0.eb"
Failed during parsing of the easyconfigs, so no ecs were built (1 easyconfigs in total)
node3564.doduo.os - Linux RHEL 8.8, x86_64, AMD EPYC 7552 48-Core Processor, Python 3.6.8
See https://gist.github.com/boegel/570f03d71931e1acc7bcc12db931790b for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _DualSPHysics-5.0.175-GCC-11.2.0.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3564.doduo.os - Linux RHEL 8.8, x86_64, AMD EPYC 7552 48-Core Processor, Python 3.6.8
See https://gist.github.com/boegel/3ef1d3538219ff5f2e8cffc5651cd675 for a full test report.

**Pull request merged**
