### PR TITLE
remove `hidden=True` from `run_shell_cmd` in `PythonPackage` easyblock for consistency

### PR DESCRIPTION
**Pull request by bartoldeman**
To address
https://github.com/easybuilders/easybuild-easyblocks/pull/3046#discussion_r1444031157 as a followup to #3046

### CODE REVIEW

**Review by boegel — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _Pillow-10.0.0-GCCcore-12.3.0.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
jscclxc1.int.jsc-clx.fz-juelich.de - Linux Rocky Linux 9.3, x86_64, Intel Xeon Processor (Cascadelake) (cascadelake), Python 3.9.18
See https://gist.github.com/SebastianAchilles/e4ac5b0f471cd730311c97169efc333e for a full test report.

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Going in, thanks @bartoldeman!

**Pull request merged**
