### PR TITLE
Move Go build junk into builddir

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _git-lfs-3.5.1.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/4ba6720d9892f7ca55c291b32b7aecd2 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _rclone-1.66.0.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/9a196269a1afab30ed83b78fe7c8f707 for a full test report.

**Comment by Micket** [comment]
Can confirm my ~/go directory is nice and empty after this change!

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
> Can confirm my ~/go directory is nice and empty after this change!

So was mine. Thanks!

**Comment by branfosj** [comment]
Going in, thanks @Micket!

**Pull request merged**
