### PR TITLE
also define CUDA_ROOT env var pointing to install dir

### PR DESCRIPTION
**Pull request by pescobar**

### CODE REVIEW

**Comment by boegel** [comment]
@pescobar For which software were you hitting this missing `$CUDA_ROOT`? A quick Google search seems to suggest this is software-specific (e.g. PyCUDA)?

**Comment by pescobar** [comment]
@boegel I noticed that one of my users was hardcoding this env var in his bashrc and I thought it would be useful to define it in the module . 

I thought it was a widely used env var. but you are right that this is not a standard env var. Only few applications use it. I didn't notice it. 

I think this PR can be discarded but it's also true that having this env var doesn't hurt

**Comment by boegel** [comment]
@easybuilders/easybuild-easyblocks-maintainers Thoughts on this?

It indeed doesn't hurt to let `CUDA` modules define `$CUDA_ROOT`, even though it's not standard?

**Comment by boegel** [comment]
awaiting feedback from @easybuilders/easybuild-easyblocks-maintainers ...

**Comment by boegel** [comment]
I'll go ahead and include this, under the assumption that things won't blow up.

If they do, we'll hear about it soon enough...

**Pull request merged**
