### PR TITLE
fix subdir path in VTune easyblock for 2021.x versions + add sanity check command

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by akesandgren** [comment]
The previous change to vtune.py only changed the sanity check, but what is really needed is to change subdir. This way sanity check doesn't need to be changed for 2021.x and we get a correctly set PATH

**Comment by akesandgren** [comment]
Test report by @akesandgren
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _VTune-2021.6.0.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/0fa9bcdb533b04c9181bae29cdf39f3b for a full test report.

**Comment by boegel** [comment]
@akesandgren Can we add a custom sanity check command too (using `--version` or `--help` on one of the tools)?
If it were there, we wouldn't have overlooked the `$PATH` issue...

**Comment by akesandgren** [comment]
Yeah, vtune --version should suffice. But I can't remember how to do that in a easyblock

**Comment by akesandgren** [comment]
@boegel Can you run a test for some older VTune? My container doesn't have the required OS packages for the older versions... preferably a pre 2020 version...

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _VTune-2021.6.0.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
rocky8-eb - Linux rocky linux 8.4, x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.6.8
See https://gist.github.com/368ea32ffb96dbc5b4c01f8453cd1f14 for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _VTune-2021.6.0.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/1f8874e21e90fff4db6e65abb09fdbda for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _VTune-2019_update5.eb_ 
 * **SUCCESS** _VTune-2020_update3.eb_ 
 * **SUCCESS** _VTune-2021.6.0.eb_ 

Build succeeded for 3 out of 3 (3 easyconfigs in total)
jrlogin01.jureca - Linux centos linux 8.3.2011, x86_64, AMD EPYC 7742 64-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/baf8f48d975c6fcf989285b619aab1d9 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _VTune-2013_update10.eb_ 
 * **SUCCESS** _VTune-2017.eb_ 
 * **SUCCESS** _VTune-2019_update5.eb_ 
 * **SUCCESS** _VTune-2020_update3.eb_ 
 * **SUCCESS** _VTune-2021.6.0.eb_ 

Build succeeded for 5 out of 5 (5 easyconfigs in total)
node2695.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/111a29221006431d2631db768919bd15 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Pull request merged**
