### PR TITLE
update ABAQUS easyblock to support installing of version 2021 with hot fixes

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

Loosely based on @orbsmiv's hard work in https://github.com/bear-rsg/easybuild-easyblocks/blob/2020a/easybuild/easyblocks/a/abaqus.py ;)

### CODE REVIEW

**Review by bartoldeman — APPROVED** [review]
LGTM

**Comment by bartoldeman** [comment]
I'll just wait for the test reports before merging.

**Comment by branfosj** [comment]
Test report by @branfosj
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _ABAQUS-2021-hotfix-2117.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/dff2cf9f1c49c67e3afdb1fc82ef0b02 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _ABAQUS-2021.eb_ 
 * **SUCCESS** _ABAQUS-2021-hotfix-2042.eb_ 
 * **SUCCESS** _ABAQUS-2021-hotfix-2132.eb_ 
 * **SUCCESS** _ABAQUS-2020.eb_ 
 * **SUCCESS** _ABAQUS-6.14.1-linux-x86_64.eb_ 
 * **SUCCESS** _ABAQUS-2018-hotfix-1806.eb_ 

Build succeeded for 6 out of 6 (6 easyconfigs in total)
node2641.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/35df06a1c526e4dc1b3ef9a26895af8f for a full test report.

**Pull request merged**
