### PR TITLE
Use on_error rather than deprecated log_error named argument for which function

### PR DESCRIPTION
**Pull request by Flamefire**
Followup to https://github.com/easybuilders/easybuild-framework/pull/3661 using the non-deprecated param

CC @smoors

### CODE REVIEW

**Comment by smoors** [comment]
@Flamefire can you submit a test report for a CUDA and/or TF easyconfig (to be sure everything still works)?

**Comment by Flamefire** [comment]
Sure, report for CUDA is coming up. TF has the exact same change so if CUDA works TF will work too, and running a full build on TF is expensive

**Comment by Flamefire** [comment]
Test report by @Flamefire
#### Overview of tested easyconfigs (in order)
 * **FAIL (unhandled exception: which() got an unexpected keyword argument 'on_error')Traceback (most recent call last):
  File "/home/h3/s3248973/.local/EasyBuildDev/easybuild-framework/easybuild/main.py", line 117, in build_and_install_software
    (ec_res['success'], app_log, err) = build_and_install_one(ec, init_env)
  File "/home/s3248973/.local/EasyBuildDev/easybuild-framework/easybuild/framework/easyblock.py", line 3404, in build_and_install_one
    result = app.run_all_steps(run_test_cases=run_test_cases)
  File "/home/s3248973/.local/EasyBuildDev/easybuild-framework/easybuild/framework/easyblock.py", line 3303, in run_all_steps
    self.run_step(step_name, step_methods)
  File "/home/s3248973/.local/EasyBuildDev/easybuild-framework/easybuild/framework/easyblock.py", line 3158, in run_step
    step_method(self)()
  File "/tmp/easybuild-tmp/included-easyblocks-v_yi4T/easybuild/easyblocks/cuda.py", line 198, in post_install_step
    ldconfig = which('ldconfig', log_ok=False, on_error=IGNORE)
TypeError: which() got an unexpected keyword argument 'on_error'
** _CUDA-10.2.89-GCC-8.3.0.eb_ 

Build succeeded for 0 out of 1 (1 easyconfigs in total)
taurusi6163.taurus.hrsk.tu-dresden.de - Linux RHEL 7.9, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/a53453580415848eed7309fea0c51e83 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _CUDA-10.2.89-GCC-8.3.0.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
taurusi6163.taurus.hrsk.tu-dresden.de - Linux RHEL 7.9, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/9ac47d6c07af4bb1aa2b619e3fa267d2 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test with TensorFlow coming up, but should be good to go indeed...

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _TensorFlow-2.4.1-foss-2020b.eb_ 
 * **FAIL (unhandled exception: which() got an unexpected keyword argument 'on_error')Traceback (most recent call last):
  File "/data/gent/400/vsc40023/easybuild_easy_installed/lib/python3.6/site-packages/easybuild_framework-4.3.5.dev0-py2.7.egg/easybuild/main.py", line 117, in build_and_install_software
    (ec_res['success'], app_log, err) = build_and_install_one(ec, init_env)
  File "/data/gent/400/vsc40023/easybuild_easy_installed/lib/python3.6/site-packages/easybuild_framework-4.3.5.dev0-py2.7.egg/easybuild/framework/easyblock.py", line 3404, in build_and_install_one
    result = app.run_all_steps(run_test_cases=run_test_cases)
  File "/data/gent/400/vsc40023/easybuild_easy_installed/lib/python3.6/site-packages/easybuild_framework-4.3.5.dev0-py2.7.egg/easybuild/framework/easyblock.py", line 3303, in run_all_steps
    self.run_step(step_name, step_methods)
  File "/data/gent/400/vsc40023/easybuild_easy_installed/lib/python3.6/site-packages/easybuild_framework-4.3.5.dev0-py2.7.egg/easybuild/framework/easyblock.py", line 3158, in run_step
    step_method(self)()
  File "/tmp/eb-3l_qy0zb/included-easyblocks-73wkvylm/easybuild/easyblocks/cuda.py", line 198, in post_install_step
    ldconfig = which('ldconfig', log_ok=False, on_error=IGNORE)
TypeError: which() got an unexpected keyword argument 'on_error'
** _CUDAcore-11.2.2.eb_ 

Build succeeded for 1 out of 2 (2 easyconfigs in total)
node3501.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/c29d930d790891041bb51b169bbebe52 for a full test report.

**Comment by Flamefire** [comment]
@boegel Only the fosscuda TF triggers the code path in question, the foss does not. And did you forget to update framework (#3661)?

**Comment by boegel** [comment]
@Flamefire Yes, I was using an old `easybuild-framework` branch, let me try that again. :)

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _CUDAcore-11.2.2.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3501.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/50482be6ce9d01d889dbe4b247c399c8 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _TensorFlow-2.4.1-fosscuda-2020b.eb_ 
 * **SUCCESS** _CUDAcore-11.1.1.eb_ 

Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3302.joltik.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/d187012f5e69bcb06b51fff97267098d for a full test report.

**Pull request merged**
