### PR TITLE
adjust qa list in WIEN2k easyblock to handle new questions + fix sanity check for v21.1

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@akesandgren Do you have access to the sources for all WIEN2k versions that we have easyconfigs for?

Since you're also removing questions, it would be nice to get good coverage in testing existing WIEN2k easyconfigs for this...

**Comment by boegel** [comment]
@akesandgren Then please submit a test report with WIEN2k 21.1

**Comment by boegel** [comment]
@akesandgren Ah, that's actually done already in https://github.com/easybuilders/easybuild-easyconfigs/pull/13972, nevermind :)

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _WIEN2k-19.2-intel-2020b.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2605.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/d666832dfe774856ce1f2b7129bb7bf4 for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _WIEN2k-17.1-foss-2018a.eb_ 
 * **SUCCESS** _WIEN2k-18.1-foss-2018a.eb_ 
 * **FAIL (build issue)** _WIEN2k-19.1-intel-2019a.eb_ (partial log available at https://gist.github.com/a31e05f27c1c0a60dbfd0b136f0cc46c)
 * **SUCCESS** _WIEN2k-19.2-intel-2020b.eb_ 
 * **SUCCESS** _WIEN2k-21.1-intel-2021a.eb_ 

Build succeeded for 4 out of 5 (5 easyconfigs in total)
sms - Linux centos linux 7.6.1810, x86_64, AMD EPYC 7601 32-Core Processor (zen), Python 2.7.5
See https://gist.github.com/c44bb161b698b82abbd857409285939b for a full test report.

**Comment by boegel** [comment]
@migueldiascosta 
```
== 2021-09-12 15:43:35,433 run.py:233 INFO running cmd: run_lapw -i 3 
== 2021-09-12 15:43:37,477 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:124 in __init__): cmd "run_lapw -i 3" exited with exit code 9 and output:
 LAPW0 END
SECLR4 - Error
grep: lapw2*.error: No such file or directory
```

Did we break something? If so, please open an issue to follow up (and tag it with next release)

**Comment by migueldiascosta** [comment]
@boegel I think this is related to the number of openmp threads used and only in that particular version, let me check

(I think in general we should limit the number of threads used in the test case (above I was using 4) because it can be painfully slow to use many more, but it should work with a few threads per process, and it does in the other versions...)

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _WIEN2k-19.1-intel-2019a.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
sms - Linux centos linux 7.6.1810, x86_64, AMD EPYC 7601 32-Core Processor (zen), Python 2.7.5
See https://gist.github.com/ecf5e0a0692f2df374ea3bf66e6cc6c2 for a full test report.

**Pull request merged**
