### PR TITLE
update PyTorch easyblock to avoid configure warnings by disabling some options

### PR DESCRIPTION
**Pull request by Flamefire**
Explicitely disable some options to avoid warnings during the configure.

### CODE REVIEW

**Comment by boegel** [comment]
@Flamefire Can you clarify what kind of warning pop up without these changes?

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2
CORE_CNT=16
EB_ARGS="PyTorch-1.13.1-foss-2022a-CUDA-11.7.0.eb PyTorch-2.1.2-foss-2023a.eb"

**Comment by Flamefire** [comment]
> @Flamefire Can you clarify what kind of warning pop up without these changes?

Stuff like: "Not compiling with X. Pass Y to disable this warning". E.g.: https://github.com/pytorch/pytorch/blob/40a6710ad34ae4c6f4987f0e47b5c94df3fc8ec7/cmake/Dependencies.cmake#L803-L813

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2
CORE_CNT=16
EB_ARGS="PyTorch-1.13.1-foss-2022a-CUDA-11.7.0.eb PyTorch-2.1.2-foss-2023a.eb"

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _PyTorch-1.10.0-foss-2021a-CUDA-11.3.1.eb_ 
 * **SUCCESS** _PyTorch-1.11.0-foss-2021a-CUDA-11.3.1.eb_ 
 * **SUCCESS** _PyTorch-1.12.0-foss-2022a-CUDA-11.7.0.eb_ 
 * **SUCCESS** _PyTorch-1.12.1-foss-2021a-CUDA-11.3.1.eb_ 
 * **FAIL (build issue)** _PyTorch-1.12.1-foss-2021b-CUDA-11.5.2.eb_ (partial log available at https://gist.github.com/boegel/2640b41c9f8ee1f3e827e57c95c873ae)
 * **SUCCESS** _PyTorch-1.12.1-foss-2022a-CUDA-11.7.0.eb_ 
 * **SUCCESS** _pytest-rerunfailures-11.1-GCCcore-11.3.0.eb_ 
 * **SUCCESS** _pytest-shard-0.1.2-GCCcore-11.3.0.eb_ 
 * **FAIL (build issue)** _PyTorch-1.13.1-foss-2022a-CUDA-11.7.0.eb_ (partial log available at https://gist.github.com/boegel/4498523636b35f08ed7804ce7d9ec05a)

Build succeeded for 7 out of 9 (7 easyconfigs in total)
node3905.accelgor.os - Linux RHEL 8.8, x86_64, AMD EPYC 7413 24-Core Processor (zen3), 1 x NVIDIA NVIDIA A100-SXM4-80GB, 535.129.03, Python 3.6.8
See https://gist.github.com/boegel/e6b728c6f7fb23b5351ccd707c143ab3 for a full test report.

**Comment by Flamefire** [comment]
@boegel 
>     * **FAIL (build issue)** _PyTorch-1.13.1-foss-2022a-CUDA-11.7.0.eb_ (partial log available at https://gist.github.com/boegel/4498523636b35f08ed7804ce7d9ec05a)

This failed because the check logic didn't find the number of failed tests but detected that some have failed ("+ test_ops_gradients ", the plus sign is an indication for this)
We might need to adjust the regex again. Can you attach the log?   
In any case this is nothing new from this PR and it seemingly only has 2 failed tests which looks fine

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
Test report by @branfosj
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _PyTorch-2.0.1-foss-2022b.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0105u03a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/a581d8d414c1200d452a7bed204fe898 for a full test report.

**Pull request merged**
