### PR TITLE
add custom easyblock for sympy to fix issue in test step when tmpdir is a symlink

### PR DESCRIPTION
**Pull request by casparvl**
(created using `eb --new-pr`)

see https://github.com/easybuilders/easybuild-easyconfigs/issues/17593

### CODE REVIEW

**Review by branfosj — CHANGES_REQUESTED** [review]

**Review by branfosj — DISMISSED** [review]
@casparvl I am happy with this, but can we have a test report from the system where this was failing before?

**Comment by boegel** [comment]
We also need an accompanying easyconfigs PR to make the `sympy` easyconfigs use this custom easyblock?

**Comment by casparvl** [comment]
Created one just now https://github.com/easybuilders/easybuild-easyconfigs/pull/18428 
I'll start creating test reports later...

**Comment by casparvl** [comment]
@branfosj Reports are at  https://github.com/easybuilders/easybuild-easyconfigs/pull/18428#issuecomment-1663080841
That was done on the system where it was failing before, see https://github.com/easybuilders/easybuild-easyconfigs/pull/17467#issuecomment-1658529566

**Review by boegel — CHANGES_REQUESTED** [review]
This easyblock should also take care of the sanity check, etc., so the `sympy` easyconfigs can become pretty minimal.

I'm working on that, will send a PR to the branch used for this PR soon, testing first...

**Review by boegel — APPROVED** [review]
Extensively tested via https://github.com/easybuilders/easybuild-easyconfigs/pull/18428, good to go, thanks @casparvl!

**Pull request merged**
