### PR TITLE
added support for ESMPy in ESMF

### PR DESCRIPTION
**Pull request by mboisson**

### CODE REVIEW

**Comment by mboisson** [comment]
@boegel or Damian may want to review this PR. It adds Python support if Python is in the dependencies.

**Comment by branfosj** [comment]
Test report by @branfosj
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _ESMF-7.1.0r-foss-2019a.eb_ 
 * **SUCCESS** _ESMF-8.0.0-foss-2019b.eb_ 
 * **SUCCESS** _ESMF-8.1.1-foss-2021a.eb_ 
 * **SUCCESS** _ESMF-8.2.0-foss-2021b.eb_ 

Build succeeded for 4 out of 4 (4 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/37f2dcae6248417edf7a8b2d10b46bd9 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
#### Overview of tested easyconfigs (in order)
 * **FAIL (build issue)** _ESMF-8.2.0-foss-2021b.eb_ (partial log available at https://gist.github.com/4023d2bbd9c3a55fed39ff854a185f74)

Build succeeded for 0 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/ae2df078c4ffac494310a88fe5d71289 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _ESMF-8.2.0-foss-2021b.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/7acb671060efb0abf225d45c02988bb0 for a full test report.

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Going in, thanks @mboisson!

**Pull request merged**
