### PR TITLE
update WIEN2k easyblock for v23.2

### PR DESCRIPTION
**Pull request by lcniel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16
EB_ARGS="WIEN2k-21.1-intel-2021b.eb"

**Comment by akesandgren** [comment]
@boegelbot please test @ generoso
CORE_CNT=16
EB_ARGS="WIEN2k-21.1-intel-2021b.eb"

**Comment by akesandgren** [comment]
See build report in https://github.com/easybuilders/easybuild-easyconfigs/pull/19247

**Review by akesandgren — APPROVED** [review]
LGTM

**Comment by akesandgren** [comment]
Going in, thanks @lcniel!

**Pull request merged**
