### PR TITLE
update imkl easyblock to unpack example tarballs and set $MKL_EXAMPLES (+ some code cleanup)

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by branfosj — CHANGES_REQUESTED** [review]

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _imkl-11.3.1.150-iimpi-8.1.5-GCC-4.9.3-2.25.eb_ 
 * **SUCCESS** _imkl-11.3.2.181-iimpi-2016.02-GCC-4.9.3-2.25.eb_ 
 * **SUCCESS** _imkl-11.3.3.210-iimpi-2016b.eb_ 
 * **SUCCESS** _imkl-11.3.3.210-iompi-2016.07.eb_ 
 * **SUCCESS** _imkl-11.3.3.210-iompi-2016.09-GCC-4.9.3-2.25.eb_ 
 * **SUCCESS** _imkl-2018.2.199-iompi-2018.02.eb_ 
 * **SUCCESS** _imkl-2018.3.222-iimpi-2018b.eb_ 
 * **SUCCESS** _imkl-2018.3.222-iompi-2018b.eb_ 
 * **SUCCESS** _imkl-2019.1.144-iimpi-2019a.eb_ 
 * **SUCCESS** _imkl-2019.5.281-iimpi-2019b.eb_ 
 * **SUCCESS** _imkl-2019.5.281-iimpic-2019b.eb_ 
 * **SUCCESS** _imkl-2019.5.281-iompi-2019b.eb_ 
 * **SUCCESS** _imkl-2020.1.217-iimpi-2020a.eb_ 
 * **SUCCESS** _imkl-2020.1.217-iimpic-2020a.eb_ 
 * **SUCCESS** _imkl-2020.4.304-iimpi-2020b.eb_ 
 * **SUCCESS** _imkl-2020.4.304-iimpic-2020b.eb_ 
 * **SUCCESS** _imkl-2020.4.304-iompi-2020b.eb_ 

Build succeeded for 17 out of 17 (17 easyconfigs in total)
node2618.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/4f94d461dbda18076167e6ee585667cf for a full test report.

**Comment by SebastianAchilles** [comment]
For newer versions of `imkl` (I only checked v2021.2.0 so far) the path to the examples changed from
```
'MKL_EXAMPLES': '%(installdir)s/mkl/examples/',
```
to
```
'MKL_EXAMPLES': '%(installdir)s/mkl/%(version)s/examples/'
```

**Comment by boegel** [comment]
> For newer versions of `imkl` (I only checked v2021.2.0 so far) the path to the examples changed

That's taken into account here via `self.mkl_basedir`.

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _imkl-11.3.1.150-iimpi-8.1.5-GCC-4.9.3-2.25.eb_ 
 * **SUCCESS** _imkl-11.3.2.181-iimpi-2016.02-GCC-4.9.3-2.25.eb_ 
 * **SUCCESS** _imkl-11.3.3.210-iimpi-2016b.eb_ 
 * **SUCCESS** _imkl-11.3.3.210-iompi-2016.07.eb_ 
 * **SUCCESS** _imkl-11.3.3.210-iompi-2016.09-GCC-4.9.3-2.25.eb_ 
 * **SUCCESS** _imkl-2018.2.199-iompi-2018.02.eb_ 
 * **SUCCESS** _imkl-2018.3.222-iimpi-2018b.eb_ 
 * **SUCCESS** _imkl-2018.3.222-iompi-2018b.eb_ 
 * **SUCCESS** _imkl-2019.1.144-iimpi-2019a.eb_ 
 * **SUCCESS** _imkl-2019.5.281-iimpi-2019b.eb_ 
 * **SUCCESS** _imkl-2019.5.281-iimpic-2019b.eb_ 
 * **SUCCESS** _imkl-2019.5.281-iompi-2019b.eb_ 
 * **SUCCESS** _imkl-2020.1.217-iimpi-2020a.eb_ 
 * **SUCCESS** _imkl-2020.1.217-iimpic-2020a.eb_ 
 * **SUCCESS** _imkl-2020.4.304-iimpi-2020b.eb_ 
 * **SUCCESS** _imkl-2020.4.304-iimpic-2020b.eb_ 
 * **SUCCESS** _imkl-2020.4.304-iompi-2020b.eb_ 

Build succeeded for 17 out of 17 (17 easyconfigs in total)
node2618.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/bfaf63e595380696f01b59f239a6aba5 for a full test report.

**Comment by SebastianAchilles** [comment]
> > For newer versions of `imkl` (I only checked v2021.2.0 so far) the path to the examples changed
> 
> That's taken into account here via `self.mkl_basedir`.

That is Perfect! Sorry, I didn't spot the conditional `self.mkl_basedir` when I first looked at the changes.

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Going in, thanks @boegel!

**Pull request merged**
