### PR TITLE
Add cleanup in easyblock of OpenFoam

### PR DESCRIPTION
**Pull request by wpoely86**

### CODE REVIEW

**Comment by boegel** [comment]
This requires retesting all OpenFOAM(-Extend) builds, so assigning 2.6.0 milestone on this...

**Comment by boegel** [comment]
ping on retesting?

**Comment by boegel** [comment]
@wpoely86: reping...

**Comment by boegel** [comment]
@besserox: thoughts on this?

**Comment by besserox** [comment]
@wpoely86 Can you elaborate on why it is necessary to do this?

Doesn't EasyBuild remove any previous install before building?
Or does the downloaded tarball come unclean?

**Comment by wpoely86** [comment]
@besserox It's not clear to me. It's part of several easyconfigs for OpenFoam-Extend and @boegel asked to put it in the block.

Under most normal circumstances, this should do nothing but it doesn't hurt either.

**Comment by besserox** [comment]
OK. It should not hurt.

Do you have a PR to remove these lines from the easyconfigs?

**Comment by wpoely86** [comment]
There is now: hpcugent/easybuild-easyconfigs#2689

**Comment by akesandgren** [comment]
wcleanAll is indeed needed under certain situations. Like adding patches that adds new include files for instance. So yes, please include this.
Although a simple wcleanAll without the "|| echo" stuff is quite sufficient.

**Comment by wpoely86** [comment]
OK, lets gets is old PR merged then! 

We should clean up the easyconfigs too but it doesn't hurt to already merge this. In the worst case, the clean is done twice.

**Comment by boegel** [comment]
Testing this with existing OpenFOAM easyconfigs...

**Comment by boegel** [comment]
Checks out, no problems encountered when testing with existing `OpenFOAM` and `OpenFOAM-Extend` easyconfigs, so going in, thanks @wpoely86!

**Comment by boegel** [comment]
So apparently my checking of this wasn't thorough enough, since `wcleanAll` is not available anymore for recent OpenFOAM versions, it has been replaced by `wcleanPlatform -all` (cfr. https://github.com/OpenFOAM/OpenFOAM-4.x/commit/119708e401328f40a6e10535987cea550fec97d9)...

It seems like `wcleanPlatform -all` should be used for OpenFOAM 4.x , but not for OpenFOAM-Extend 4.x...

Fix in https://github.com/easybuilders/easybuild-easyblocks/pull/1258

**Pull request merged**
