### PR TITLE
update QuantumESPRESSO easyblock for v6.4.1

### PR DESCRIPTION
**Pull request by Micket**
1. Generalize binary copying code
2. Add full include paths for ELPA (2017+ we have skipped the symlinks, might as well just always use the right include path)
3. Remove sanity check for binaries dropped from > v6.4

### CODE REVIEW

**Comment by migueldiascosta** [comment]
@Micket did you try this with the 6.4 "release pack", besides 6.4.1? I had to add a special case for `install_subdir`,

```
@@ -62,7 +62,10 @@
         super(EB_QuantumESPRESSO, self).__init__(*args, **kwargs)
 
         if LooseVersion(self.version) >= LooseVersion("6"):
-            self.install_subdir = "qe-%s" % self.version
+            if self.version == '6.4':
+                self.install_subdir = "qe_release_%s" % self.version
+            else:
+                self.install_subdir = "qe-%s" % self.version
         else:
             self.install_subdir = "espresso-%s" % self.version
 

```

**Comment by Micket** [comment]
@migueldiascosta I didn't test 6.4
What do you say about having an option to specify the installdir as part of the config file instead so that we don't have to hack in more version specifics into the block?

**Comment by boegel** [comment]
@Micket As discussed during conf call, having a fallback option to manually specify the install subdir makes sense to me, but we should keep giving preference to handling it in the easyblock...

**Comment by Micket** [comment]
As generalizing the install subdir path isn't necessary for 6.4.1, and can be done independently of these fixes, I'm suggesting someone reviews this PR as it is. I will make a new one for the subdir option, to make them easier to review.

**Comment by boegel** [comment]
I think this is good to go, I've tested it with a couple of existing `QuantumESPRESSO` easyconfigs (old & new), and test report for are on their way. If no issues pop up, I'll merge it tomorrow...

**Comment by migueldiascosta** [comment]
Going in, thanks @Micket!

**Pull request merged**
