### PR TITLE
load module early during PythonPackage's sanity check step via sanity_check_load_module

### LINKED ISSUE #2745: PythonPackage is not compatible with --sanity-check-only
Using `--sanity-check-only` on something that was installed with the `PythonPackage` (or `PythonBundle`, or a derivative) easyblock fails with:

```
== FAILED: Installation ended unsuccessfully (build directory: /tmp/easybuild_build/pygmo/2.16.1/foss-2020b): build failed (first 300 chars): cmd "pip --version" exited with exit code 127 and output:
/bin/bash: pip: command not found
 (took 0 secs)
```

The problem is that the module (which is already installed) only gets loaded later, when the parent `sanity_check_step` is being called.

### PR DESCRIPTION
**Pull request by boegel**
requires:
* https://github.com/easybuilders/easybuild-framework/pull/4125

fixes #2745

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _Python-3.9.6-GCCcore-11.2.0.eb_ 
 * **FAIL (build issue)** _xarray-0.15.1-foss-2019b-Python-3.7.4.eb_ (partial log available at https://gist.github.com/8051af7ae32f0a1ef3a87538ff5e210d)
 * **FAIL (build issue)** _scikit-learn-0.24.2-intel-2021a.eb_ (partial log available at https://gist.github.com/7a3a908235cf52801a0f3999d80f370e)
 * **SUCCESS** _matplotlib-3.5.2-foss-2022a.eb_ 
 * **FAIL (build issue)** _h5py-3.6.0-intel-2021b.eb_ (partial log available at https://gist.github.com/83d92ab96ecdd5492833d74c696ac379)

Build succeeded for 2 out of 5 (5 easyconfigs in total)
node3139.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/8a8fb30fb0352c57ebca18d86bb9ffd2 for a full test report.

**Comment by boegel** [comment]
Hmm, clearly not working yet as intended...

**Comment by boegel** [comment]
A fix in `extensioneasyblock.py` was also needed (see https://github.com/easybuilders/easybuild-framework/pull/4125/commits/e282dbe0a5f42763c2224a311db1a48abdbf9161), as well as not generating/loading the fake module prior to running `pip check` in `PythonPackage.sanity_check_step` (see 57288b6).

**Review by akesandgren — APPROVED** [review]
LGTM

**Comment by akesandgren** [comment]
Going in, thanks @boegel!

**Pull request merged**
