### PR TITLE
add custom easyblock for JAX

### PR DESCRIPTION
**Pull request by edmondac**
For https://github.com/easybuilders/easybuild-easyconfigs/pull/11595

### CODE REVIEW

**Comment by edmondac** [comment]
See https://github.com/easybuilders/easybuild-easyconfigs/pull/11595 for successful test reports. The CI on there won't work until this PR is merged, I believe.

**Comment by Flamefire** [comment]
@edmondac Could you factor out the Bazel EB? I'd like to see that merged fast as my TF stuff is blocked by that ****

**Comment by edmondac** [comment]
> @edmondac Could you factor out the Bazel EB? I'd like to see that merged fast as my TF stuff is blocked by that ****

Sure - Bazel commits cherry-picked to a new branch in https://github.com/easybuilders/easybuild-easyblocks/pull/2272

**Comment by branfosj** [comment]
easybuilders/easybuild-easyconfigs#11595 is closed as we are going with a different method for installing jax / jaxlib, so this is unneeded.

**Comment by Flamefire** [comment]
We might revisit this though depending on how hard the EC turns out to be and if we want to move stuff out of it. But technically we don't need an easyblock, well besides patching the TF dependency

**Pull request closed without merging**
