### PR TITLE
use `PYPI_SOURCE` constant in generic `PythonPackage` easyblock + custom easyblock for Python

### PR DESCRIPTION
**Pull request by Flamefire**
Required after the conversion in 

- [x] https://github.com/easybuilders/easybuild-framework/pull/4595

### CODE REVIEW

**Review by boegel — APPROVED** [review]
lgtm (but requires that https://github.com/easybuilders/easybuild-framework/pull/4595 is merged first)

**Comment by Micket** [comment]
Test report by @Micket
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _cryptography-42.0.8-GCCcore-13.3.0.eb_ 
 * **SUCCESS** _Python-3.12.3-GCCcore-13.3.0.eb_ 
 * **SUCCESS** _Python-bundle-PyPI-2024.06-GCCcore-13.3.0.eb_ 
 * **SUCCESS** _Mako-1.3.5-GCCcore-13.3.0.eb_ 

Build succeeded for 4 out of 4 (4 easyconfigs in total)
alvis-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/75149b61849bb923d4984da7566645a1 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _libyaml-0.2.5-GCCcore-13.3.0.eb_ 
 * **FAIL (build issue)** _LibTIFF-4.6.0-GCCcore-13.3.0.eb_ (partial log available at https://gist.github.com/Micket/edd61aa41e513f140504db3171f10c3e)
 * **SUCCESS** _Zip-3.0-GCCcore-13.3.0.eb_ 
 * **SUCCESS** _virtualenv-20.26.2-GCCcore-13.3.0.eb_ 
 * **SUCCESS** _Eigen-3.4.0-GCCcore-13.3.0.eb_ 

Build succeeded for 4 out of 5 (5 easyconfigs in total)
vera-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/26d1d54923e367c8f896325afa14ba39 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _jbigkit-2.1-GCCcore-13.3.0.eb_ 
 * **SUCCESS** _NASM-2.16.03-GCCcore-13.3.0.eb_ 
 * **SUCCESS** _libjpeg-turbo-3.0.1-GCCcore-13.3.0.eb_ 
 * **SUCCESS** _libdeflate-1.20-GCCcore-13.3.0.eb_ 
 * **SUCCESS** _LibTIFF-4.6.0-GCCcore-13.3.0.eb_ 

Build succeeded for 5 out of 5 (1 easyconfigs in total)
vera-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/7c44898133382cde1731f0331e5772d1 for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Pull request merged**
