### PR TITLE
update Boost easyblock to support use of 'b2'

### PR DESCRIPTION
**Pull request by fizwit**

### CODE REVIEW

**Comment by fizwit** [comment]
I have made corrections to boost.py that were recommended by wpoely86  boost #1063

**Comment by boegel** [comment]
@fizwit please clarify the PR title?

**Comment by boegel** [comment]
@fizwit also, I think you meant to refer to #1062 rather than #1063

Why are you opening an entirely new PR for this, rather than updating #1062 to react to the suggestions?

**Comment by fizwit** [comment]
thanks for your reply,
yes, I meant to refer to PR 1062.

It's embarrassing for me to admit but, I am extremely dyslexic and the
written documentation for git is impossible for me to understand. I
literally do not know how to merge an update to an existing PR.  Sorry I
just don't know the process

**Comment by boegel** [comment]
@fizwit It is not a big problem, it's just that it increasing the bookkeeping overhead a bit for us.
For this PR, let's leave it as is.

In fact, PR #1062 will be closed automatically when this PR gets merged, since you have the same commits included here (941514d and b0c36d7). GitHub is smart enough to see that the commits in #1062 will be already merged in...

To update an existing PR, you check out the branch that corresponds to that PR, add a new commit to it, and then push that branch.
In this case, PR #1062 corresponds to your `boost` branch, so it would look something like this:

```
git checkout boost
# edit easybuild/easyblocks/b/boost.py
git add easybuild/easyblocks/b/boost.py
git commit -m "fix remarks"
git push origin boost
```

(the last comment may differ, it depends on how you have set up your git repository, you can check with `git remote -v` to see which remote corresponds to yours)

Let me know if this helps you for future contributions. If it would be useful to you, we can set up a short conf call for a live demo of the process.

We are working to make `eb --new-pr` and `eb --update-pr` also work with easyblocks (and even framework) PRs, see https://github.com/hpcugent/easybuild-framework/pull/1876. I hope to finish that soon, that will make it significantly easier to contribute back (changes to existing) easyblocks.

**Comment by boegel** [comment]
@fizwit the proposed changes look good now, and seem to be backwards-compatible, thank you for taking that into account!

I did a quick test with enabling the use of `b2` to install `Boost-1.61.0-foss-2016b.eb` and `Boost-1.61.0-intel-2016b.eb`.

Using `b2` work fine for `Boost-1.61.0-foss-2016b.eb` worked fine, but with `Boost-1.61.0-intel-2016b.eb` I ran into an issue:

```
ERROR: Build of /vscmnt/gent_vulpix/_/user/data/gent/gvo000/gvo00002/vsc40023/Boost-1.61.0-intel-2016b.eb failed (err: "build failed (first 300 chars): Sanity check failed: no file of ('lib/libboost_mpi.so',) in /user/home/gent/vsc400/vsc40023/eb_phanpyscratch/CO7/haswell-ib/software/Boost/1.61.0-intel-2016b")
```

So, the `lib/libboost_mpi.so` file is not being installed when `intel/2016b` is used as toolchain.
This works fine when `b2` is not used though.

It seems like the MPI detection done by `b2` isn't working well with Intel MPI?

I also noticed that the build takes significantly longer when `b2` is being used, probably because the build is not being performed in parallel like we do with `bjam`?

To be clear: I don't consider this issue a blocker for this PR, since the use of `b2` is optional.

**Comment by fizwit** [comment]
thanks for the comments.  I understand the need to automate.  I have a lot
to contribute and want to get the process correct. I have two new tools,
easy_annotate.py and easy_update.py that I want to submit.  Easy_update can
update the ext_list for Python, R and R-BioConductor.  Easy_annotate reads
easyconfig files and creates static html documentation.  Check it out:
https://fredhutch.github.io/easybuild-life-sciences/

I hope to add Jekyll support to easy_annotate.py

hope all is well,

**Comment by boegel** [comment]
@fizwit you can contribute stand-alone scripts that can be useful for others in the `easybuild/scripts` directory at https://github.com/hpcugent/easybuild-framework

**Comment by boegel** [comment]
@fizwit any comments on the `b2` install procedure failing with `intel/2016b`? See https://github.com/hpcugent/easybuild-easyblocks/pull/1070#issuecomment-266191268 .

Should we enhance the changes made in this pull request first, or shall we merge this as is and revisit it later?

**Comment by boegel** [comment]
@fizwit Can you clarify why this PR was closed?

**Pull request closed without merging**
