### PR TITLE
correctly handle empty list of sources in PythonPackage._should_unpack_source 

### LINKED ISSUE #2441: _should_unpack_source in PythonPackage breaks if there are no sources
https://github.com/easybuilders/easybuild-easyblocks/blob/2c20ad0899067d91c4ac05aade254903249a075c/easybuild/easyblocks/generic/pythonpackage.py#L425-L434

assumes there is at least one source, either a string or a list. But e.g. MATLAB-Engine doesn't use its own sources at all so these are now broken.

Simple fix we check is there are no sources, then `return False`

### PR DESCRIPTION
**Pull request by Micket**
fixes #2441

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
#### Overview of tested easyconfigs (in order)

Build succeeded for 0 out of 0 (1 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/6d6c68112092b2f214893110dd11e0ba for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _MATLAB-Engine-2019a-GCCcore-8.3.0.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/8027cb53a3b88b62a6cc5154820c0204 for a full test report.

**Comment by boegel** [comment]
@Micket I'm not a big fan of inline returns, and it's clear a bit more care should be taken here, so I've taken this a bit further in ba8c776...

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _MATLAB-Engine-2019b-GCCcore-8.3.0.eb_ 
 * **SUCCESS** _Pysam-0.15.3-GCC-8.3.0.eb_ 
 * **SUCCESS** _matplotlib-3.3.3-foss-2020b.eb_ 
 * **SUCCESS** _plantcv-3.8.0-foss-2020a-Python-3.8.2.eb_ 
 * **SUCCESS** _pkgconfig-1.5.1-GCCcore-8.3.0-Python-3.7.4.eb_ 

Build succeeded for 5 out of 5 (5 easyconfigs in total)
node2617.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/26efaf3cc2b432621aa6591b84d148d4 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _Python-3.9.5-GCCcore-10.3.0.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3148.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/0acaa06ad0774475c2570b5cb243e2d3 for a full test report.

**Review by boegel — APPROVED** [review]

**Pull request merged**
