### PR TITLE
update Ferret easyblock to be compatible with v7.6.0

### PR DESCRIPTION
**Pull request by lexming**

### CODE REVIEW

**Comment by lexming** [comment]
@boegelbot: please test @ generoso
EB_ARGS="--include-easyblocks-from-pr=3052"

**Comment by lexming** [comment]
@boegelbot please test @ generoso
EB_ARGS="Ferret-7.5.0-foss-2019b.eb"

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
Test report by @branfosj
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _Ferret-7.5.0-foss-2019b.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/branfosj/5b9d8ca89a3f2296af126903bc2657b1 for a full test report.

**Comment by branfosj** [comment]
@boegelbot please test @ generoso
EB_ARGS="Ferret-7.5.0-foss-2019b.eb"

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
Going in, thanks @lexming!

**Pull request merged**
