### PR TITLE
Make `CMakeMake` respect the toolchainopts when selecting build type

### PR DESCRIPTION
**Pull request by Micket**
See title

### CODE REVIEW

**Review by Flamefire — APPROVED** [review]
LGTM

**Comment by Micket** [comment]
Test report by @Micket
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _CGAL-5.6.1-GCCcore-13.3.0.eb_ 
 * **SUCCESS** _fmt-9.1.0-GCCcore-12.2.0.eb_ 
 * **SUCCESS** _graphite2-1.3.14-GCCcore-13.3.0.eb_ 
 * **SUCCESS** _json-c-0.17-GCCcore-13.3.0.eb_ 
 * **SUCCESS** _libgit2-1.8.1-GCCcore-13.3.0.eb_ 
 * **SUCCESS** _libheif-1.17.6-GCC-12.3.0.eb_ 
 * **SUCCESS** _nvtop-3.1.0-GCCcore-12.3.0.eb_ 
 * **SUCCESS** _Qhull-2020.2-GCCcore-13.3.0.eb_ 
 * **SUCCESS** _RAxML-NG-1.2.0-GCC-12.3.0.eb_ 
 * **SUCCESS** _SentencePiece-0.2.0-GCC-13.2.0.eb_ 
 * **SUCCESS** _snappy-1.1.9-GCCcore-12.2.0.eb_ 
 * **SUCCESS** _SRA-Toolkit-3.1.1-gompi-2023b.eb_ 
 * **SUCCESS** _x265-3.6-GCCcore-13.3.0.eb_ 
 * **SUCCESS** _yaml-cpp-0.8.0-GCCcore-13.2.0.eb_ 

Build succeeded for 14 out of 14 (14 easyconfigs in total)
alvis-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/1c4a1ac142e565f3b90e7402d981a30d for a full test report.

**Comment by Micket** [comment]
Will repeat the tests above with debug: True

**Comment by Micket** [comment]
Test report by @Micket
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _CGAL-5.6.1-GCCcore-13.3.0.eb_ 
 * **SUCCESS** _fmt-9.1.0-GCCcore-12.2.0.eb_ 
 * **SUCCESS** _gmsh-4.12.2-foss-2023a.eb_ 
 * **SUCCESS** _graphite2-1.3.14-GCCcore-13.3.0.eb_ 
 * **SUCCESS** _json-c-0.17-GCCcore-13.3.0.eb_ 
 * **SUCCESS** _libgit2-1.8.1-GCCcore-13.3.0.eb_ 
 * **SUCCESS** _libheif-1.17.6-GCC-12.3.0.eb_ 
 * **SUCCESS** _nvtop-3.1.0-GCCcore-12.3.0.eb_ 
 * **SUCCESS** _Qhull-2020.2-GCCcore-13.3.0.eb_ 
 * **SUCCESS** _RAxML-NG-1.2.0-GCC-12.3.0.eb_ 
 * **SUCCESS** _SentencePiece-0.2.0-GCC-13.2.0.eb_ 
 * **SUCCESS** _snappy-1.1.9-GCCcore-12.2.0.eb_ 
 * **SUCCESS** _SRA-Toolkit-3.1.1-gompi-2023b.eb_ 
 * **SUCCESS** _x265-3.6-GCCcore-13.3.0.eb_ 
 * **SUCCESS** _yaml-cpp-0.8.0-GCCcore-13.2.0.eb_ 

Build succeeded for 15 out of 15 (15 easyconfigs in total)
alvis-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/52ae77ae0a426b7f7c6150762494784f for a full test report.

**Comment by Micket** [comment]
which also looked good to me, so now with noopt

**Comment by Micket** [comment]
Test report by @Micket
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _CGAL-5.6.1-GCCcore-13.3.0.eb_ 
 * **FAIL (build issue)** _fmt-9.1.0-GCCcore-12.2.0.eb_ (partial log available at https://gist.github.com/Micket/be6063393b1e2f4c3a39eeae1ed66d4e)
 * **SUCCESS** _graphite2-1.3.14-GCCcore-13.3.0.eb_ 
 * **SUCCESS** _json-c-0.17-GCCcore-13.3.0.eb_ 
 * **SUCCESS** _libgit2-1.8.1-GCCcore-13.3.0.eb_ 
 * **SUCCESS** _libheif-1.17.6-GCC-12.3.0.eb_ 
 * **SUCCESS** _nvtop-3.1.0-GCCcore-12.3.0.eb_ 
 * **FAIL (build issue)** _Qhull-2020.2-GCCcore-13.3.0.eb_ (partial log available at https://gist.github.com/Micket/81f9890a7a2a45883c5eed329140e555)
 * **SUCCESS** _RAxML-NG-1.2.0-GCC-12.3.0.eb_ 
 * **SUCCESS** _SentencePiece-0.2.0-GCC-13.2.0.eb_ 
 * **SUCCESS** _snappy-1.1.9-GCCcore-12.2.0.eb_ 
 * **FAIL (build issue)** _SRA-Toolkit-3.1.1-gompi-2023b.eb_ (partial log available at https://gist.github.com/Micket/4219b353f70b8ddeda8b2ac6e53e3064)
 * **SUCCESS** _x265-3.6-GCCcore-13.3.0.eb_ 
 * **FAIL (build issue)** _yaml-cpp-0.8.0-GCCcore-13.2.0.eb_ (partial log available at https://gist.github.com/Micket/57c56ca5378f1ec9705fe94ee04768a4)

Build succeeded for 10 out of 14 (14 easyconfigs in total)
alvis-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/0cf19fb6e8f346eb94f0a500b100ed44 for a full test report.

**Comment by Micket** [comment]
also looked good, though the noopt flag is still setting --march=native which seems strange (though that is due to *FLAGS environment variables, not due to the cmake easyblock.

Failures above is just that the build scripts intentionally append a "d" at the end of the library names, except for SRA-Toolkit which the build just breaks with you run debug (really unclear as to what is happening there, but, not CMake's fault from what i can see in the logs).

I think this is good to go in.

**Review by bartoldeman — APPROVED** [review]
lgtm

**Comment by Flamefire** [comment]
> also looked good, though the noopt flag is still setting --march=native which seems strange (though that is due to *FLAGS environment variables, not due to the cmake easyblock.

I guess  EBs `optarch` is orthogonal to debug builds. And makes sense to me.

> Failures above is just that the build scripts intentionally append a "d" at the end of the library names,

For those it might be better to use (potentially iterated) `configureopts` to build debug and release versions. It is intentional that the debug libs are named differently to allow them to coexist.

> except for SRA-Toolkit which the build just breaks with you run debug (really unclear as to what is happening there, but, not CMake's fault from what i can see in the logs).

"Usage:  vdb-dump <path> [<path> ...] [options]" --> Looks like it messes up an invocation of a helper program. Probably a bug in their build scripts which we can report.

**Pull request merged**
