### PR TITLE
modified perlmodule to be able to handle different options than the m…

### PR DESCRIPTION
**Pull request by mboisson**
…ain perl build. Modified Perl to support preconfigopts (and in particular accept having CFLAGS in it)

This PR also includes #1362 since I needed it to successfully build perl

### CODE REVIEW

**Comment by mboisson** [comment]
@boegel, I am not sure how much of all of this is needed for other sites, but here is what I had to add to our local EasyConfig to make the recipe work : 

`
# Directories from the build directory that need to be added to PERL5LIB
include_subdirs = [
		'',
		'lib',
		'cpan/AutoLoader/lib',
		'dist/Carp/lib',
		'dist/PathTools',
		'dist/PathTools/lib',
		'cpan/ExtUtils-Command/lib',
		'cpan/ExtUtils-Install/lib',
		'cpan/ExtUtils-MakeMaker/lib',
		'cpan/ExtUtils-Manifest/lib',
		'cpan/File-Path/lib',
		'ext/re',
		'dist/Term-ReadLine/lib',
		'dist/Exporter/lib',
		'ext/File-Find/lib',
		'cpan/Text-Tabs/lib',
		'dist/constant/lib',
		'lib/ExtUtils',
		]
perl5lib = ":%(builddir)s/perl-%(version)s/".join(include_subdirs)

# define our non-standard path for headers
configopts = "-Dlocincpth=$NIXUSER_PROFILE/include -Dinstallstyle=lib/perl5 -Dlibc=$NIXUSER_PROFILE/lib/libc.so.6 "
configopts += "-Dlibpth=$NIXUSER_PROFILE/lib -Dlibspath=$NIXUSER_PROFILE/lib -Dincpth=$NIXUSER_PROFILE/include "
prebuildopts = "export PERL5LIB=%s:$PERL5LIB && " % perl5lib
preinstallopts = prebuildopts

# overwrite using the same configopts or prebuildopts or preinstallopts as for the main perl
extensions_configopts = " "
extensions_prebuildopts = " "
extensions_preinstallopts = " "
`

**Comment by boegel** [comment]
@mboisson Is this still relevant now https://github.com/easybuilders/easybuild-framework/pull/2194 is merged?

**Comment by mboisson** [comment]
I haven't look in the details of easybuilders/easybuild-framework#2194  but it *seems* (?) to do the same, so I guess this PR is no longer needed.

**Comment by akesandgren** [comment]
@mboisson Could you take a look at 2194 and see if this one is needed or not?

**Comment by mboisson** [comment]
I did look at PR 2194 in June, and it does seem to do the same thing.

**Pull request closed without merging**
