### PR TITLE
enhance Amber easyblock to fix running of update_amber script when 'python' command is not available in OS

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

This is required for installing `Amber` or `AmberTools` on a system where no `python` command is available through the OS (which is easily the case on CentOS 8, for example).

### CODE REVIEW

**Comment by migueldiascosta** [comment]
lgtm on visible inspection but I wonder, would it be a problem to move loading the `builddependencies` to before the `patch_step`?

**Comment by boegel** [comment]
> lgtm on visible inspection but I wonder, would it be a problem to move loading the `builddependencies` to before the `patch_step`?

See https://github.com/easybuilders/easybuild-framework/issues/1376

**Comment by boegel** [comment]
@migueldiascosta So, is this good go in?

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @boegel!

**Pull request merged**
