### PR TITLE
handle new directory structure for Intel Advisor

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

For `2019_update5`: top level there is `advisor` that symlinks to `advisor_2019.5.0.602216` and inside that folder is `bin64`, etc.

For `2022.1.0`: the `bin64` directory is inside `advisor/2022.1.0` and there is a symlink inside `advisor` pointing `latest` to `2022.1.0`.

This change means that the following appear in the module file that were not there otherwise:
```
prepend_path("MANPATH", pathJoin(root, "advisor/latest/man"))
prepend_path("PATH", pathJoin(root, "advisor/latest/bin64"))
```

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _Advisor-2019_update5.eb_ 
 * **SUCCESS** _Advisor-2021.2.0.eb_ 
 * **SUCCESS** _Advisor-2022.1.0.eb_ 

Build succeeded for 3 out of 3 (3 easyconfigs in total)
bear-pg0104u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/401aa9cc45ef9d4b56010c28e733fe6a for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _Advisor-2021.4.0.eb_ 
 * **SUCCESS** _Advisor-2022.1.0.eb_ 
 * **SUCCESS** _Advisor-2023.0.0.eb_ 
 * **SUCCESS** _Advisor-2023.2.0.eb_ 

Build succeeded for 4 out of 4 (4 easyconfigs in total)
bwd-rockylinux-92 - Linux Rocky Linux 9.2 (Blue Onyx), x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), 2 x NVIDIA NVIDIA GeForce GTX 1060 6GB, 535.54.03, Python 3.9.16
See https://gist.github.com/SebastianAchilles/2176f67bda81581e66def52450439fb3 for a full test report.

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Going in, thanks @branfosj!

**Comment by SebastianAchilles** [comment]
Going in, thanks @branfosj!

**Pull request merged**
