### PR TITLE
don't grep for specific version in --version output of Intel compiler commands for versions 2022.x

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by robert-mijakovic** [comment]
ifx has also 2022.0.0

**Comment by boegel** [comment]
> ifx has also 2022.0.0

With this change I'm just running `ifx --version`, but I'm not checking the output at all.
Since `--version` also prints the location of the installation for some commands, there will always be a hit for `%(version)s`, so the check is kind of silly anyway...

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _intel-compilers-2021.1.2.eb_ 
 * **SUCCESS** _intel-compilers-2021.2.0.eb_ 
 * **SUCCESS** _intel-compilers-2021.3.0.eb_ 
 * **SUCCESS** _intel-compilers-2021.4.0.eb_ 

Build succeeded for 4 out of 4 (4 easyconfigs in total)
node3513.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/c054574a38b7a6cda094173147263181 for a full test report.

**Review by bedroge — APPROVED** [review]
lgtm

**Pull request merged**
