### PR TITLE
fix license file when running with --module-only for Gurobi

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

see comment in #2639

### CODE REVIEW

**Comment by smoors** [comment]
Test report by @smoors
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _Gurobi-9.1.2-GCCcore-10.2.0.eb_ 
 * **SUCCESS** _Gurobi-9.1.2-GCCcore-10.2.0.eb.orig_ 

Build succeeded for 2 out of 2 (2 easyconfigs in total)
node350.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/20aaa836a472eaa13d9b8d0c3280e7a2 for a full test report.

**Comment by smoors** [comment]
tested with the original easyconfig, and with `copy_license_file = False`
also tested with `--module-only --rebuild`

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _Gurobi-9.5.0-GCCcore-11.2.0.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2601.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/9aa81912c90c83c80ccaa7499e962a7e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _Gurobi-9.5.0-GCCcore-11.2.0.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2601.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/1026c282eb4fda757382c8d5c53884b5 for a full test report.

**Pull request merged**
