### PR TITLE
allow wxPython to be installed as an extension

### PR DESCRIPTION
**Pull request by mboisson**
Also using the 'build wheel + pip install wheel' mechanism, as otherwise, it would ignore the install prefix

### CODE REVIEW

**Review by akesandgren — APPROVED** [review]
LGTM

**Comment by akesandgren** [comment]
Going in, thanks @mboisson!

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _wxPython-4.0.4-GCC-8.2.0-2.31.1-Python-3.7.2.eb_ 
 * **SUCCESS** _wxPython-4.0.4-GCC-8.2.0-2.31.1-Python-2.7.15.eb_ 

Build succeeded for 2 out of 2 (2 easyconfigs in total)
node2643.swalot.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/2bf6852896734bd274969da3e7a17230 for a full test report.

**Comment by boegel** [comment]
The changes made here seem to be breaking the installation of `wxPython-4.0.7.post2-GCC-8.3.0-Python-3.7.4.eb` (which installs fine with EasyBuild v4.3.1). The sanity check fails because `.so` symlinks are missing in the installation:

```
== sanity checking...
...
  >> file 'lib/python3.7/site-packages/wx/libwx_baseu-3.0.so' found: FAILED
  >> file 'lib/python3.7/site-packages/wx/libwx_gtk3u_core-3.0.so' found: FAILED
```

Can someone confirm this?

**Comment by mboisson** [comment]
Mmm, these symlinks are indeed not in the `lib/pythonX.Y/site-packages/wx/`  folder, they are in the `lib` folder. I guess the sanity_checks have to be changed depending on the installation method ?

**Comment by boegel** [comment]
Not that it's only a problem for `wxPython-4.0.7`, the `wxPython-4.0.4` easyconfigs still work fine?!

Do you mind opening a PR to fix this before we fork off things for the EasyBuild v4.3.2 (which we'll do tomorrow or Wed)?

**Comment by mboisson** [comment]
Mmm, well I'm not in a situation to be able to test those EasyConfigs directly. I thought it might be just because the installation methods are not the same, and therefore result in different symlinks, but that it does not work for 4.0.7, but does for 4.0.4, that is mind-boggling.

**Comment by boegel** [comment]
Let's follow up in https://github.com/easybuilders/easybuild-easyconfigs/issues/11790, it's too difficult to follow up on problems in merged PRs...

**Pull request merged**
