### PR TITLE
allow version mismatchs between OpenSSL components in host system as long as they fulfill version requirements

### LINKED ISSUE #3337: OpenSSL version check fails on Debian-based distros for OpenSSL 3
Even though my host system had OpenSSL 3 installed, EB was still trying to build it from source instead of wrapping the system libraries. It turns out that it does find the two required libraries, but it fails to determine the version of one of them:
```
== 2024-05-23 12:51:35,977 openssl_wrapper.py:97 DEBUG Requiring minimum OpenSSL version: 3.0.0
== 2024-05-23 12:51:35,986 openssl_wrapper.py:137 INFO Matrix of version library names: [['libssl.so.3', 'libcrypto.so.3']]
== 2024-05-23 12:51:35,987 openssl_wrapper.py:145 INFO Target OpenSSL libraries: ['libssl.so.3', 'libcrypto.so.3']
== 2024-05-23 12:51:36,004 systemtools.py:1123 INFO Found absolute path to libssl.so.3: /usr/lib/riscv64-linux-gnu/libssl.so.3
== 2024-05-23 12:51:36,017 openssl_wrapper.py:195 DEBUG Could not detect the full version of system OpenSSL library: /usr/lib/riscv64-linux-gnu/libssl.so.3
== 2024-05-23 12:51:36,018 openssl_wrapper.py:203 DEBUG System OpenSSL library '/usr/lib/riscv64-linux-gnu/libssl.so.3' with version 0 is older than requested version 3.0.0
== 2024-05-23 12:51:36,033 systemtools.py:1123 INFO Found absolute path to libcrypto.so.3: /usr/lib/riscv64-linux-gnu/libcrypto.so.3
== 2024-05-23 12:51:36,113 openssl_wrapper.py:199 DEBUG System OpenSSL library '/usr/lib/riscv64-linux-gnu/libcrypto.so.3' with version 3.0.7 fulfills requested version 3.0.0
== 2024-05-23 12:51:36,114 openssl_wrapper.py:222 INFO OpenSSL library not found in host system, falling back to OpenSSL in EasyBuild
```

The filenames don't provide the version here (`libssl-dev` is installed), so EB will try to find the version by reading the file itself and looking for some string (https://github.com/easybuilders/easybuild-easyblocks/blob/develop/easybuild/easyblocks/o/openssl_wrapper.py#L104). This works for `libcrypto.so.3`, but it apparently this doesn't for `libssl.so.3` anymore in OpenSSL 3:

```
root@533ab7ae6861:/# grep PRETTY_NAME /etc/os-release 
PRETTY_NAME="Ubuntu 24.04 LTS"
root@533ab7ae6861:/# strings /usr/lib/x86_64-linux-gnu/libcrypto.so.3 | grep "OpenSSL 3"
OpenSSL 3.0.13 30 Jan 2024
root@533ab7ae6861:/# strings /usr/lib/x86_64-linux-gnu/libssl.so.3 | grep "OpenSSL 3"
root@533ab7ae6861:/# 
```

### PR DESCRIPTION
**Pull request by SebastianAchilles**
(created using `eb --new-pr`)
Fixes #3337

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _OpenSSL-3.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
zen2-ubuntu-2310 - Linux Ubuntu 23.10 (Mantic Minotaur), x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.11.6
See https://gist.github.com/SebastianAchilles/c522e570909613c9c630a0c1ed97f57a for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _OpenSSL-3.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
zen2-ubuntu-2404 - Linux Ubuntu 24.04 LTS (Noble Numbat), x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.12.3
See https://gist.github.com/SebastianAchilles/1c5a9c59b4a4ecf3e2a51c3390b76e0b for a full test report.

**Comment by bedroge** [comment]
Test report by @bedroge
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _OpenSSL-3.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
starfive - Linux Debian GNU/Linux n/a, RISC-V-64, UNKNOWN, Python 3.10.9
See https://gist.github.com/bedroge/8fd79fd41e7a47eaa4532f86f3fae649 for a full test report.

**Review by lexming — COMMENTED** [review]
Regarding the change on the version check of the headers, do the OpenSSL headers in your Debian-based system have a different version that the OpenSSL libraries in that same system?

**update**: @SebastianAchilles can you check two things:
1. in `opensslv.h`: check `OPENSSL_VERSION_TEXT`, `OPENSSL_VERSION_STR` and `OPENSSL_FULL_VERSION_STR`, do they match? does that version string appear in the corresponding `libssl.so`?
2. in `libssl.so`: what is the output of `strings libssl.so | head -n 1`?

**Review by lexming — COMMENTED** [review]
@SebastianAchilles I tested this PR on our systems and I have some changes to suggest:
* instead of checking that the major version of the headers is >= `3`, we should compare it with the minimum required version of OpenSSL set in the easyconfig. Then we don't need specific code per OpenSSL version while allowing mismatched version between library and header files.
* current easyblock does not work on RHEL 8 based system that have OpenSSL v3 installed as compat library alongside OpenSSL v1.1.
 
Please check PR https://github.com/SebastianAchilles/easybuild-easyblocks/pull/2 to this PR which incorporates these changes.

**Comment by SebastianAchilles** [comment]
>     1. in `opensslv.h`: check `OPENSSL_VERSION_TEXT`, `OPENSSL_VERSION_STR` and `OPENSSL_FULL_VERSION_STR`, do they match? does that version string appear in the corresponding `libssl.so`?

On Ubuntu 24.04 I see the following:
```
ubuntu-2404:~$ grep OPENSSL_VERSION_TEXT /usr/include/openssl/opensslv.h
# define OPENSSL_VERSION_TEXT "OpenSSL 3.0.13 30 Jan 2024"
ubuntu-2404:~$ grep OPENSSL_VERSION_STR /usr/include/openssl/opensslv.h
# define OPENSSL_VERSION_STR "3.0.13"
ubuntu-2404:~$ grep OPENSSL_FULL_VERSION_STR /usr/include/openssl/opensslv.h
# define OPENSSL_FULL_VERSION_STR "3.0.13"
```

This string does not appear in `libssl.so`:
```
ubuntu-2404:~$ strings /usr/lib/x86_64-linux-gnu/libssl.so.3 | grep "3.0.13"
ubuntu-2404:~$ strings /usr/lib/x86_64-linux-gnu/libssl.so.3 | grep "OPENSSL_3"
OPENSSL_3.0.0
OPENSSL_3.0.3
```

>     2. in `libssl.so`: what is the output of `strings libssl.so | head -n 1`?

```
ubuntu-2404:~$ strings /usr/lib/x86_64-linux-gnu/libssl.so.3 | head -n 1
/q T
```

**Comment by SebastianAchilles** [comment]
> @SebastianAchilles I tested this PR on our systems and I have some changes to suggest:
> 
>     * instead of checking that the major version of the headers is >= `3`, we should compare it with the minimum required version of OpenSSL set in the easyconfig. Then we don't need specific code per OpenSSL version while allowing mismatched version between library and header files.
> 
>     * `libcrypto` and `libssl` can contain multiple version strings, we need to sort them and pick the highest value
> 
>     * current easyblock does not work on RHEL 8 based system that have OpenSSL v3 installed as compat library alongside OpenSSL v1.1.
> 
> 
> Please check PR [SebastianAchilles#2](https://github.com/SebastianAchilles/easybuild-easyblocks/pull/2) to this PR which incorporates these changes.

Thanks for the suggestions. :+1: I just merged [SebastianAchilles#2](https://github.com/SebastianAchilles/easybuild-easyblocks/pull/2).

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _OpenSSL-3.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
zen2-ubuntu-2310 - Linux Ubuntu 23.10 (Mantic Minotaur), x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.11.6
See https://gist.github.com/SebastianAchilles/50e8c54e64483e4dbcd2613017beb7f4 for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _OpenSSL-3.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
zen2-ubuntu-2404 - Linux Ubuntu 24.04 LTS (Noble Numbat), x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.12.3
See https://gist.github.com/SebastianAchilles/6a394cd95a8a05aa3c6e376572611b57 for a full test report.

**Comment by bedroge** [comment]
Test report by @bedroge
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _OpenSSL-3.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
starfive - Linux Debian GNU/Linux n/a, RISC-V-64, UNKNOWN, Python 3.10.9
See https://gist.github.com/bedroge/abdae6cc829eb8bdd959ec2bea54f6db for a full test report.

**Comment by bedroge** [comment]
Test report by @bedroge
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _OpenSSL-3.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 22.04, x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.10.12
See https://gist.github.com/bedroge/81461bde1e41230f85126e2c9e3b671e for a full test report.

**Comment by bedroge** [comment]
Test report by @bedroge
#### Overview of tested easyconfigs (in order)
 * **FAIL (build issue)** _OpenSSL-1.1.eb_ (partial log available at https://gist.github.com/bedroge/bcfed58bd91a3c1396b54dc7c01ab86d)

Build succeeded for 0 out of 1 (1 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 22.04, x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.10.12
See https://gist.github.com/bedroge/1bc75b4512458291dd27debe32ce9329 for a full test report.

**Comment by SebastianAchilles** [comment]
I am not sure how to install OpenSSL 1.1 on Ubuntu 22.04. When I start a Ubuntu 22.04 container, I can only install OpenSSL 3.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _OpenSSL-1.1.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
zen2-ubuntu-2004 - Linux Ubuntu 20.04.6 LTS (Focal Fossa), x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.8.10
See https://gist.github.com/SebastianAchilles/b5741894950725af412cac6c5a0b3df5 for a full test report.

**Comment by bedroge** [comment]
> I am not sure how to install OpenSSL 1.1 on Ubuntu 22.04. When I start a Ubuntu 22.04 container, I can only install OpenSSL 3.

I have `libssl1.1` installed, but I'm not sure how I got that, maybe because my 22.04 installation was upgraded from 20.04 (?). Anyway, it's a bit of a weird and confusing use case, so I guess we can just ignore this.

**Comment by lexming** [comment]
Test report by @lexming
#### Overview of tested easyconfigs (in order)
 * **FAIL (build issue)** _OpenSSL-1.1.eb_ (partial log available at https://gist.github.com/lexming/52a9c3804c61a756679d58be322f3548)

Build succeeded for 0 out of 1 (1 easyconfigs in total)
obelia - Linux Fedora Linux 40 (KDE Plasma), x86_64, 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz, Python 3.10.14
See https://gist.github.com/lexming/448ecafe5b13184964b137de2764ec75 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _OpenSSL-3.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
obelia - Linux Fedora Linux 40 (KDE Plasma), x86_64, 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz, Python 3.10.14
See https://gist.github.com/lexming/e657f4e04a62820f91d7a72de5418234 for a full test report.

**Review by lexming — CHANGES_REQUESTED** [review]
I found an issue in my Fedora system, where `openssl` belongs to v3. The wrapper does not check the version of the executable until the sanity checks and assumes that `openssl` corresponds to whatever version we are wrapping.

So, I made some extra fixes. Please check PR https://github.com/SebastianAchilles/easybuild-easyblocks/pull/3, it has the following changes:
* check version of `openssl` executables before wrapping
* use pattern matching for the sanity check of version of openssl executable
* simplify settings for different _generations_ of OpenSSL (replace `majmin_version` with `generation`)
* a bit of code cleanup

**Comment by SebastianAchilles** [comment]
> I found an issue in my Fedora system, where `openssl` belongs to v3. The wrapper does not check the version of the executable until the sanity checks and assumes that `openssl` corresponds to whatever version we are wrapping. This fails with OpenSSL v1.1 in this system, as openssl does not correspond to that version.
> 
> So, I made some extra fixes. Please check PR [SebastianAchilles#3](https://github.com/SebastianAchilles/easybuild-easyblocks/pull/3), it has the following changes:
> 
>     * check version of `openssl` executables before wrapping
> 
>     * use pattern matching for the sanity check of version of openssl executable
> 
>     * simplify settings for different _generations_ of OpenSSL (replace `majmin_version` with `generation`)
> 
>     * a bit of code cleanup

Thanks for the PR. The wrapping of OpenSSL 3 stopped working with the changes from [SebastianAchilles#3](https://github.com/SebastianAchilles/easybuild-easyblocks/pull/3) in recent Ubuntu versions (tested 24.04 and 22.04). I get:
```
WARNING: Not all OpenSSL components found in host system, falling back to OpenSSL in EasyBuild!
```
I will need to look into this and try to understand where it is failing.

**Comment by SebastianAchilles** [comment]
I see the following in the logs:
```
== 2024-05-29 13:59:08,552 openssl_wrapper.py:301 INFO System OpenSSL binary for version 3.0.9 not found!
```
```
$ openssl version
OpenSSL 3.0.13 30 Jan 2024 (Library: OpenSSL 3.0.13 30 Jan 2024)
```

**Comment by lexming** [comment]
Binary, headers and libraries report different versions?? What kind of crap are they doing with the packaging of OpenSSL in Ubuntu?!?!

**Comment by lexming** [comment]
@SebastianAchilles please test again, I changed approach. Now we define a minimum and maximum version and only check that each component falls in that version range. Components may have different versions between them.

**Comment by SebastianAchilles** [comment]
> @SebastianAchilles please test again, I changed approach. Now we define a minimum and maximum version and only check that each component falls in that version range. Components may have different versions between them.

Thanks a lot :+1: It is working now on Ubuntu 24.04 and 22.04. I have also tested Rocky Linux 8.9 with OpenSSL 1.1 and 3 installed in the OS. Wrapping both worked.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _OpenSSL-3.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
zen2-ubuntu-2204 - Linux Ubuntu 22.04.4 LTS (Jammy Jellyfish), x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.10.12
See https://gist.github.com/SebastianAchilles/f21cb1b2fc4c1d77b7e9905bd45505cc for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _OpenSSL-3.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
zen2-ubuntu-2404 - Linux Ubuntu 24.04 LTS (Noble Numbat), x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.12.3
See https://gist.github.com/SebastianAchilles/38853eb7eafea6737046d29ddc2f649e for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
#### Overview of tested easyconfigs (in order)
 * **FAIL (unhandled exception: expected str, bytes or os.PathLike object, not NoneType)Traceback (most recent call last):
  File "/home/lexming/.local/venv/eb/lib64/python3.10/site-packages/easybuild/main.py", line 135, in build_and_install_software
    (ec_res['success'], app_log, err) = build_and_install_one(ec, init_env)
  File "/home/lexming/.local/venv/eb/lib64/python3.10/site-packages/easybuild/framework/easyblock.py", line 4270, in build_and_install_one
    result = app.run_all_steps(run_test_cases=run_test_cases)
  File "/home/lexming/.local/venv/eb/lib64/python3.10/site-packages/easybuild/framework/easyblock.py", line 4149, in run_all_steps
    self.run_step(step_name, step_methods)
  File "/home/lexming/.local/venv/eb/lib64/python3.10/site-packages/easybuild/framework/easyblock.py", line 3984, in run_step
    step_method(self)()
  File "/tmp/eb-f336f0lv/included-easyblocks-5fwi6u7n/easybuild/easyblocks/openssl_wrapper.py", line 382, in sanity_check_step
    os.path.join('lib', os.path.basename(self.system_ssl["engines"])),
  File "/usr/lib64/python3.10/posixpath.py", line 142, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
** _OpenSSL-1.1.eb_ 
 * **SUCCESS** _OpenSSL-3.eb_ 

Build succeeded for 1 out of 2 (2 easyconfigs in total)
obelia - Linux Fedora Linux 40 (KDE Plasma), x86_64, 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz, Python 3.10.14
See https://gist.github.com/lexming/8a130b918ba88fa78dcf3ca276ba3f07 for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _OpenSSL-1.1.eb_ 
 * **SUCCESS** _OpenSSL-3.eb_ 

Build succeeded for 2 out of 2 (2 easyconfigs in total)
skl-rockylinux-89 - Linux Rocky Linux 8.9, x86_64, Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (skylake), 1 x NVIDIA NVIDIA RTX A4000, 555.42.02, Python 3.6.8
See https://gist.github.com/SebastianAchilles/396f89ba33b51b388a3aaff0a5ac8f04 for a full test report.

**Comment by SebastianAchilles** [comment]
Building OpenSSL from source is causing problems. I have seen this with OpenSSL 3 on Ubuntu 20.04 and OpenSSL 1.1 on RockyLinux 9.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
#### Overview of tested easyconfigs (in order)
 * **FAIL (unhandled exception: expected str, bytes or os.PathLike object, not NoneType)Traceback (most recent call last):
  File "/home/easybuild/.local/easybuild/software/EasyBuild/4.9.1/lib/python3.9/site-packages/easybuild/main.py", line 135, in build_and_install_software
    (ec_res['success'], app_log, err) = build_and_install_one(ec, init_env)
  File "/home/easybuild/.local/easybuild/software/EasyBuild/4.9.1/lib/python3.9/site-packages/easybuild/framework/easyblock.py", line 4270, in build_and_install_one
    result = app.run_all_steps(run_test_cases=run_test_cases)
  File "/home/easybuild/.local/easybuild/software/EasyBuild/4.9.1/lib/python3.9/site-packages/easybuild/framework/easyblock.py", line 4149, in run_all_steps
    self.run_step(step_name, step_methods)
  File "/home/easybuild/.local/easybuild/software/EasyBuild/4.9.1/lib/python3.9/site-packages/easybuild/framework/easyblock.py", line 3984, in run_step
    step_method(self)()
  File "/tmp/eb-_hlcigf_/included-easyblocks-7jgahip8/easybuild/easyblocks/openssl_wrapper.py", line 382, in sanity_check_step
    os.path.join('lib', os.path.basename(self.system_ssl["engines"])),
  File "/usr/lib64/python3.9/posixpath.py", line 142, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
** _OpenSSL-1.1.eb_ 
 * **SUCCESS** _OpenSSL-3.eb_ 

Build succeeded for 1 out of 2 (2 easyconfigs in total)
bwd-rockylinux-94 - Linux Rocky Linux 9.4 (Blue Onyx), x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), 2 x NVIDIA NVIDIA GeForce GTX 1060 6GB, 535.161.08, Python 3.9.18
See https://gist.github.com/SebastianAchilles/75c9bad17c942712ecb46942e7d7bef4 for a full test report.

**Comment by lexming** [comment]
indeed, that's my fault, on it...

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
#### Overview of tested easyconfigs (in order)
 * **FAIL (unhandled exception: expected str, bytes or os.PathLike object, not NoneType)Traceback (most recent call last):
  File "/home/easybuild/.local/easybuild/software/EasyBuild/4.9.1/lib/python3.8/site-packages/easybuild/main.py", line 135, in build_and_install_software
    (ec_res['success'], app_log, err) = build_and_install_one(ec, init_env)
  File "/home/easybuild/.local/easybuild/software/EasyBuild/4.9.1/lib/python3.8/site-packages/easybuild/framework/easyblock.py", line 4270, in build_and_install_one
    result = app.run_all_steps(run_test_cases=run_test_cases)
  File "/home/easybuild/.local/easybuild/software/EasyBuild/4.9.1/lib/python3.8/site-packages/easybuild/framework/easyblock.py", line 4149, in run_all_steps
    self.run_step(step_name, step_methods)
  File "/home/easybuild/.local/easybuild/software/EasyBuild/4.9.1/lib/python3.8/site-packages/easybuild/framework/easyblock.py", line 3984, in run_step
    step_method(self)()
  File "/tmp/eb-aw027p_l/included-easyblocks-xnlj4y7v/easybuild/easyblocks/openssl_wrapper.py", line 382, in sanity_check_step
    os.path.join('lib', os.path.basename(self.system_ssl["engines"])),
  File "/usr/lib/python3.8/posixpath.py", line 142, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
** _OpenSSL-3.eb_ 

Build succeeded for 0 out of 1 (1 easyconfigs in total)
zen2-ubuntu-2004 - Linux Ubuntu 20.04.6 LTS (Focal Fossa), x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.8.10
See https://gist.github.com/SebastianAchilles/ecd489877807526381322f0f136232ab for a full test report.

**Review by lexming — CHANGES_REQUESTED** [review]
@SebastianAchilles final fix in https://github.com/SebastianAchilles/easybuild-easyblocks/pull/4 :slightly_smiling_face:

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _OpenSSL-1.1.eb_ 
 * **SUCCESS** _OpenSSL-3.eb_ 

Build succeeded for 2 out of 2 (2 easyconfigs in total)
bwd-rockylinux-94 - Linux Rocky Linux 9.4 (Blue Onyx), x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), 2 x NVIDIA NVIDIA GeForce GTX 1060 6GB, 535.161.08, Python 3.9.18
See https://gist.github.com/SebastianAchilles/917aa495cfee7c0ab46646e9cebc63d1 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _OpenSSL-1.1.eb_ 
 * **SUCCESS** _OpenSSL-3.eb_ 

Build succeeded for 2 out of 2 (2 easyconfigs in total)
obelia - Linux Fedora Linux 40 (KDE Plasma), x86_64, 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz, Python 3.10.14
See https://gist.github.com/lexming/4946999f31d2c9e17688ea7b591e9a81 for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _OpenSSL-3.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
zen2-ubuntu-2004 - Linux Ubuntu 20.04.6 LTS (Focal Fossa), x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.8.10
See https://gist.github.com/SebastianAchilles/243e309951c3b0d45438ff4b64058e08 for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen3
EB_BRANCH=5.0.x
EB_ARGS="OpenSSL-1.1.eb OpenSSL-3.eb"

**Comment by lexming** [comment]
@boegelbot: please test @ generoso
EB_ARGS="OpenSSL-1.1.eb OpenSSL-3.eb"

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen3
EB_BRANCH=5.0.x
EB_ARGS="OpenSSL-1.1.eb OpenSSL-3.eb"

**Comment by bedroge** [comment]
Test report by @bedroge
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _OpenSSL-3.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
starfive - Linux Debian GNU/Linux n/a, RISC-V-64, UNKNOWN, Python 3.10.9
See https://gist.github.com/bedroge/188feade882d8c516f3754569e584f16 for a full test report.

**Comment by bedroge** [comment]
Test report by @bedroge
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _OpenSSL-1.1.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
starfive - Linux Debian GNU/Linux n/a, RISC-V-64, UNKNOWN, Python 3.10.9
See https://gist.github.com/bedroge/665850dc7d508bd3d15b0682ccf7e41e for a full test report.

**Comment by lexming** [comment]
Overview of systems tested

| System  | OpenSSL v1.1 | OpenSSL v3 |
| ------------- | ------------- |------------- |
| Rocky 8.9  | :heavy_check_mark:   (wrap, native)  | :heavy_check_mark: (wrap, compat) |
| Rocky 9.4  | :heavy_check_mark:  (source)  | :heavy_check_mark:  (wrap, native) |
| Fedora 40 | :heavy_check_mark:  (source)  | :heavy_check_mark:  (wrap, native) |
| Ubuntu 22.04 | :heavy_check_mark:  (wrap, compat)  | :heavy_check_mark: (wrap, native) |
| Debian Bookworm | :heavy_check_mark:  (wrap, native)  | :heavy_check_mark: (wrap, compat) |

source = OpenSSL built from source
wrap, native = wrap system OpenSSL components in standard locations
wrap, compat = wrap system OpenSSL components in non-standard locations (compatibility packages)

**Comment by Micket** [comment]
Test report by @Micket
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _OpenSSL-3.eb_ 
 * **SUCCESS** _OpenSSL-1.1.eb_ 

Build succeeded for 2 out of 2 (2 easyconfigs in total)
vera-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/797efc5be78fe36385a873cdb6a92954 for a full test report.

**Comment by lexming** [comment]
Merging, thanks @SebastianAchilles !

**Pull request merged**
