### PR TITLE
enhance cuDNN easyblock to verify that EULA is accepted before installing it

### PR DESCRIPTION
**Pull request by ocaisa**

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3
EB_ARGS="--accept-eula=CUDA --installpath /tmp/$USER/pr3473 cuDNN-8.9.7.29-CUDA-12.3.0.eb"

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3
EB_ARGS="--accept-eula-for=CUDA --installpath /tmp/$USER/pr3473 cuDNN-8.9.7.29-CUDA-12.3.0.eb"

**Comment by ocaisa** [comment]
@boegel The last test was an expected failure that shows that this works: the `cuDNN` EULA had _not_ been accepted.

**Review by boegel — APPROVED** [review]
lgtm

**Pull request merged**
