### PR TITLE
use custom RPATH sanity check for Go packages that doesn't actually check for an RPATH section in the binary

### PR DESCRIPTION
**Pull request by bedroge**
With RPATH support enabled, the RPATH sanity check of the `GoPackage` easyblock always fails. See https://github.com/easybuilders/easybuild-easyconfigs/issues/17516.

This implements @casparvl's suggestion (https://github.com/easybuilders/easybuild-easyconfigs/issues/17516#issuecomment-1473843382) and doesn't run the `readelf` command on these binaries. In the rare case that a binary does actually depend on some external library, an error should be printed that explains that the current RPATH wrappers don't work for Go, and a link to the issue is printed as well.

### CODE REVIEW

**Comment by bedroge** [comment]
Test report by @bedroge
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _SeqKit-2.3.1.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 22.04, x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.10.6
See https://gist.github.com/bedroge/e27f46092773aa381ce599368b1238d9 for a full test report.

**Review by boegel — CHANGES_REQUESTED** [review]
@bedroge Rather than copy-pasting the body of `EasyBlock.sanity_check_rpath` and stripping out the stuff related to `readelf_rpath_regex`, can't we make the `readelf` part of `EasyBlock.sanity_check_rpath` optional (but enabled by default), so we can just do this here?

```python
super(EB_Go, self).sanity_check_rpath(check_readelf_rpath=False)
```

**Comment by bedroge** [comment]
> @bedroge Rather than copy-pasting the body of `EasyBlock.sanity_check_rpath` and stripping out the stuff related to `readelf_rpath_regex`, can't we make the `readelf` part of `EasyBlock.sanity_check_rpath` optional (but enabled by default), so we can just do this here?
> 
> ```python
> super(EB_Go, self).sanity_check_rpath(check_readelf_rpath=False)
> ```

Yes, that's a good idea, makes it much more reusable.

Related to that: the issue also popped up for https://github.com/easybuilders/easybuild-easyconfigs/issues/17516, but this makes me wonder if there's a way to easily apply the same thing for easyconfigs like that one without having to implement a custom easyblock? Would it, for instance, make sense to have a list of application names for which the step gets skipped anyway, or add some easyconfig parameter that can be used to skip the step?

**Comment by boegel** [comment]
> > @bedroge Rather than copy-pasting the body of `EasyBlock.sanity_check_rpath` and stripping out the stuff related to `readelf_rpath_regex`, can't we make the `readelf` part of `EasyBlock.sanity_check_rpath` optional (but enabled by default), so we can just do this here?
> > ```python
> > super(EB_Go, self).sanity_check_rpath(check_readelf_rpath=False)
> > ```
> 
> Yes, that's a good idea, makes it much more reusable.
> 
> Related to that: the issue also popped up for [easybuilders/easybuild-easyconfigs#17516](https://github.com/easybuilders/easybuild-easyconfigs/issues/17516), but this makes me wonder if there's a way to easily apply the same thing for easyconfigs like that one without having to implement a custom easyblock? Would it, for instance, make sense to have a list of application names for which the step gets skipped anyway, or add some easyconfig parameter that can be used to skip the step?

We could indeed also add an easyconfig parameter so the `readelf` part of `sanity_check_rpath` can be disabled from an easyconfig file, something like `sanity_check_rpath_readelf = False` ?

**Comment by bedroge** [comment]
Implemented the first idea in https://github.com/easybuilders/easybuild-framework/pull/4249/files, the latter can be done in an additional PR.

**Comment by bedroge** [comment]
Test report by @bedroge
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _SeqKit-2.3.1.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 22.04, x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.10.6
See https://gist.github.com/bedroge/c62f58cb1379b6b084cc58615bef3d2d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _gofasta-0.0.5.eb_ 
 * **SUCCESS** _KMCP-0.9.1.eb_ 
 * **SUCCESS** _SeqKit-2.3.1.eb_ 

Build succeeded for 3 out of 3 (3 easyconfigs in total)
node4009.donphan.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), 1 x NVIDIA NVIDIA A2, 530.30.02, Python 3.6.8
See https://gist.github.com/boegel/ffcadff88ee7c7cd02e89eb370777d4f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _gofasta-0.0.5.eb_ 
 * **SUCCESS** _KMCP-0.9.1.eb_ 
 * **SUCCESS** _SeqKit-2.3.1.eb_ 

Build succeeded for 3 out of 3 (3 easyconfigs in total)
node4009.donphan.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), 1 x NVIDIA NVIDIA A2, 530.30.02, Python 3.6.8
See https://gist.github.com/boegel/1342b3ab886293fd1d9041b44d9035ed for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Pull request merged**
