### PR TITLE
update LLVM easyblock to put 'cmake' symlink in place so separate CMake modules requires for LLVM 15+ can be found

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _LLVM-9.0.0-GCCcore-8.3.0.eb_ 
 * **SUCCESS** _LLVM-10.0.1-GCCcore-10.2.0.eb_ 
 * **SUCCESS** _LLVM-11.0.0-GCCcore-10.2.0.eb_ 
 * **SUCCESS** _LLVM-12.0.1-GCCcore-11.2.0.eb_ 
 * **SUCCESS** _LLVM-14.0.3-GCCcore-11.3.0.eb_ 

Build succeeded for 5 out of 5 (5 easyconfigs in total)
node3522.doduo.os - Linux RHEL 8.4, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/f8b92378a9d7a414e51e0e3185ebb196 for a full test report.

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Test report by @branfosj
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _LLVM-14.0.3-GCCcore-11.3.0.eb_ 
 * **SUCCESS** _LLVM-11.1.0-GCCcore-10.3.0.eb_ 

Build succeeded for 2 out of 2 (2 easyconfigs in total)
bear-pg0105u36b.bear.cluster - Linux RHEL 8.5, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/a735f66537c55545a3ad19fb5fafe654 for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @boegel!

**Pull request merged**
