### PR TITLE
avoid dependency on 'which' command in sanity check for Python, use 'command -v' instead

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _Python-2.7.18-GCCcore-10.2.0.eb_ 
 * **SUCCESS** _Python-3.9.6-GCCcore-11.2.0.eb_ 
 * **SUCCESS** _Python-3.6.4-intel-2018a.eb_ 

Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3102.skitty.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/db0eda9640bc6d18b0bf350100f2f218 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _Python-3.9.6-GCCcore-11.2.0.eb_ 
 * **SUCCESS** _Python-2.7.18-GCCcore-11.2.0-bare.eb_ 

Build succeeded for 2 out of 2 (2 easyconfigs in total)
node2692.swalot.os - Linux Ubuntu 20.04.3 LTS (Focal Fossa), x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.8.10
See https://gist.github.com/dfb7cd55bcb7a0938ae014b1096b1770 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _Python-3.9.6-GCCcore-11.2.0.eb_ 
 * **SUCCESS** _Python-2.7.18-GCCcore-11.2.0-bare.eb_ 

Build succeeded for 2 out of 2 (2 easyconfigs in total)
node2682.swalot.os - Linux openSUSE Leap 15.3, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.15
See https://gist.github.com/49961ecd5ceae16d62c23a48737d7f4b for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _Python-3.9.6-GCCcore-11.2.0.eb_ 
 * **SUCCESS** _Python-2.7.18-GCCcore-11.2.0-bare.eb_ 

Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3502.doduo.os - Linux RHEL 8.4, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/deefa4134dcb227b89c280b363b2bff2 for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _Python-3.9.6-GCCcore-11.2.0.eb_ 
 * **SUCCESS** _Python-2.7.18-GCCcore-11.2.0-bare.eb_ 

Build succeeded for 2 out of 2 (2 easyconfigs in total)
zen2-ubuntu-eb - Linux Ubuntu 22.04, x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.10.2
See https://gist.github.com/2611f082b70dc8335cf51db9ff6273b1 for a full test report.

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _Python-3.9.6-GCCcore-11.2.0.eb_ 
 * **SUCCESS** _Python-2.7.18-GCCcore-11.2.0-bare.eb_ 

Build succeeded for 2 out of 2 (2 easyconfigs in total)
skylake-alma8-eb - Linux AlmaLinux 8.5, x86_64, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (skylake), Python 3.6.8
See https://gist.github.com/c1f8556568fe0d6d393faa4602ce81ff for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _Python-3.9.6-GCCcore-11.2.0.eb_ 
 * **SUCCESS** _Python-2.7.18-GCCcore-11.2.0-bare.eb_ 

Build succeeded for 2 out of 2 (2 easyconfigs in total)
jsczen2g1.int.jsc-zen2.easybuild-test.cluster - Linux Rocky Linux 8.5, x86_64, AMD EPYC 7742 64-Core Processor (zen2), 1 x NVIDIA GRID V100-4C, 460.73.01, Python 3.6.8
See https://gist.github.com/8336808ea5b512554730240681dd8f4b for a full test report.

**Comment by SebastianAchilles** [comment]
Going in, thanks @boegel!

**Pull request merged**
