### PR TITLE
Add new block for libgpuarray

### PR DESCRIPTION
**Pull request by akesandgren**

### CODE REVIEW

**Comment by boegel** [comment]
@akesandgren Hmm, this may be overkill, see https://github.com/easybuilders/easybuild-easyconfigs/pull/5429 (which can even be simplified, I think)...

**Comment by akesandgren** [comment]
Perhaps. Didn't think of doing it that way.
But if it produces the same results then i have no objections.

**Comment by boegel** [comment]
@akesandgren This can be closed now that https://github.com/easybuilders/easybuild-easyconfigs/pull/5429 is merged?

**Comment by akesandgren** [comment]
Not needed any longer, solved by a better easyconfig

**Pull request closed without merging**
