### PR TITLE
fixed sanity check for later versions of molpro

### PR DESCRIPTION
**Pull request by rungitta**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by migueldiascosta** [comment]
lgtm - @rungitta can you submit a test report? i.e. running eb on local easyconfig(s) with `--include-easyblocks-from-pr=2499 -u` should upload the test reports to a gist and post a comment here

**Comment by rungitta** [comment]
Test report by @rungitta
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _Molpro-mpp-2021.1.0.linux_x86_64_openmp.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
bioint02.hpc.uio.no - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) CPU E5-2690 0 @ 2.90GHz (sandybridge), Python 3.6.8
See https://gist.github.com/c299c513b12505b0c20601f15a77aeee for a full test report.

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @rungitta!

**Pull request merged**
