### PR TITLE
take into account versions like '4.x' in OpenFOAM easyblock

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by migueldiascosta** [comment]
lgtm, is there already an easyconfig for a `4.x` version to test this with?

Since it clearly won't change anything for versions that don't include `.x`, I'm prepared to waive submitting tests for all current openfoam easyconfigs ;)

**Comment by boegel** [comment]
@migueldiascosta See https://github.com/easybuilders/easybuild-easyconfigs/pull/11752 (newer toolchains don't work with OpenFOAM 4.x, partially because it requires an old Paraview).

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @boegel!

**Pull request merged**
