### PR TITLE
Change permissions of the Java builddir to avoid permission denied error

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

I've hit a `permission denied` error when installing Java. Making this permission change fixed it for me.

### CODE REVIEW

**Comment by sassy-crick** [comment]
To add: I hit the same problem on our GPFS file system and that change fixed it for me as well. 
Happy to provide the log-file if required. Either way: thanks!

**Review by bartoldeman — DISMISSED** [review]
I'm just curious how to reproduce this, with which Java version, and what files are problematic.
Perhaps this is something that can be fixed more generally in the framework?

**Comment by bartoldeman** [comment]
@sassy-crick can you please provide that logfile then?

**Comment by boegel** [comment]
Merging this as-is should be fine, I don't see how it could cause trouble, but getting more info on the problem would indeed be nice, I don't remember anyone reporting this up until now...

**Comment by sassy-crick** [comment]
@bartoldeman  Here are the two log files from the `Bazel` and `Java` builds which failed. I hope that helps.
[Bazel-3.7.2-20220322.08.log](https://github.com/easybuilders/easybuild-easyblocks/files/8353909/easybuild-Bazel-3.7.2-20220322.080813.pTTrW.log)
[Java-11.0.2-20220321.log](https://github.com/easybuilders/easybuild-easyblocks/files/8353912/easybuild-Java-11.0.2-20220321.232347.QqGlx.log)

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _Java-17.0.2.eb_ 
 * **SUCCESS** _Java-16.0.1.eb_ 
 * **SUCCESS** _Java-15.0.1.eb_ 
 * **SUCCESS** _Java-13.0.2.eb_ 
 * **SUCCESS** _Java-11.0.2.eb_ 
 * **SUCCESS** _Java-1.8.0_311.eb_ 
 * **SUCCESS** _Java-17.eb_ 
 * **SUCCESS** _Java-16.eb_ 
 * **SUCCESS** _Java-15.eb_ 
 * **SUCCESS** _Java-13.eb_ 
 * **SUCCESS** _Java-11.eb_ 
 * **SUCCESS** _Java-1.8.eb_ 

Build succeeded for 12 out of 12 (6 easyconfigs in total)
node2606.swalot.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/ea4e1e2211e0cbe786058e9232659c7f for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Pull request merged**
