### PR TITLE
add support to SystemCompiler generic easyblock to specify custom compiler command rather than always using lowercase 'name'

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by ocaisa** [comment]
This will get some love when #1106 does :P

**Comment by boegel** [comment]
@ocaisa Planning to get to that...

**Comment by ocaisa** [comment]
One issue, it's not really made clear that this information is only used to figure out what the compiler version is. It has no impact on what compiler will be used by the generated module.

What is the use case exactly?

**Comment by ocaisa** [comment]
Is it for the case where you providing a full path to the compiler? If so, that is actually not handled by the easyblock, you would need to strip the path from the incoming command to get the (current) pattern matching to work

**Comment by ocaisa** [comment]
Handling that case would be nice, and this seems like a good PR to do it in

**Comment by boegel** [comment]
I was using this to generate a `GCCcore` module with the system `gcc`, but you handled that different & perhaps better in https://github.com/easybuilders/easybuild-easyblocks/pull/1106, so let's go with that.

**Pull request closed without merging**
