### PR TITLE
add support for IBM XL compilers

### PR DESCRIPTION
**Pull request by JackPerdue**
Notes:
## 1) I need a "base" install to build upon once configured with GCC.  i.e. I currently am working on:

GCC/4.8.4-CLooG-multilib
xlmass/8.1.0
xlsmp/4.1.0
xlcbase/13.01.0
xlc/13.01.0-GCC-4.8.4-CLooG-multilib
xlfbase/15.01.0
xlf/15.01.0-GCC-4.8.4-CLooG-multilib
xlcxlf/2015B-484
MPICH2/1.5-xlcxlf-2015B-484
xlmpich2/1.5-2015B-484
## zlib/1.2.8-xlmpich2-1.5-2015B-484

I can't have xlc configured with GCC load a plain xlc so I need to call it something different (e.g. xlcbase).  And I've already written the framework to use xlc/xlf.

2) The version check was eased because:
    a) I'd prefer to specify a version for our users (vs. just "system")
    b) I don't much care for the version the compiler spits out (see comment at top)

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
@JackPerdue: would be great to have a test report for corresponding easyconfigs that uses this

**Comment by omula** [comment]
@JackPerdue I am planning to try xl compilers but I am bit lost.
I see that there's xlmass which is a math library. Does it replace BLAS, FFTW, ScalaPACK, etc?
I see that there's also ESSL and xlsmp.
I would be really happy if you can provide some guidance.

I tried to go to your website but it seems to be down.
http://www.siliconslick.com/easybuild/toolchains/compiler/ibmxl.py

Thanks in advance.

**Comment by JackPerdue** [comment]
Hmmm.... I guess siliconslick.com is down at the moment..... should be back in a bit.
In the meantime, I'm  a bit rusty but:  xlsmp and xlmass are components of the xlc and xlf compilers.  I tried to break out the common libraries between xlc/xlf (much like we need to do with icc/ifort).  For linear algebra, you will want ESSL. I'd point you to another directory on the web site but...

**Comment by omula** [comment]
It seems that siliconslick is back :) I've been navigate through the directories and this is quite interesting
http://www.siliconslick.com/easybuild/easyconfigs/curie/
Is there any other path I should have a look to?

Thank you!

**Comment by JackPerdue** [comment]
That's the place unless you have a BlueGene in which case you'll want http://www.siliconslick.com/easybuild/easyconfigs/bgsys/

Maybe start with xlcbase/13.1.0.1 and xlfbase/15.1.0.1 since I think they were my latest "best" effort (3 years ago). Maybe not.  It is all kind of a blurry mess at this point. We tossed our BlueGene rental (nobody was using it) and dropped Power compiler support so it has just withered.   I mostly just use foss now (make life much simpler).

**Comment by boegel** [comment]
I don't think this is going anywhere, so I'll go ahead and close this...

**Pull request closed without merging**
