### PR TITLE
Use build dir for big files/folders while building TensorFlow

### PR DESCRIPTION
**Pull request by Flamefire**
build_pip_package (executed after Bazel finishes) uses a temporary folder which gets large (2 GB for TF 2.9).

It uses `$TMPDIR` (via mktemp) which we set to the temporary folder created by Easybuild in PythonPackage but that might have only enough space for logs etc.
As this folder is part of the build put it inside the build directory.

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
#### Overview of tested easyconfigs (in order)
 * **FAIL (build issue)** _TensorFlow-2.9.1-foss-2022a.eb_ (partial log available at https://gist.github.com/Flamefire/764e1adeb890c6e7e8b7b76dec85521b)

Build succeeded for 0 out of 1 (1 easyconfigs in total)
n1610 - Linux RHEL 8.7 (Ootpa), x86_64, Intel(R) Xeon(R) Platinum 8470 (icelake), Python 3.8.13
See https://gist.github.com/Flamefire/9723cbe4e15fbf626551fde012634fb7 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _TensorFlow-2.9.1-foss-2022a.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
n1610 - Linux RHEL 8.7 (Ootpa), x86_64, Intel(R) Xeon(R) Platinum 8470 (icelake), Python 3.8.13
See https://gist.github.com/Flamefire/9a5248adb01e5f3191aa66f81f1b55c9 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
#### Overview of tested easyconfigs (in order)
 * **FAIL (build issue)** _TensorFlow-2.7.1-foss-2021b-CUDA-11.4.1.eb_ (partial log available at https://gist.github.com/Flamefire/8cbe0ba25846dc2f208593dffa17190e)

Build succeeded for 0 out of 1 (1 easyconfigs in total)
n1336 - Linux RHEL 8.7 (Ootpa), x86_64, Intel(R) Xeon(R) Platinum 8470 (icelake), Python 3.8.13
See https://gist.github.com/Flamefire/e48e6565fa442670a94e0e05d0b81648 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _TensorFlow-2.7.1-foss-2021b-CUDA-11.4.1.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
n1336 - Linux RHEL 8.7 (Ootpa), x86_64, Intel(R) Xeon(R) Platinum 8470 (icelake), Python 3.8.13
See https://gist.github.com/Flamefire/2d317abd7d09ebf2caf5f9c3e9ffefef for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _Bazel-6.1.0-GCCcore-12.3.0.eb_ 
 * **SUCCESS** _dill-0.3.7-GCCcore-12.3.0.eb_ 
 * **SUCCESS** _pkgconfig-1.5.5-GCCcore-12.3.0-python.eb_ 
 * **SUCCESS** _h5py-3.9.0-foss-2023a.eb_ 
 * **SUCCESS** _flatbuffers-23.5.26-GCCcore-12.3.0.eb_ 
 * **SUCCESS** _flatbuffers-python-23.5.26-GCCcore-12.3.0.eb_ 
 * **SUCCESS** _JsonCpp-1.9.5-GCCcore-12.3.0.eb_ 
 * **SUCCESS** _ml_dtypes-0.3.2-gfbf-2023a.eb_ 
 * **SUCCESS** _nsync-1.26.0-GCCcore-12.3.0.eb_ 
 * **SUCCESS** _Abseil-20230125.3-GCCcore-12.3.0.eb_ 
 * **SUCCESS** _RE2-2023-08-01-GCCcore-12.3.0.eb_ 
 * **SUCCESS** _protobuf-24.0-GCCcore-12.3.0.eb_ 
 * **SUCCESS** _protobuf-python-4.24.0-GCCcore-12.3.0.eb_ 
 * **SUCCESS** _grpcio-1.57.0-GCCcore-12.3.0.eb_ 
 * **FAIL (unhandled exception: module 'easybuild.tools.run' has no attribute 'ERROR')Traceback (most recent call last):
  File "/rds/projects/2017/branfosj-rse/easybuild/src/easybuild-framework/easybuild/main.py", line 136, in build_and_install_software
    (ec_res['success'], app_log, err) = build_and_install_one(ec, init_env)
  File "/rds/projects/2017/branfosj-rse/easybuild/src/easybuild-framework/easybuild/framework/easyblock.py", line 4292, in build_and_install_one
    result = app.run_all_steps(run_test_cases=run_test_cases)
  File "/rds/projects/2017/branfosj-rse/easybuild/src/easybuild-framework/easybuild/framework/easyblock.py", line 4167, in run_all_steps
    self.run_step(step_name, step_methods)
  File "/rds/projects/2017/branfosj-rse/easybuild/src/easybuild-framework/easybuild/framework/easyblock.py", line 4002, in run_step
    step_method(self)()
  File "/rds/projects/2017/branfosj-rse/easybuild/src/easybuild-easyblocks/easybuild/easyblocks/generic/pythonbundle.py", line 122, in extensions_step
    super(PythonBundle, self).extensions_step(*args, **kwargs)
  File "/rds/projects/2017/branfosj-rse/easybuild/src/easybuild-framework/easybuild/framework/easyblock.py", line 2906, in extensions_step
    self.install_all_extensions(install=install)
  File "/rds/projects/2017/branfosj-rse/easybuild/src/easybuild-framework/easybuild/framework/easyblock.py", line 1882, in install_all_extensions
    self.install_extensions_sequential(install=install)
  File "/rds/projects/2017/branfosj-rse/easybuild/src/easybuild-framework/easybuild/framework/easyblock.py", line 1932, in install_extensions_sequential
    txt = ext.install_extension_substep("install_extension")
  File "/rds/projects/2017/branfosj-rse/easybuild/src/easybuild-framework/easybuild/framework/extension.py", line 261, in install_extension_substep
    return substep_method(*args, **kwargs)
  File "/rds/projects/2017/branfosj-rse/easybuild/src/easybuild-easyblocks/easybuild/easyblocks/generic/pythonpackage.py", line 933, in install_extension
    step_method(self)()
  File "/dev/shm/branfosj/tmp-up-EL8/included-easyblocks-t9vnb__s/easybuild/easyblocks/tensorflow.py", line 553, in configure_step
    self.verify_system_libs_info()
  File "/dev/shm/branfosj/tmp-up-EL8/included-easyblocks-t9vnb__s/easybuild/easyblocks/tensorflow.py", line 348, in verify_system_libs_info
    if build_option('strict') == run.ERROR:
AttributeError: module 'easybuild.tools.run' has no attribute 'ERROR'
** _TensorFlow-2.15.1-foss-2023a.eb_ 

Build succeeded for 14 out of 15 (1 easyconfigs in total)
bear-pg0210u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8480CL (sapphirerapids), Python 3.6.8
See https://gist.github.com/branfosj/1ab123495b510cbfea1df456e38c5a88 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _TensorFlow-2.2.3-foss-2020b.eb_ 
 * **SUCCESS** _TensorFlow-2.7.1-foss-2021b.eb_ 

Build succeeded for 2 out of 2 (2 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/branfosj/128a6e8c810c8ffee72c11d121197523 for a full test report.

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
