### PR TITLE
use -x option for "go install" in GoPackage generic easyblock

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

Go downloads and installs package dependencies listed in the go.mod file.
it would be good to have a log of all the packages that are installed, at least in debug mode

### CODE REVIEW

**Comment by boegel** [comment]
@smoors Is there any significant downside to always using this option?

(I don't consider making the logs a little bit more verbose a significant downside)

**Comment by smoors** [comment]
> @smoors Is there any significant downside to always using this option?
> 
> (I don't consider making the logs a little bit more verbose a significant downside)

don't think so. i'll remove the debug clause.

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _elprep-5.1.1.eb_ 
 * **SUCCESS** _SeqKit-2.3.1.eb_ 
 * **SUCCESS** _Miller-6.4.0.eb_ 
 * **SUCCESS** _gofasta-0.0.5.eb_ 
 * **SUCCESS** _goalign-0.3.2.eb_ 
 * **SUCCESS** _gh-2.20.2.eb_ 
 * **SUCCESS** _rclone-1.57.0.eb_ 

Build succeeded for 7 out of 7 (7 easyconfigs in total)
node3113.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/19a96d94f8b6041b495bf9f231db3b57 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Pull request merged**
