### PR TITLE
use checkMCR.sh to determine if we have the correct MCR for FreeSurfer

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

see discussion in https://github.com/easybuilders/easybuild-easyconfigs/issues/18300

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _FreeSurfer-7.2.0-centos8_x86_64.eb_ 
 * **FAIL (build issue)** _FreeSurfer-7.3.2-centos8_x86_64.eb_ (partial log available at https://gist.github.com/branfosj/e04759878e3ba75253874e00a8cafb3d)

Build succeeded for 1 out of 2 (2 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/c9016ac894f990f4022920cf630acbbd for a full test report.

**Comment by branfosj** [comment]
^ is as expected. `FreeSurfer-7.2.0-centos8_x86_64.eb` passes, as we are using the correct MCR version and `FreeSurfer-7.3.2-centos8_x86_64.eb` fails as we need to update the MCR version.

**Comment by branfosj** [comment]
See https://github.com/easybuilders/easybuild-easyconfigs/pull/18303#issuecomment-1634347718 for a build report using this PR with the updated FreeSurfer 7.3.2 and 7.4.0 easyconfigs.

**Comment by migueldiascosta** [comment]
this is great since it will enable us to know if/when the MCR version is silently changed again

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @branfosj!

**Pull request merged**
