### PR TITLE
update `Cargo` easyblock to extract crates into a vendor subdir and overwrite git repo URLs with local paths

### PR DESCRIPTION
**Pull request by lexming**
This evolved into a 2x1 PR, apologies for the added complexity.

## Fix 1: extract crates into vendor subdir

Currently, the sources of the main `Cargo` package and the sources of all crates are all extracted into `builddir`. This is known to make some installations fail. The presence of the main sources alongside its dependencies can make `cargo` trip in identifying availability of _vendored sources_. See related [comment below](https://github.com/easybuilders/easybuild-easyblocks/pull/3118#issuecomment-1919459702).

Not all `Cargo` packages are affected, but it seems to happen on more complex packaging. For instance, known failure is a package with a virtual workspace distributing multiple crates plus a another package in a subdir.

This PR solves this issue by extracting the list of `crates` into a separate _vendor_ subdir without any sources of the main packages (_i.e._ items in the `sources` list of the easyconfig). This follows the same approach carried out by the `cargo vendor` command.

## Fix 2: overwrite crates from git repos with local paths

I hit another issue where `cargo` was failing to locate the extracted sources of a dependency pulled from a git repo. The sources are properly downloaded and extracted from the git repo and the checksuming of the local sources is done properly. However, `Cargo.lock` of the main package being installed does not list any checksum for those dependencies pulled from a git repo, so `cargo` has no way to correlate the extracted folder to this dependency.

This PR solves this issue by overwriting the repo URL of each package pulled from a git repo with the local paths to the corresponding extracted folders. This is done in the generated `.cargo/config.toml` file by using the `[patch.URL]` directive as describe in the [rust docs](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#overriding-repository-url) instead of `[source.URL]`.

For instace,

```
[source."https://github.com/ritchie46/jsonpath"]
git = "https://github.com/ritchie46/jsonpath"
rev = "24eaf0b4416edff38a4d1b6b17bc4b9f3f047b4b"
```
becomes
```
[patch."https://github.com/ritchie46/jsonpath"]
jsonpath_lib = { path = "/user/brussel/101/vsc10122/easybuild/install/skylake/build/polars/0.19.19/gfbf-2023a/easybuild_vendor/jsonpath" }
```

## Changelog
* extract crates into `self.builddir.easybuild_vendor`
* add static methods to generate filenames for downloaded tarballs and local tarballs
* be smarter in setting `finalpath` of extracted sources by detecting
* use global templates to generate `.cargo/config.toml` file
* replace `[source.URL]` with `[patch.URL]` to overwrite git repos with local paths to extracted sources

### CODE REVIEW

**Comment by lexming** [comment]
@boegelbot please test @ generoso
EB_ARGS="maturin-1.1.0-GCCcore-12.3.0.eb maturin-1.4.0-GCCcore-12.3.0-Rust-1.75.0.eb cryptography-41.0.1-GCCcore-12.3.0.eb bcrypt-4.0.1-GCCcore-12.3.0.eb pydantic-2.5.3-GCCcore-12.3.0.eb"

**Comment by lexming** [comment]
@boegelbot please test @ generoso
EB_ARGS="maturin-1.1.0-GCCcore-12.3.0.eb maturin-1.4.0-GCCcore-12.3.0-Rust-1.75.0.eb cryptography-41.0.1-GCCcore-12.3.0.eb bcrypt-4.0.1-GCCcore-12.3.0.eb pydantic-2.5.3-GCCcore-12.3.0.eb"

**Comment by lexming** [comment]
Case at hand reflecting the issue fixed by this PR is DeltaLake:
* **Failed** test with current `develop`: https://github.com/easybuilders/easybuild-easyconfigs/pull/19758#issuecomment-1919222064
* **Successful** test with this PR: https://github.com/easybuilders/easybuild-easyconfigs/pull/19758#issuecomment-1920998244

**Comment by lexming** [comment]
## Test case for fix2 - polars:
* **Failed** test with current `develop`: https://github.com/easybuilders/easybuild-easyconfigs/pull/19770#issuecomment-1921505658
* **Successful** test with this PR: https://github.com/easybuilders/easybuild-easyconfigs/pull/19770#issuecomment-1921624476

**Comment by lexming** [comment]
@Micket this is ready on my side, not touching it any more

**Review by Micket — APPROVED** [review]
lgtm

**Pull request merged**
