### PR TITLE
close log after installing Bundle component

### PR DESCRIPTION
**Pull request by boegel**
fixes https://github.com/easybuilders/easybuild-framework/issues/3533

### CODE REVIEW

**Comment by boegel** [comment]
@akesandgren and/or @zao: Can you verify that this indeed fixes the log leaking issue that was reported in https://github.com/easybuilders/easybuild-framework/issues/3533?

**Comment by akesandgren** [comment]
Yep, problem fixed (and log file now ends with "Closing log for application name libpthread-stubs" which it didn't before).

**Review by akesandgren — APPROVED** [review]
LGTM

**Comment by akesandgren** [comment]
Going in, thanks @boegel!

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _X11-20210802-GCCcore-11.2.0.eb_ 
 * **SUCCESS** _matplotlib-3.5.1-intel-2020b.eb_ 
 * **SUCCESS** _foss-2020b.eb_ 
 * **SUCCESS** _OpenSSL-1.0.eb_ 

Build succeeded for 4 out of 4 (4 easyconfigs in total)
node3510.doduo.os - Linux RHEL 8.4, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/a022c78b4ea09402a19a97a73f9e3750 for a full test report.

**Pull request merged**
