### PR TITLE
Update ROOT easyblock to support sysroot

### PR DESCRIPTION
**Pull request by ocaisa**
May help with https://github.com/EESSI/software-layer/pull/769

### CODE REVIEW

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Got a test report?

**Comment by Micket** [comment]
Test report by @Micket
#### Overview of tested easyconfigs (in order)
 * **FAIL (build issue)** _ROOT-6.30.06-foss-2023a.eb_ (partial log available at https://gist.github.com/Micket/514abf8d0c25d7bd2957e9afedfadf79)

Build succeeded for 0 out of 1 (1 easyconfigs in total)
vera-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/0353de64cf8bb10c34f143a262d431f1 for a full test report.

**Comment by ocaisa** [comment]
@boegelbot please test @ generoso
EB_ARGS="--installpath /tmp/pr3467 ROOT-6.30.06-foss-2023a.eb ROOT-6.26.10-foss-2022b.eb ROOT-6.26.06-foss-2022a.eb ROOT-6.24.06-foss-2021b.eb"

**Comment by Micket** [comment]
Test report by @Micket
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _GL2PS-1.4.2-GCCcore-12.3.0.eb_ 
 * **SUCCESS** _ROOT-6.30.06-foss-2023a.eb_ 

Build succeeded for 2 out of 2 (1 easyconfigs in total)
vera-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/0cbefe6f00f723e1d6a64e90e2cef9e7 for a full test report.

**Comment by ocaisa** [comment]
@boegelbot please test @ generoso
EB_ARGS="--installpath /tmp/pr3467 ROOT-6.30.06-foss-2023a.eb ROOT-6.26.10-foss-2022b.eb ROOT-6.26.06-foss-2022a.eb ROOT-6.24.06-foss-2021b.eb"

**Comment by ocaisa** [comment]
Successful build that uses this PR in https://github.com/EESSI/software-layer/pull/769#issuecomment-2388890642 (where `sysroot` is actually used)

**Pull request merged**
