### PR TITLE
fix OpenFOAM easyblock to support installation on Arm/aarch64 systems

### PR DESCRIPTION
**Pull request by terjekv**
- More aarch64 compatibility fixes.
  - Different versions of OpenFOAM use different abbreviations for ARM64, or Arm64...

### CODE REVIEW

**Comment by ocaisa** [comment]
@terjekv Can you close #2161 since this one replaces it?

**Comment by terjekv** [comment]
Sorted. They were supposed to be compatible, but the develop merging seems to have gone awry. Sorry.  :-(

**Comment by terjekv** [comment]
A test report is on its way, it'll take a few hours due to both OpenFOAM variants needing a full build.

**Comment by terjekv** [comment]
This is odd, I ran a test report with the easyblock, but I'm not sure where the test result ended up?

**Comment by boegel** [comment]
> This is odd, I ran a test report with the easyblock, but I'm not sure where the test result ended up?

You hit a known bug that we haven't fixed yet, see https://github.com/easybuilders/easybuild-framework/issues/3289

Your test report is there though, there's just no corresponding comment for it: https://gist.github.com/terjekv/993437e9e5b14f67e68a33dc57f54809

**Review by boegel — APPROVED** [review]
lgtm

**Pull request merged**
