### PR TITLE
Make GROMACS easyblock work with `--module-only`

### LINKED ISSUE #2399: GROMACS easyblock does not work with `--module-only`
Trying to rebuild the module leads to
```
== configuring [skipped]
== building [skipped]
== testing [skipped]
== installing [skipped]
== taking care of extensions [skipped]
== restore after iterating...
== postprocessing [skipped]
== sanity checking...
ERROR: Traceback (most recent call last):
  File "/project/def-sponsor00/ocaisa/easybuild/software/EasyBuild/4.3.4/lib/python3.8/site-packages/easybuild/main.py", line 117, in build_and_install_software
    (ec_res['success'], app_log, err) = build_and_install_one(ec, init_env)
  File "/project/def-sponsor00/ocaisa/easybuild/software/EasyBuild/4.3.4/lib/python3.8/site-packages/easybuild/framework/easyblock.py", line 3412, in build_and_install_one
    result = app.run_all_steps(run_test_cases=run_test_cases)
  File "/project/def-sponsor00/ocaisa/easybuild/software/EasyBuild/4.3.4/lib/python3.8/site-packages/easybuild/easyblocks/g/gromacs.py", line 711, in run_all_steps
    return super(EB_GROMACS, self).run_all_steps(*args, **kwargs)
  File "/project/def-sponsor00/ocaisa/easybuild/software/EasyBuild/4.3.4/lib/python3.8/site-packages/easybuild/framework/easyblock.py", line 3311, in run_all_steps
    self.run_step(step_name, step_methods)
  File "/project/def-sponsor00/ocaisa/easybuild/software/EasyBuild/4.3.4/lib/python3.8/site-packages/easybuild/framework/easyblock.py", line 3166, in run_step
    step_method(self)()
  File "/project/def-sponsor00/ocaisa/easybuild/software/EasyBuild/4.3.4/lib/python3.8/site-packages/easybuild/easyblocks/g/gromacs.py", line 589, in sanity_check_step
    lib_files.extend([
  File "/project/def-sponsor00/ocaisa/easybuild/software/EasyBuild/4.3.4/lib/python3.8/site-packages/easybuild/easyblocks/g/gromacs.py", line 590, in <listcomp>
    'lib%s%s.%s' % (x, suff, self.libext) for x in libnames + mpi_libnames for suff in suffixes
AttributeError: 'EB_GROMACS' object has no attribute 'libext'
```

### PR DESCRIPTION
**Pull request by ocaisa**
Fixes #2399

### CODE REVIEW

**Comment by ocaisa** [comment]
Test report by @ocaisa
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _GROMACS-2020.4-foss-2020a-Python-3.8.2.eb_ 
 * **FAIL (build issue)** _GROMACS-2021-foss-2020b.eb_ (partial log available at https://gist.github.com/c52873b6b7227fb0d208d2fea0110ca4)

Build succeeded for 1 out of 2 (2 easyconfigs in total)
generoso - Linux centos linux 8.2.2004, x86_64, Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz, Python 3.6.8
See https://gist.github.com/366775fb2e0b3860c5287b7306fb198f for a full test report.

**Comment by ocaisa** [comment]
Test report by @ocaisa
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _GROMACS-2020.4-foss-2020a-Python-3.8.2.eb_ 
 * **SUCCESS** _scikit-build-0.11.1-foss-2020b.eb_ 
 * **SUCCESS** _networkx-2.5-foss-2020b.eb_ 
 * **SUCCESS** _GROMACS-2021-foss-2020b.eb_ 

Build succeeded for 4 out of 4 (2 easyconfigs in total)
generoso - Linux centos linux 8.2.2004, x86_64, Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz, Python 3.6.8
See https://gist.github.com/191f4890066046004b0a8ec2b179a8f6 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _GROMACS-2019.3-foss-2019b.eb_ 
 * **SUCCESS** _GROMACS-2019.4-foss-2019b.eb_ 
 * **SUCCESS** _GROMACS-2020.1-foss-2020a-Python-3.8.2.eb_ 
 * **SUCCESS** _GROMACS-2020.4-foss-2020a-Python-3.8.2.eb_ 
 * **SUCCESS** _GROMACS-2020-foss-2019b.eb_ 
 * **SUCCESS** _GROMACS-2021-foss-2020b.eb_ 

Build succeeded for 6 out of 6 (6 easyconfigs in total)
node2601.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/4784fae2307c56ff4cde1ef25588c7e6 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _GROMACS-2021-foss-2020b.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2601.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/5b379785646d7654259d3edc23043920 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _GROMACS-2019.3-foss-2019b.eb_ 
 * **SUCCESS** _GROMACS-2019.4-foss-2019b.eb_ 
 * **SUCCESS** _GROMACS-2020-foss-2019b.eb_ 

Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3153.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/ee9b9385cd9a10638e5f84922ec68921 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _GROMACS-2019.2-fosscuda-2019a.eb_ 
 * **SUCCESS** _GROMACS-2020.5-fosscuda-2020a-Python-3.8.2.eb_ 
 * **SUCCESS** _GROMACS-2020-fosscuda-2019b.eb_ 
 * **SUCCESS** _GROMACS-2021-fosscuda-2020b.eb_ 

Build succeeded for 4 out of 4 (4 easyconfigs in total)
node3304.joltik.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/00a4dd5bc227c908e14ce42c0eb687f2 for a full test report.

**Pull request merged**
