### PR TITLE
make a project environment and manage LOAD_PATH for JuliaPackage

### PR DESCRIPTION
**Pull request by lexming**
This PR changes a bit how installations of JuliaPackages are handled to get the following improvements:

Fixes https://github.com/easybuilders/easybuild-easyconfigs/issues/19281
Alternative fix for https://github.com/easybuilders/easybuild-easyconfigs/pull/19650

* Properly handle `JuliaPackages` that have other `JuliaPackages` in their `dependencies`. Currently those dependencies are not seen by `Julia.Pkg` which results in packages being re-installed even though they can be found in the deps. This is fixed by adding all Julia packages found across dependencies to the Julia environment of the installation.
* Don't make assumptions about `DEPOT_PATH` and grab it from the Julia environment. This avoids needing `JULIA_DEPOT_PATH` in the shell environment.
* Respect user environment: user depot and its shared environment for this version of Julia are kept as top paths of `DEPOT_PATH` and `LOAD_PATH` respectively. This ensures that the user can keep using its own environment after loading JuliaPackage modules, installing additional software on its personal depot while still using packages provided by the module:
    * Don't reset `DEPOT_PATH` or `LOAD_PATH` on module load unless they are not set at all
    * Append path to installation to `DEPOT_PATH` and path to installation environment to `LOAD_PATH`

### CODE REVIEW

**Comment by lexming** [comment]
@boegelbot please test @ generoso
EB_ARGS="IJulia-1.24.0-Julia-1.8.5.eb MultilevelEstimators-0.1.0-GCC-11.2.0-Julia-1.7.2.eb Circuitscape-5.12.3-Julia-1.9.2.eb Circuitscape-5.12.3-Julia-1.7.2.eb RCall-0.13.17-foss-2022a-R-4.2.1-Julia-1.9.2.eb ResistanceGA-4.2-5-foss-2022a-R-4.2.1-Julia-1.9.2.eb "

**Comment by lexming** [comment]
@boegelbot please test @ generoso
EB_ARGS="IJulia-1.24.0-Julia-1.8.5.eb MultilevelEstimators-0.1.0-GCC-11.2.0-Julia-1.7.2.eb Circuitscape-5.12.3-Julia-1.9.2.eb Circuitscape-5.12.3-Julia-1.7.2.eb RCall-0.13.17-foss-2022a-R-4.2.1-Julia-1.9.2.eb"

**Comment by lexming** [comment]
@boegelbot please test @ generoso
EB_ARGS="IJulia-1.24.0-Julia-1.8.5.eb MultilevelEstimators-0.1.0-GCC-11.2.0-Julia-1.7.2.eb Circuitscape-5.12.3-Julia-1.9.2.eb Circuitscape-5.12.3-Julia-1.7.2.eb RCall-0.13.17-foss-2022a-R-4.2.1-Julia-1.9.2.eb"

**Comment by lexming** [comment]
@boegelbot please test @ generoso
EB_ARGS="IJulia-1.24.0-Julia-1.8.5.eb MultilevelEstimators-0.1.0-GCC-11.2.0-Julia-1.7.2.eb Circuitscape-5.12.3-Julia-1.9.2.eb Circuitscape-5.12.3-Julia-1.7.2.eb RCall-0.13.17-foss-2022a-R-4.2.1-Julia-1.9.2.eb"

**Comment by lexming** [comment]
@boegelbot please test @ generoso
EB_ARGS="IJulia-1.23.3-Julia-1.6.7.eb IJulia-1.24.0-Julia-1.8.5.eb MultilevelEstimators-0.1.0-GCC-11.2.0-Julia-1.7.2.eb Circuitscape-5.12.3-Julia-1.9.2.eb Circuitscape-5.12.3-Julia-1.7.2.eb"

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
Test report by @branfosj
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _IJulia-1.23.3-Julia-1.6.7.eb_ 
 * **SUCCESS** _IJulia-1.24.0-Julia-1.8.5.eb_ 
 * **SUCCESS** _Circuitscape-5.12.3-Julia-1.9.2.eb_ 
 * **SUCCESS** _Circuitscape-5.12.3-Julia-1.7.2.eb_ 

Build succeeded for 4 out of 4 (4 easyconfigs in total)
bear-pg0105u03a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/59be7c3f84039927157e18aa85d69f75 for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @lexming!

**Comment by branfosj** [comment]
Going in, thanks @lexming!

**Pull request merged**
