### PR TITLE
update GAMESS-US easyblock to directly write install.info

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by sassy-crick** [comment]
This is a working EasyBlock for recent releases of `GAMESS-US` releases.
The idea is instead of doing the question-and-answer bit, simply provide a `install.info`, which is the result of the Q&A session anyway. I tried to build `GAMESS-US` in such a way where I know it is working on a cluster using `sockets`. Using `mpi` should work as well but I did not test that. I have tried to include other features like `OpenMP` which works, but I have not really done any work with for example `libxc`. I only tried that briefly using the EB libxc but that did not pan out during the build step so I left it out. I done some bug-catching for `mkl` as the older `compall` scripts don't have the `oneapi` feature. 
There is probably room for improving my Python, no doubt, and also room to add more to it. I fixed setting the maximum number of cores/nodes for `ddikick.x` so it can be set in the EasyConfig file, where `OpenMPI` can be turned off as well so required. 
Nice to have: 
- get libxc working
- get OpenBLAS-64 working
- CUDA?

**Comment by saromleang** [comment]
Have a look at ` ./bin/create-install-info.py --help` within the GAMESS directory. We use for our internal continuous integration.

**Comment by sassy-crick** [comment]
> Have a look at ` ./bin/create-install-info.py --help` within the GAMESS directory. We use for our internal continuous integration.

@saromleang Thanks for pointing that out to us! That looks promising. Just to confirm: any changes to the ''install.info'' script will be taken care of by running that command.So if a new field is added, the script will be automatically updated.  Is that correct?

**Comment by saromleang** [comment]
> > Have a look at ` ./bin/create-install-info.py --help` within the GAMESS directory. We use for our internal continuous integration.
> 
> @saromleang Thanks for pointing that out to us! That looks promising. Just to confirm: any changes to the ''install.info'' script will be taken care of by running that command.So if a new field is added, the script will be automatically updated. Is that correct?

Yes, we have a document template for install.info that is leverage by ` ./bin/create-install-info.py` that keeps up with any changes to fields in install.info. Just be aware that ` ./bin/create-install-info.py` does not handle all targets (e.g., hpe-cray-ex). But the most common target `linux64` should be fully support along with build options under `linux64`.

**Review by Micket — CHANGES_REQUESTED** [review]
Please do something along the lines of
```python3
buildopts = dict()
...
buildopts['VB2000'] = self.cfg['use_bundled_vb2000']
...
for key, val in buildopts.items():
    f.write('setenv', key, val, '\n')
```

**Review by lexming — CHANGES_REQUESTED** [review]
I really like this approach of directly writing `install.info` instead going through the question/answer game. However there are several parts of the easyblock that need improvement.

I've been carefully reviewing the code of this easyblock and I made extensive changes to it that address the main problems outlined below. Please check my changes in https://github.com/sassy-crick/easybuild-easyblocks/pull/1 and if you agree with them merge it to this PR.

**Comment by akesandgren** [comment]
@sassy-crick ping on this one...

**Comment by lexming** [comment]
@sassy-crick your commits are now part of https://github.com/easybuilders/easybuild-easyblocks/pull/3047 where we are continuing this PR.

Closing as superseded by https://github.com/easybuilders/easybuild-easyblocks/pull/3047

**Pull request closed without merging**
