### PR TITLE
build single-file shared libraries for imkl so it can be used as FlexiBLAS backend via $FLEXIBLAS_LIBRARY_PATH

### PR DESCRIPTION
**Pull request by bartoldeman**
By building FlexiBLAS compatible libraries and pointing FLEXIBLAS_LIBRARY_PATH to them on the imkl side and creating a configuration file on the FlexiBLAS side, FlexiBLAS no longer needs imkl as a (build)dependency.

### CODE REVIEW

**Comment by bartoldeman** [comment]
Notes:
1. The same technique can be applied to BLIS or OpenBLAS as well, by using their libraries directly as backend:
https://github.com/mpimd-csc/flexiblas/issues/13#issuecomment-782828653
2. An alternative is to use an imkl-FlexiBLAS module, instead of including it directly into imkl but this looks simpler.
3. The imkl/BLIS/OpenBLAS modules could in principle set the environment variable FLEXIBLAS=imkl (etc.) as well, so loading the module would activate the backend. So far we haven't done that but have we considered it?

https://github.com/easybuilders/easybuild-easyconfigs/issues/14332

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _FlexiBLAS-3.0.4-GCC-10.3.0.eb_ 
 * **SUCCESS** _FlexiBLAS-3.0.4-GCC-11.2.0.eb_ 
 * **SUCCESS** _imkl-2019.5.281-gompi-2019b.eb_ 
 * **SUCCESS** _imkl-2019.5.281-gompic-2019b.eb_ 
 * **SUCCESS** _imkl-2019.5.281-iompi-2019b.eb_ 
 * **SUCCESS** _imkl-2020.1.217-iimpi-2020a.eb_ 
 * **SUCCESS** _imkl-2020.4.304-gompi-2020b.eb_ 
 * **SUCCESS** _imkl-2020.4.304-iimpi-2020b.eb_ 
 * **SUCCESS** _imkl-2021.2.0-gompi-2021a.eb_ 
 * **SUCCESS** _imkl-2021.2.0-iimpi-2021a.eb_ 
 * **SUCCESS** _imkl-2021.3.0-gompi-2021a.eb_ 
 * **SUCCESS** _imkl-2021.4.0.eb_ 

Build succeeded for 12 out of 12 (12 easyconfigs in total)
node3112.skitty.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/7a60b2e2f515b20417f9ad3e3c79e8e0 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _FlexiBLAS-3.0.4-GCC-10.3.0.eb_ 
 * **SUCCESS** _FlexiBLAS-3.0.4-GCC-11.2.0.eb_ 
 * **SUCCESS** _imkl-2019.5.281-gompi-2019b.eb_ 
 * **SUCCESS** _imkl-2019.5.281-gompic-2019b.eb_ 
 * **SUCCESS** _imkl-2019.5.281-iompi-2019b.eb_ 
 * **SUCCESS** _imkl-2020.1.217-iimpi-2020a.eb_ 
 * **SUCCESS** _imkl-2020.4.304-gompi-2020b.eb_ 
 * **SUCCESS** _imkl-2020.4.304-iimpi-2020b.eb_ 
 * **SUCCESS** _imkl-2021.2.0-gompi-2021a.eb_ 
 * **SUCCESS** _imkl-2021.2.0-iimpi-2021a.eb_ 
 * **SUCCESS** _imkl-2021.3.0-gompi-2021a.eb_ 
 * **SUCCESS** _imkl-2021.4.0.eb_ 

Build succeeded for 12 out of 12 (12 easyconfigs in total)
node3575.doduo.os - Linux RHEL 8.4, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/4c0dfa123456ef27d094749cc06b1c74 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Pull request merged**
