### PR TITLE
use `DYNAMIC_ARCH=1` when building OpenBLAS with `--optarch=GENERIC`

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--installpath /tmp/$USER/pr3492 --optarch=GENERIC OpenBLAS-0.3.21-GCC-12.2.0.eb OpenBLAS-0.3.23-GCC-12.3.0.eb OpenBLAS-0.3.24-GCC-13.2.0.eb"

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3
EB_ARGS="--installpath /tmp/$USER/pr3492 OpenBLAS-0.3.21-GCC-12.2.0.eb OpenBLAS-0.3.23-GCC-12.3.0.eb OpenBLAS-0.3.24-GCC-13.2.0.eb"

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _OpenBLAS-0.3.21-GCC-12.2.0.eb_ 
 * **SUCCESS** _OpenBLAS-0.3.23-GCC-12.3.0.eb_ 
 * **SUCCESS** _OpenBLAS-0.3.24-GCC-13.2.0.eb_ 

Build succeeded for 3 out of 3 (3 easyconfigs in total)
aarch64-neoverse-n1-node1.int.aws-rocky88-202310.eessi.io - Linux Rocky Linux 8.8, AArch64, ARM UNKNOWN (neoverse_n1), Python 3.6.8
See https://gist.github.com/boegel/567291571e7f80c0f1169c43846e0f1a for a full test report.

**Review by bedroge — APPROVED** [review]
Also checked the logs of the generic aarch64 builds in https://github.com/EESSI/software-layer/pull/793. The `make` command has `DYNAMIC_ARCH=1  TARGET=ARMV8`, and the compiler flags contain `-march=armv8-a -mtune=generic`.

So, looks good to me!

**Pull request merged**
