### PR TITLE
fixing fftw reprod by skipping early if configopts is a list

### PR DESCRIPTION
**Pull request by mboisson**
Related to https://github.com/easybuilders/easybuild-easyblocks/issues/1574
Building the "reprod" recipe fails with 
```
  File "/cvmfs/soft.computecanada.ca/easybuild/lib/python2.7/site-packages/easybuild-framework/easybuild/framework/easyblock.py", line 2860, in build_and_install_one
    result = app.run_all_steps(run_test_cases=run_test_cases)
  File "/cvmfs/soft.computecanada.ca/easybuild/lib/python2.7/site-packages/easybuild-easyblocks/easybuild/easyblocks/f/fftw.py", line 212, in run_all_steps
    self.cfg.update('configopts', [' '.join(prec_configopts) + ' ' + common_config_opts])
TypeError: cannot concatenate 'str' and 'list' objects
``` 

if not for this PR.

### CODE REVIEW

**Comment by mboisson** [comment]
Presumably, one could by themselves have multiple configopts if they want to trigger multiple builds (like we do for python support in other packages). I don't know if this happens much with FFTW ? 

Also, even though  easybuilders/easybuild-framework#2664  possibly fix the reprod issue for future versions, it does not help for software packages that have already been installed.

**Comment by akesandgren** [comment]
So, should we merge this or not? @boegel

**Comment by boegel** [comment]
I'm not sure, just skipping all the stuff we do if `configopts` is not specified as a string makes me a bit nervous...

Maybe people naively try to use a list of values for `configopts` themselves in an `FFTW` easyconfig?
If so, it shouldn't (relatively silently, since `log.warning` only goes to the log file) skip the normal iterative confguration we do...

Instead, it should fail hard with a friendly error message imho...

**Comment by mboisson** [comment]
If the reprove issue has been solved with the more recent refactoring, then that’s fine. This PR was to allow the reprod to go through without error, so issuing an error would not work in that case.
  

  
  

  
  
>

**Comment by boegel** [comment]
@mboisson Well, we would still get a cleaner error in case someone tries to specify `configopts` as a list by mistake, which is better than producing a traceback...

Do you mind replacing the `log.warning` + `log.debug` with

```python
raise EasyBuildError("Value for configopts parameter must be a string value, got %s", self.cfg['configopts'])
```

**Comment by damianam** [comment]
@mboisson ping

**Comment by mboisson** [comment]
I don't think that we should fail if an easyconfig purposefully uses an array of configopts in order to create multiple builds (as used to be done by the reprod easyconfig).

**Comment by mboisson** [comment]
This may no longer apply. Closing.

**Pull request closed without merging**
