### PR TITLE
use more test programs in sanity check step of OpenMPI easyblock

### PR DESCRIPTION
**Pull request by SebastianAchilles**
(created using `eb --new-pr`)

These additional tests should catch some problems, e.g. the one we noticed in https://github.com/easybuilders/easybuild-easyconfigs/issues/18925

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _OpenMPI-4.1.5-GCC-12.3.0.eb_ 
 * **SUCCESS** _OpenMPI-4.1.4-GCC-12.2.0.eb_ 
 * **SUCCESS** _OpenMPI-4.1.4-GCC-11.3.0.eb_ 
 * **SUCCESS** _OpenMPI-4.1.1-GCC-11.2.0.eb_ 
 * **SUCCESS** _OpenMPI-4.1.1-GCC-10.3.0.eb_ 

Build succeeded for 5 out of 5 (5 easyconfigs in total)
bwd-rockylinux-92 - Linux Rocky Linux 9.2 (Blue Onyx), x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.9.16
See https://gist.github.com/SebastianAchilles/62483c77f6427329143be0e040b67191 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _OpenMPI-3.1.1-GCC-7.3.0-2.30.eb_ 
 * **SUCCESS** _OpenMPI-3.1.4-GCC-8.3.0.eb_ 
 * **SUCCESS** _OpenMPI-3.1.3-GCC-8.2.0-2.31.1.eb_ 

Build succeeded for 3 out of 3 (3 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/branfosj/330837929887b68c28a5fd26743bf7a3 for a full test report.

**Comment by branfosj** [comment]
@boegelbot please test @ generoso EB_ARGS="OpenMPI-3.1.1-GCC-7.3.0-2.30.eb OpenMPI-3.1.4-GCC-8.3.0.eb OpenMPI-3.1.3-GCC-8.2.0-2.31.1.eb OpenMPI-4.0.3-GCC-9.3.0.eb OpenMPI-4.0.5-GCC-10.2.0.eb OpenMPI-4.1.1-GCC-10.3.0.eb OpenMPI-4.1.1-GCC-11.2.0.eb OpenMPI-4.1.4-GCC-11.3.0.eb OpenMPI-4.1.4-GCC-12.2.0.eb OpenMPI-4.1.5-GCC-12.3.0.eb OpenMPI-4.1.6-GCC-13.2.0.eb"
CORE_CNT=16

**Comment by branfosj** [comment]
Test report by @branfosj
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _OpenMPI-4.1.4-NVHPC-22.7-CUDA-11.7.0.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0208u03a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), 1 x NVIDIA NVIDIA A100-SXM4-40GB, 520.61.05, Python 3.6.8
See https://gist.github.com/branfosj/9896c6e33b6b1bd31e44959647eb789e for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _OpenMPI-4.0.3-GCC-9.3.0.eb_ 
 * **SUCCESS** _OpenMPI-4.0.5-GCC-10.2.0.eb_ 

Build succeeded for 2 out of 2 (2 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/branfosj/662bc7c22f60006f8eff84f48fce3f21 for a full test report.

**Comment by branfosj** [comment]
@boegelbot please test @ generoso EB_ARGS="OpenMPI-3.1.1-GCC-7.3.0-2.30.eb OpenMPI-3.1.4-GCC-8.3.0.eb OpenMPI-3.1.3-GCC-8.2.0-2.31.1.eb OpenMPI-4.0.3-GCC-9.3.0.eb OpenMPI-4.0.5-GCC-10.2.0.eb OpenMPI-4.1.1-GCC-10.3.0.eb OpenMPI-4.1.1-GCC-11.2.0.eb OpenMPI-4.1.4-GCC-11.3.0.eb OpenMPI-4.1.4-GCC-12.2.0.eb OpenMPI-4.1.5-GCC-12.3.0.eb OpenMPI-4.1.6-GCC-13.2.0.eb --module-only"

**Comment by branfosj** [comment]
Test report by @branfosj
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _OpenMPI-4.1.1-intel-compilers-2021.2.0.eb_ 
 * **SUCCESS** _OpenMPI-4.1.1-intel-compilers-2021.4.0.eb_ 
 * **SUCCESS** _OpenMPI-4.1.5-intel-compilers-2023.1.0.eb_ 

Build succeeded for 3 out of 3 (3 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/4526d9959207763c248333e2aff99a01 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _OpenMPI-4.1.1-GCC-10.3.0.eb_ 
 * **SUCCESS** _OpenMPI-4.1.1-GCC-11.2.0.eb_ 
 * **SUCCESS** _OpenMPI-4.1.4-GCC-11.3.0.eb_ 
 * **SUCCESS** _OpenMPI-4.1.4-GCC-12.2.0.eb_ 
 * **SUCCESS** _OpenMPI-4.1.5-GCC-12.3.0.eb_ 
 * **FAIL (build issue)** _UCX-1.15.0-GCCcore-13.2.0.eb_ (partial log available at https://gist.github.com/branfosj/635ffb550058ae73a976315c916725b7)
 * **SUCCESS** _PMIx-4.2.6-GCCcore-13.2.0.eb_ 
 * **FAIL (build issue)** _OpenMPI-4.1.6-GCC-13.2.0.eb_ (partial log available at https://gist.github.com/branfosj/c7877cf995398dc4fc2feb3336265844)

Build succeeded for 6 out of 8 (6 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/2db981ae5f831bf1c15df7e1d9947eeb for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _UCX-1.15.0-GCCcore-13.2.0.eb_ 
 * **FAIL (build issue)** _OpenMPI-4.1.6-GCC-13.2.0.eb_ (partial log available at https://gist.github.com/branfosj/0d93a50c61d0ea934abc23177e7c1972)

Build succeeded for 1 out of 2 (1 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/9112e9ed65dbf65b24e52145842e8d98 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _OpenMPI-4.1.6-GCC-13.2.0.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/7d3bed87761312bf3313bd6624780b66 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _OpenMPI-3.1.4-GCC-8.3.0.eb_ 
 * **SUCCESS** _OpenMPI-4.0.5-GCC-10.2.0.eb_ 
 * **SUCCESS** _OpenMPI-4.1.0-GCC-10.2.0.eb_ 
 * **SUCCESS** _OpenMPI-4.1.1-GCC-10.3.0.eb_ 
 * **SUCCESS** _OpenMPI-4.1.1-GCC-11.2.0.eb_ 
 * **SUCCESS** _OpenMPI-4.1.2-GCC-10.2.0.eb_ 
 * **SUCCESS** _OpenMPI-4.1.2-GCC-11.2.0.eb_ 
 * **SUCCESS** _OpenMPI-4.1.4-GCC-11.3.0.eb_ 
 * **SUCCESS** _OpenMPI-4.1.4-GCC-12.2.0.eb_ 
 * **SUCCESS** _OpenMPI-4.1.5-GCC-12.2.0.eb_ 
 * **SUCCESS** _OpenMPI-4.1.5-GCC-12.3.0.eb_ 
 * **SUCCESS** _OpenMPI-4.1.5-intel-compilers-2023.1.0.eb_ 
 * **SUCCESS** _OpenMPI-4.1.6-GCC-13.2.0.eb_ 

Build succeeded for 13 out of 13 (13 easyconfigs in total)
node3100.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/26d4d649575d50266be1a95c3ebc1eac for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Pull request merged**
